//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class A1000
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string File_Desc { get; set; }
        public string Fld1 { get; set; }
        public string Fld2 { get; set; }
        public bool Status_Code { get; set; }
        public string fld1_desc { get; set; }
    }
}
