//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1009
    {
        public string File_No { get; set; }
        public string Ord_Id { get; set; }
        public string Loc_Code { get; set; }
        public string Ask_User { get; set; }
        public System.DateTime Ask_Date { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public bool Approve1 { get; set; }
        public string Appr_User1 { get; set; }
        public Nullable<System.DateTime> Appr_Date1 { get; set; }
        public string ReMark { get; set; }
        public int MaxIsstimes { get; set; }
        public bool Over_Flag { get; set; }
        public bool Green_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public int Status_Code { get; set; }
    }
}
