//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1002
    {
        public string Comp_Code { get; set; }
        public string Comp_Namec { get; set; }
        public string Comp_Namee { get; set; }
        public string Comp_Tel { get; set; }
        public string Comp_Fax { get; set; }
        public string Comp_Connect { get; set; }
        public string Comp_Addr { get; set; }
        public string Comp_Addren { get; set; }
        public string Comp_Email { get; set; }
        public string Comp_Http { get; set; }
        public int MyPeriodYear { get; set; }
        public int MyPeriodMonth { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public string Ver { get; set; }
        public string LogoFile { get; set; }
        public string Lg_Flag { get; set; }
        public string Comp_Addr2 { get; set; }
        public string Comp_Addr3 { get; set; }
        public string Comp_Addr4 { get; set; }
        public string Comp_AddrEn2 { get; set; }
        public string Comp_AddrEn3 { get; set; }
        public string Comp_AddrEn4 { get; set; }
        public string Tax_No { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Account { get; set; }
        public string Short_Desc { get; set; }
    }
}
