//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1007
    {
        public int Acc_Year { get; set; }
        public int Acc_Month { get; set; }
        public string Loc_Code { get; set; }
        public bool PmcAppr_Flag { get; set; }
        public string PmcAppr_User { get; set; }
        public Nullable<System.DateTime> PmcAppr_Date { get; set; }
        public string PmcUser { get; set; }
        public Nullable<System.DateTime> PmcDate { get; set; }
        public string LocUser { get; set; }
        public Nullable<System.DateTime> LocDate { get; set; }
        public bool LocAppr_Flag { get; set; }
        public string LocAppr_User { get; set; }
        public Nullable<System.DateTime> LocAppr_Date { get; set; }
        public string M15902 { get; set; }
    }
}
