//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1004
    {
        public string File_No { get; set; }
        public string Ord_ID { get; set; }
        public string Info_Type { get; set; }
        public string Po_No { get; set; }
        public string Pay_Type { get; set; }
        public string Pay_Desc { get; set; }
        public string Loc_Code { get; set; }
        public string Vdr_Code { get; set; }
        public decimal Amt { get; set; }
        public decimal Amt_F { get; set; }
        public Nullable<decimal> Amt_Bal { get; set; }
        public decimal know_Amt { get; set; }
        public string Curr_Code { get; set; }
        public decimal Curr_Rate { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string Bank_Desc { get; set; }
        public string Acc_Code { get; set; }
        public string Acc_Desc { get; set; }
        public string Bank_Info { get; set; }
        public string UseFor { get; set; }
        public string Ask_User { get; set; }
        public System.DateTime Ask_Date { get; set; }
        public int Appr_Flag { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string Check_User1 { get; set; }
        public Nullable<System.DateTime> Check_Date1 { get; set; }
        public string Check_User2 { get; set; }
        public Nullable<System.DateTime> Check_Date2 { get; set; }
        public string Check_User3 { get; set; }
        public Nullable<System.DateTime> Check_Date3 { get; set; }
        public string Remark { get; set; }
        public bool Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
