//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1003
    {
        public string P_Area { get; set; }
        public string Area_Code { get; set; }
        public int ALavel { get; set; }
        public string Area_Descc { get; set; }
        public string Area_Desce { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
