//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1000
    {
        public string m_pkey { get; set; }
        public string m_skey { get; set; }
        public string m_descc { get; set; }
        public string m_desce { get; set; }
        public string m_descb { get; set; }
        public int seq_no { get; set; }
        public string erp_file { get; set; }
        public string erp_path { get; set; }
        public string icon { get; set; }
        public string remark { get; set; }
        public int status_code { get; set; }
        public bool Menu_Flag { get; set; }
        public bool rpt_flag { get; set; }
        public int Lay_Flag { get; set; }
        public string T_Code { get; set; }
        public bool Remot_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Shell_Para { get; set; }
        public Nullable<int> rptset_type { get; set; }
        public bool ERP_Flag { get; set; }
        public bool DS_Flag { get; set; }
        public bool Trade_Flag { get; set; }
        public bool Vdr_Flag { get; set; }
    }
}
