//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1005
    {
        public string Item_Grp { get; set; }
        public int Cal_Type { get; set; }
        public bool Ask_Type { get; set; }
        public bool Bol_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
