//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1012
    {
        public string File_No { get; set; }
        public int Seq_no { get; set; }
        public string Item_no { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_return { get; set; }
        public Nullable<decimal> Qty_bal { get; set; }
        public decimal Unit_Price { get; set; }
        public string Ref_no { get; set; }
        public string Remark { get; set; }
        public bool Approve { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string Mid { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime Sysdate { get; set; }
        public bool IO_Flag { get; set; }
        public string Job_No { get; set; }
        public string Tran_Type { get; set; }
        public Nullable<decimal> Tax_Rate { get; set; }
        public Nullable<bool> TaxRate_Flag { get; set; }
        public Nullable<decimal> Amt_Tax { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string TaxSt_Code { get; set; }
        public decimal Cost_Per { get; set; }
        public decimal Qty_Per { get; set; }
        public string Tran_Type1 { get; set; }
        public string Iqc_No { get; set; }
        public bool Iqc_Flag { get; set; }
        public int MaxIqcTimes { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
    }
}
