//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1011
    {
        public string File_No { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string FrmLoc_Code { get; set; }
        public string ToLoc_Code { get; set; }
        public string Ord_ID { get; set; }
        public string Tran_Type { get; set; }
        public string Rec_User { get; set; }
        public string Remark { get; set; }
        public string Vh_No { get; set; }
        public bool Approve { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime Sysdate { get; set; }
        public string VhOrd_ID { get; set; }
        public Nullable<int> Cust_Flag { get; set; }
        public string Curr_Code { get; set; }
        public string IqcLoc_Code { get; set; }
        public string cust_code { get; set; }
    }
}
