//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1017
    {
        public string ParentItem { get; set; }
        public string SonItem { get; set; }
        public string Y_Type { get; set; }
        public decimal Qty { get; set; }
        public int Color_Num { get; set; }
        public string M305 { get; set; }
        public decimal Yield { get; set; }
        public decimal Proof { get; set; }
        public bool Yield_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
