//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1015
    {
        public string SoCustCode { get; set; }
        public string SoSO { get; set; }
        public string SoSoNo { get; set; }
        public decimal SoSoSeq { get; set; }
        public int SoSoSSeq { get; set; }
        public System.DateTime SoSoDate { get; set; }
        public System.DateTime SoRtd { get; set; }
        public Nullable<System.DateTime> SoFtd { get; set; }
        public string SoItemNo { get; set; }
        public string SoSpec1 { get; set; }
        public string SoSpec3 { get; set; }
        public string SoCustPO { get; set; }
        public decimal SoUnitPrice { get; set; }
        public decimal SoDiscount { get; set; }
        public decimal SoTDiscount { get; set; }
        public decimal SoQty { get; set; }
        public Nullable<decimal> SoAmt { get; set; }
        public decimal SoQtySd { get; set; }
        public decimal SoQtyDnQty { get; set; }
        public decimal SoDnQtySd { get; set; }
        public string HostName { get; set; }
        public decimal undnqty { get; set; }
        public decimal undnamt { get; set; }
    }
}
