//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1019
    {
        public string ParentItem { get; set; }
        public string SonItem { get; set; }
        public int P_Ver { get; set; }
        public int M_Ver { get; set; }
        public decimal Qty_Per { get; set; }
        public decimal Yield { get; set; }
        public decimal Per_Cost { get; set; }
        public bool Part_Type { get; set; }
        public int Bom_Type { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public Nullable<System.DateTime> M_StEffdate { get; set; }
        public Nullable<System.DateTime> M_EdEffdate { get; set; }
        public string Remark { get; set; }
        public string MyRecord { get; set; }
        public string Ecn_no { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
