//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1029
    {
        public string Cust_Code { get; set; }
        public string Cust_Namee { get; set; }
        public string Cust_Namec { get; set; }
        public string Off_Add1 { get; set; }
        public string Off_Add2 { get; set; }
        public string Off_Add3 { get; set; }
        public string Off_Add4 { get; set; }
        public string Off_Add1C { get; set; }
        public string Off_Add2C { get; set; }
        public string Off_Add3C { get; set; }
        public string Off_Add4C { get; set; }
        public string Directors { get; set; }
        public string Off_User { get; set; }
        public string Off_Title { get; set; }
        public string Off_Tel { get; set; }
        public string Off_Fax { get; set; }
        public string Off_Email { get; set; }
        public string Off_Http { get; set; }
        public string Mkt_Add1 { get; set; }
        public string Mkt_Add2 { get; set; }
        public string Mkt_Add3 { get; set; }
        public string Mkt_Add4 { get; set; }
        public string Mkt_Fax { get; set; }
        public string Mkt_Tel { get; set; }
        public string Mkt_User { get; set; }
        public string Mkt_Title { get; set; }
        public string Mkt_Email { get; set; }
        public string Acc_Add1 { get; set; }
        public string Acc_Add2 { get; set; }
        public string Acc_Add3 { get; set; }
        public string Acc_Add4 { get; set; }
        public string Acc_Fax { get; set; }
        public string Acc_Tel { get; set; }
        public string Acc_User { get; set; }
        public string Acc_Title { get; set; }
        public string Acc_Email { get; set; }
        public string Ship_Add1 { get; set; }
        public string Ship_Add2 { get; set; }
        public string Ship_Add3 { get; set; }
        public string Ship_Add4 { get; set; }
        public string Ship_Fax { get; set; }
        public string Ship_Tel { get; set; }
        public string Ship_User { get; set; }
        public string Ship_Title { get; set; }
        public string Ship_Email { get; set; }
        public string Other_Add1 { get; set; }
        public string Other_Add2 { get; set; }
        public string Other_Add3 { get; set; }
        public string Other_Add4 { get; set; }
        public string Other_Fax { get; set; }
        public string Other_Tel { get; set; }
        public string Other_User { get; set; }
        public string Other_Title { get; set; }
        public string Other_Email { get; set; }
        public decimal Credit_High { get; set; }
        public decimal Credit_Use { get; set; }
        public string Curr_Code { get; set; }
        public string Pay_Code { get; set; }
        public string Sale_Code { get; set; }
        public string Ship_Code { get; set; }
        public int Inv_type { get; set; }
        public string Inv_gsp { get; set; }
        public string Inv_org_country { get; set; }
        public string Inv_fob { get; set; }
        public string Cust_Type { get; set; }
        public string Area_Code { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Ac_Code { get; set; }
        public decimal DisCount { get; set; }
        public string Bank_Namec { get; set; }
        public string Bank_Namee { get; set; }
        public string Bank_Ac { get; set; }
        public string Acc_Code { get; set; }
        public string Agent_Code { get; set; }
        public string Ship_Mark { get; set; }
        public string Side_MarkA { get; set; }
        public string Side_MarkA_Pic { get; set; }
        public string Side_MarkB { get; set; }
        public string Side_MarkB_Pic { get; set; }
        public string Side_MarkC { get; set; }
        public string Remark_PMC { get; set; }
        public string Remark_SHIP { get; set; }
        public string Remark_HIST { get; set; }
        public string ForWarder { get; set; }
        public decimal Qty_PerH { get; set; }
        public decimal Qty_PerL { get; set; }
        public string Sales { get; set; }
        public int Status_Code { get; set; }
        public string Status_Desc { get; set; }
        public string Shipfrom { get; set; }
        public int Cust_Grade { get; set; }
        public string Cust_Grp { get; set; }
        public string Test_Code { get; set; }
        public bool Penalty_Flag { get; set; }
        public bool COQ_Flag { get; set; }
        public bool CkCharge_Flag { get; set; }
        public bool SFO { get; set; }
        public int D_InDate { get; set; }
        public string ShipTo_Code { get; set; }
        public string InvTo_Code { get; set; }
        public bool BeUsed { get; set; }
        public int MonthEnd_Date { get; set; }
        public string M230 { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
        public string Short_Desc { get; set; }
        public decimal Tax_Rate { get; set; }
        public bool TaxRate_Flag { get; set; }
        public string TaxSt_Code { get; set; }
        public string L001D { get; set; }
        public string D004E { get; set; }
        public string PCust_Code { get; set; }
        public string Cust_ID { get; set; }
        public bool export_flag { get; set; }
        public bool export_flag1 { get; set; }
        public Nullable<bool> Sale_Flag { get; set; }
        public string Sale_Desc { get; set; }
        public string Change_Desc { get; set; }
        public string Compete_Shop { get; set; }
        public string Compete_Addr { get; set; }
        public string Compete_Boss { get; set; }
        public string Compete_Desc { get; set; }
        public string Price_Type { get; set; }
        public Nullable<decimal> Price_Val { get; set; }
        public Nullable<decimal> Price_Per { get; set; }
        public Nullable<System.DateTime> Book_Date { get; set; }
    }
}
