//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1026
    {
        public string Curr_Code { get; set; }
        public string Curr_Namee { get; set; }
        public string Curr_Namec { get; set; }
        public decimal Curr_Rate_Last { get; set; }
        public bool Curr_Type { get; set; }
        public string Curr_Char { get; set; }
        public bool Status_Code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Bank_Code { get; set; }
        public bool export_flag { get; set; }
        public bool export_flag1 { get; set; }
    }
}
