//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1025
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string FrmSo_No { get; set; }
        public Nullable<decimal> FrmSeq_No { get; set; }
        public string ToSo_No { get; set; }
        public Nullable<decimal> ToSeq_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_Rtn { get; set; }
        public string ToFile_No { get; set; }
        public int ToFSeq_No { get; set; }
        public string Remark { get; set; }
        public string FrmLot_No { get; set; }
        public Nullable<decimal> FrmLot_Seq_No { get; set; }
        public string ToLot_So_No { get; set; }
        public Nullable<decimal> ToLot_Seq_No { get; set; }
    }
}
