//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1039
    {
        public string File_no { get; set; }
        public int Seq_no { get; set; }
        public string So_No { get; set; }
        public decimal So_Seq { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> Qty_f { get; set; }
        public decimal Unit_Price { get; set; }
        public string Remark { get; set; }
        public string Org_File { get; set; }
        public string Cn_No { get; set; }
        public int Org_seq_no { get; set; }
        public string Tran_Type { get; set; }
        public string ToSo_No { get; set; }
        public Nullable<decimal> ToSo_Seq_No { get; set; }
        public string ToItem_No { get; set; }
        public bool G_Flag { get; set; }
        public string curr_code { get; set; }
        public decimal G_Unit_Price { get; set; }
        public bool export_flag1 { get; set; }
        public string G_No { get; set; }
        public Nullable<int> Item_Flag { get; set; }
    }
}
