//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1037
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string So_No { get; set; }
        public decimal So_Seq { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_Act { get; set; }
        public decimal Qty_Just { get; set; }
        public string Org_File_No { get; set; }
        public int Org_Seq_no { get; set; }
        public string Remark { get; set; }
        public string Tran_Type { get; set; }
        public decimal Amt_Other { get; set; }
        public bool G_Flag { get; set; }
        public decimal unit_price { get; set; }
        public bool export_flag1 { get; set; }
        public string G_No { get; set; }
        public decimal G_Unit_Price { get; set; }
        public string loc_type06 { get; set; }
        public string pos_grp { get; set; }
        public string IQC_No { get; set; }
        public int maxiqctimes { get; set; }
    }
}
