//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1038
    {
        public string File_no { get; set; }
        public string Ord_ID { get; set; }
        public string Tran_Type { get; set; }
        public System.DateTime Tran_date { get; set; }
        public string FrmLoc_Code { get; set; }
        public string ToLoc_Code { get; set; }
        public string Tran_User { get; set; }
        public int Status_Code { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Vh_No { get; set; }
        public string Last_User { get; set; }
        public string Last_Date { get; set; }
        public bool export_flag { get; set; }
        public bool ToLoc_Flag { get; set; }
        public bool DS04_Flag { get; set; }
        public Nullable<bool> Distr_Flag { get; set; }
        public bool ToLocExport_Flag { get; set; }
    }
}
