//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1048
    {
        public int Plan_Source { get; set; }
        public string Job_No { get; set; }
        public decimal Seq_No { get; set; }
        public string PItem_No { get; set; }
        public string Item_No { get; set; }
        public decimal qty { get; set; }
        public decimal qty_f { get; set; }
        public decimal qty_crap { get; set; }
        public decimal qty_r { get; set; }
        public decimal qty_planed { get; set; }
        public Nullable<System.DateTime> qty_planed_date { get; set; }
        public Nullable<decimal> qty_pr { get; set; }
        public int ma_type { get; set; }
        public int mb_type { get; set; }
        public int mc_type { get; set; }
        public int md_type { get; set; }
        public int me_type { get; set; }
        public Nullable<System.DateTime> issuetime { get; set; }
        public Nullable<System.DateTime> Last_IssueTime { get; set; }
        public decimal leadtime { get; set; }
        public Nullable<System.DateTime> purctime { get; set; }
        public string source { get; set; }
        public string item_bgrp { get; set; }
        public string item_grp { get; set; }
        public int status_code { get; set; }
        public string bom_ver { get; set; }
        public string bol_ver { get; set; }
        public decimal qty_per { get; set; }
        public decimal qty_nochange { get; set; }
        public decimal qty_yield { get; set; }
        public decimal qty_order { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public string ppitem_no { get; set; }
        public Nullable<decimal> pqty_per { get; set; }
        public Nullable<bool> useall_flag { get; set; }
        public string sysremark { get; set; }
        public Nullable<int> issuetimes { get; set; }
        public string loc_code { get; set; }
        public string work_type { get; set; }
        public string So_No { get; set; }
        public decimal So_Seq { get; set; }
        public Nullable<System.DateTime> WoDate { get; set; }
        public bool ToExcel { get; set; }
        public string Pmc_Remark { get; set; }
        public Nullable<System.DateTime> Mrp_Date { get; set; }
        public string Ord_Id { get; set; }
        public string Trace_Flag { get; set; }
        public string Cust_Code { get; set; }
        public string OurModel { get; set; }
        public bool MForecast_Flag { get; set; }
        public string Cust_Po { get; set; }
        public string YourModel { get; set; }
        public Nullable<System.DateTime> So_Ftd { get; set; }
        public int FO_Qty { get; set; }
        public bool DircPr_flag { get; set; }
        public string Precedence { get; set; }
        public bool Lot_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public int Margin_Days { get; set; }
    }
}
