//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1045
    {
        public long AutoID { get; set; }
        public string pjob_no { get; set; }
        public string sjob_no { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public string ord_id { get; set; }
        public decimal qty_f { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public bool status_code { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
        public string sysremark { get; set; }
    }
}
