//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1046
    {
        public string So_No { get; set; }
        public Nullable<decimal> seq_no { get; set; }
        public string mo_no { get; set; }
        public Nullable<bool> lot_yes { get; set; }
        public Nullable<bool> mat_flag { get; set; }
        public Nullable<int> pos { get; set; }
        public Nullable<bool> ptp { get; set; }
        public Nullable<decimal> rela_seq { get; set; }
        public string tjob_no { get; set; }
        public string Info_Type { get; set; }
        public string job_no { get; set; }
        public string work_type { get; set; }
        public string item_no { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> qty_so { get; set; }
        public Nullable<decimal> qty_sd { get; set; }
        public Nullable<decimal> qty_must { get; set; }
        public Nullable<decimal> qty_lot { get; set; }
        public Nullable<decimal> qty_pass { get; set; }
        public Nullable<decimal> qty_loss { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public Nullable<decimal> qty_issue { get; set; }
        public Nullable<decimal> qty_last { get; set; }
        public Nullable<decimal> qty_take { get; set; }
        public Nullable<decimal> qty_org { get; set; }
        public Nullable<decimal> qty_my { get; set; }
        public Nullable<decimal> qty_you { get; set; }
        public Nullable<decimal> qty_raw { get; set; }
        public Nullable<decimal> qty_raw_per { get; set; }
        public Nullable<decimal> qty_detail_loss { get; set; }
        public string wip_code { get; set; }
        public Nullable<System.DateTime> ftd_so { get; set; }
        public Nullable<System.DateTime> pst_date { get; set; }
        public Nullable<System.DateTime> pfh_date { get; set; }
        public Nullable<System.DateTime> rst_date { get; set; }
        public Nullable<System.DateTime> rfh_date { get; set; }
        public Nullable<System.DateTime> ast_date { get; set; }
        public Nullable<System.DateTime> afh_date { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_code { get; set; }
        public string item_bgrp { get; set; }
        public Nullable<bool> approve { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public string SysUser { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public Nullable<bool> mat_plan { get; set; }
        public Nullable<int> maxisstimes { get; set; }
        public string Route_Code { get; set; }
        public string Route_Ver { get; set; }
        public string Bom_Ver { get; set; }
        public Nullable<bool> Job_Raw { get; set; }
        public Nullable<decimal> toqty_bal { get; set; }
        public Nullable<int> job_kind { get; set; }
        public Nullable<int> job_source { get; set; }
        public Nullable<bool> new_y { get; set; }
        public Nullable<int> job_raw_grp { get; set; }
        public Nullable<System.DateTime> mrp_date { get; set; }
        public Nullable<decimal> mrp_qty { get; set; }
        public Nullable<bool> mps_flag { get; set; }
        public Nullable<int> job_type { get; set; }
        public string sysremark { get; set; }
        public string source { get; set; }
        public Nullable<decimal> t_qty_per { get; set; }
        public Nullable<bool> SonBom_flag { get; set; }
        public Nullable<bool> part_type { get; set; }
        public string ord_id { get; set; }
        public Nullable<bool> pp_plan { get; set; }
        public string pp_plan_user { get; set; }
        public Nullable<System.DateTime> pp_plan_date { get; set; }
        public Nullable<bool> route_flag { get; set; }
        public Nullable<bool> toprod_flag { get; set; }
        public string toprod_user { get; set; }
        public Nullable<System.DateTime> toprod_date { get; set; }
        public string loc_code { get; set; }
        public Nullable<bool> Bol_Grp_Flag { get; set; }
        public Nullable<int> Bol_Grp { get; set; }
        public string Work_GrpB { get; set; }
        public Nullable<int> R_MaxTimes { get; set; }
        public string NewItem_No { get; set; }
        public decimal Lead_Time { get; set; }
        public string Line_Code { get; set; }
        public string Line_Class { get; set; }
        public int LotMaxNo { get; set; }
        public int MaxTimes1 { get; set; }
    }
}
