//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1042
    {
        public string So_no { get; set; }
        public string Ord_Id { get; set; }
        public string Cust_code { get; set; }
        public string Cso_no { get; set; }
        public string OurModel { get; set; }
        public string Trace_Flag { get; set; }
        public string WoRemark { get; set; }
        public decimal Cn_max { get; set; }
        public bool IsDetail { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
