//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1049
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string Job_No { get; set; }
        public string Item_No { get; set; }
        public string File_No { get; set; }
        public int File_Seq_No { get; set; }
        public decimal Qty_Org { get; set; }
        public decimal Qty { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public decimal Lead_Time { get; set; }
        public Nullable<System.DateTime> PRec_Date { get; set; }
        public bool U_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
