//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1052
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string Item_No { get; set; }
        public string info_type { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime Ftd_So { get; set; }
        public Nullable<System.DateTime> Ftd_EDP { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc { get; set; }
        public decimal Rela_Seq { get; set; }
        public string Line_Rule { get; set; }
        public bool Bom_Flag { get; set; }
        public bool MatRule_Flag { get; set; }
        public bool Auto_UnFgs_Flag { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string Remark { get; set; }
        public string SysRemark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
