//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1059
    {
        public string Inv_No { get; set; }
        public int Seq_No { get; set; }
        public string So_No { get; set; }
        public decimal So_Seq { get; set; }
        public int So_SSeq { get; set; }
        public string Item_No { get; set; }
        public string Item_Type { get; set; }
        public string Your_Size { get; set; }
        public string Your_Model { get; set; }
        public string Your_Color { get; set; }
        public string Your_PoNo { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_Sd { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal DisCount { get; set; }
        public decimal T_Discount { get; set; }
        public decimal Amount { get; set; }
        public decimal Tax_Rate { get; set; }
        public bool TaxRate_Flag { get; set; }
        public string Remark { get; set; }
        public string FrmCust_Code { get; set; }
        public string Spec1 { get; set; }
        public int PL_Seq_No { get; set; }
        public string Tran_Type { get; set; }
        public decimal Other_Amt { get; set; }
        public string Check_No { get; set; }
        public Nullable<decimal> G_Unit_Price { get; set; }
        public Nullable<decimal> G_Amount { get; set; }
    }
}
