//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1053
    {
        public long MID { get; set; }
        public string File_no { get; set; }
        public int Seq_no { get; set; }
        public string item_no { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Cost { get; set; }
        public decimal Org_cost { get; set; }
        public string Curr_code { get; set; }
        public decimal Curr_rate { get; set; }
        public string Ord_Id { get; set; }
        public string Ord_no { get; set; }
        public int Ord_Seq_no { get; set; }
        public string Vdr_code { get; set; }
        public Nullable<System.DateTime> Vis_Date { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
        public string Org_File_No { get; set; }
        public Nullable<int> Org_Seq_No { get; set; }
        public string Loc_Code { get; set; }
    }
}
