//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1055
    {
        public string Loc_Code { get; set; }
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string Tran_Type { get; set; }
        public string Ord_Id { get; set; }
        public string Wo_No { get; set; }
        public string Item_No { get; set; }
        public string So_No { get; set; }
        public decimal So_Seq { get; set; }
        public decimal Qty { get; set; }
        public decimal Bal_Qty { get; set; }
        public decimal Unit_Price { get; set; }
        public System.DateTime Rec_Date { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Org_File_No { get; set; }
        public int org_seq_no { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool UseAll_Flag { get; set; }
        public long MID { get; set; }
        public decimal Qty_Use { get; set; }
        public string cust_code { get; set; }
        public bool Export_Flag { get; set; }
        public bool export_flag1 { get; set; }
        public string Bat_No { get; set; }
        public Nullable<decimal> qty_use1 { get; set; }
        public Nullable<decimal> bal_qty1 { get; set; }
        public Nullable<decimal> qty1 { get; set; }
    }
}
