//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1057
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public int SSeq_No { get; set; }
        public string Tran_Type { get; set; }
        public short IO_Flag { get; set; }
        public string FrmFile_No { get; set; }
        public int FrmSeq_No { get; set; }
        public long Mid { get; set; }
        public string Ord_Id { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string Loc_Code { get; set; }
        public string FrmLoc_Code { get; set; }
        public string ToLoc_Code { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public string Vh_No { get; set; }
        public string FrmUser { get; set; }
        public string ToUser { get; set; }
        public string So_No { get; set; }
        public decimal So_Seq_No { get; set; }
        public string ReMark { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal unit_cost { get; set; }
        public bool Export_Flag { get; set; }
        public bool export_flag1 { get; set; }
    }
}
