//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1061
    {
        public int Sys_ID { get; set; }
        public string Sys_Desc { get; set; }
        public string Item_Class { get; set; }
        public string Class_Descc { get; set; }
        public string Class_Desce { get; set; }
        public bool Status_Code { get; set; }
        public string PItem_Class { get; set; }
        public int Seq_No { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Last_User { get; set; }
        public System.DateTime Last_Date { get; set; }
        public bool export_flag { get; set; }
        public bool export_flag1 { get; set; }
    }
}
