//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1069
    {
        public string Item_No { get; set; }
        public string RItem_No { get; set; }
        public string Cust_Code { get; set; }
        public string Rpl_Reason { get; set; }
        public System.DateTime FrmDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string ReMark { get; set; }
        public bool Status_Code { get; set; }
        public string SysRemark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
