//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1063
    {
        public string Item_No { get; set; }
        public decimal Mat_Cost { get; set; }
        public decimal Prd_Cost { get; set; }
        public decimal Mat_Cost_wh { get; set; }
        public decimal Prd_Cost_wh { get; set; }
        public decimal Mat_Cost_Po { get; set; }
        public decimal Prd_Cost_Po { get; set; }
        public decimal Last_Cost_Po { get; set; }
        public decimal Last_Cost_wh { get; set; }
        public string Po_No { get; set; }
        public int po_seq_no { get; set; }
        public int Rec_Seq_No { get; set; }
        public decimal Last_Cost_Po_Ex { get; set; }
        public string Last_Cost_Po_Curr { get; set; }
        public string Rec_No { get; set; }
        public decimal Last_Cost_wh_Ex { get; set; }
        public string Last_Cost_wh_Curr { get; set; }
        public string CStrategy { get; set; }
        public decimal Std_Cost { get; set; }
        public decimal Avg_Cost { get; set; }
        public decimal Avg_Qty { get; set; }
        public decimal Yield { get; set; }
        public decimal S_Cost { get; set; }
        public decimal B_Cost { get; set; }
        public decimal F_Cost { get; set; }
        public decimal Acc_Cost { get; set; }
        public bool RelaCost { get; set; }
        public Nullable<System.DateTime> Po_Appr_Date { get; set; }
        public Nullable<System.DateTime> Rec_Appr_Date { get; set; }
        public Nullable<decimal> last_cost_po_a { get; set; }
        public Nullable<decimal> last_cost_wh_a { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal Unit_Cost { get; set; }
        public string SoCurr_Code { get; set; }
        public Nullable<decimal> Gunit_Price { get; set; }
        public string GCurr_Code { get; set; }
    }
}
