//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1066
    {
        public string Item_No { get; set; }
        public string SPEC1 { get; set; }
        public string SPEC2 { get; set; }
        public string SPEC3 { get; set; }
        public string SPEC4 { get; set; }
        public string SPEC5 { get; set; }
        public string SPEC6 { get; set; }
        public string SPEC7 { get; set; }
        public string SPEC8 { get; set; }
        public string SPEC9 { get; set; }
        public string SPEC10 { get; set; }
        public string SPEC11 { get; set; }
        public string SPEC12 { get; set; }
        public string SPEC13 { get; set; }
        public string SPEC14 { get; set; }
        public string SPEC15 { get; set; }
        public string SPEC16 { get; set; }
        public string SPEC17 { get; set; }
        public string SPEC18 { get; set; }
        public string SPEC19 { get; set; }
        public string SPEC20 { get; set; }
        public string SPEC21 { get; set; }
        public string SPEC22 { get; set; }
        public string SPEC23 { get; set; }
        public string SPEC24 { get; set; }
        public string SPEC25 { get; set; }
        public string SPEC26 { get; set; }
        public string SPEC27 { get; set; }
        public string SPEC28 { get; set; }
        public string SPEC29 { get; set; }
        public string SPEC30 { get; set; }
        public string SPEC31 { get; set; }
        public string SPEC32 { get; set; }
        public string SPEC33 { get; set; }
        public string SPEC34 { get; set; }
        public string SPEC35 { get; set; }
        public string SPEC36 { get; set; }
        public string SPEC37 { get; set; }
        public string SPEC38 { get; set; }
        public string SPEC39 { get; set; }
        public string SPEC40 { get; set; }
        public string SPEC41 { get; set; }
        public string SPEC42 { get; set; }
        public string SPEC43 { get; set; }
        public string SPEC44 { get; set; }
        public string SPEC45 { get; set; }
        public string SPEC46 { get; set; }
        public string SPEC47 { get; set; }
        public string SPEC48 { get; set; }
        public string SPEC49 { get; set; }
        public string SPEC50 { get; set; }
        public string SPEC51 { get; set; }
        public string SPEC52 { get; set; }
        public string SPEC53 { get; set; }
        public string SPEC54 { get; set; }
        public string SPEC55 { get; set; }
        public string SPEC56 { get; set; }
        public string SPEC57 { get; set; }
        public string SPEC58 { get; set; }
        public string SPEC59 { get; set; }
        public string SPEC60 { get; set; }
        public string Spec90 { get; set; }
        public string Spec91 { get; set; }
        public string Spec92 { get; set; }
        public string Spec93 { get; set; }
        public string Spec94 { get; set; }
        public string Spec95 { get; set; }
        public string Spec900 { get; set; }
        public string Spec901 { get; set; }
        public string Spec902 { get; set; }
        public string Spec903 { get; set; }
        public string Spec904 { get; set; }
        public string Spec905 { get; set; }
        public string Spec906 { get; set; }
        public string Spec907 { get; set; }
        public string Spec908 { get; set; }
        public string Spec909 { get; set; }
        public string Spec910 { get; set; }
        public string C001C05 { get; set; }
        public string C001C10 { get; set; }
        public string C001C15 { get; set; }
    }
}
