//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1070A
    {
        public string Item_No { get; set; }
        public string Loc_Code { get; set; }
        public string Bat_No { get; set; }
        public decimal Qoh { get; set; }
        public decimal Qty_Use { get; set; }
        public Nullable<decimal> Qty_Bal { get; set; }
        public decimal avg_cost { get; set; }
        public long mID { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
    }
}
