//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1075
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string Mo_No { get; set; }
        public bool Lot_Yes { get; set; }
        public bool Mat_Flag { get; set; }
        public int Pos { get; set; }
        public bool Ptp { get; set; }
        public decimal Rela_Seq { get; set; }
        public string Tjob_No { get; set; }
        public string Info_Type { get; set; }
        public string Job_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty1 { get; set; }
        public decimal Qty_Distr { get; set; }
        public decimal Qty_So { get; set; }
        public decimal Qty_Sd { get; set; }
        public decimal Qty_Must { get; set; }
        public decimal Qty_Lot { get; set; }
        public decimal Qty_Pass { get; set; }
        public decimal Qty_Loss { get; set; }
        public decimal Qty_Bal { get; set; }
        public decimal Qty_Issue { get; set; }
        public decimal Qty_Last { get; set; }
        public decimal Qty_Take { get; set; }
        public decimal Qty_Org { get; set; }
        public decimal Qty_My { get; set; }
        public decimal Qty_You { get; set; }
        public decimal Qty_Raw { get; set; }
        public decimal Qty_Raw_Per { get; set; }
        public decimal Qty_Detail_Loss { get; set; }
        public string Wip_Code { get; set; }
        public Nullable<System.DateTime> Ftd_So { get; set; }
        public Nullable<System.DateTime> Pst_Date { get; set; }
        public Nullable<System.DateTime> Pfh_Date { get; set; }
        public Nullable<System.DateTime> Rst_Date { get; set; }
        public Nullable<System.DateTime> Rfh_Date { get; set; }
        public Nullable<System.DateTime> Ast_Date { get; set; }
        public Nullable<System.DateTime> Afh_Date { get; set; }
        public string Remark { get; set; }
        public int Status_Code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string Item_Bgrp { get; set; }
        public Nullable<bool> Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public bool mat_plan { get; set; }
        public int maxisstimes { get; set; }
        public string Route_Code { get; set; }
        public string Route_Ver { get; set; }
        public Nullable<int> Bom_Ver { get; set; }
        public bool Job_Raw { get; set; }
        public decimal toqty_bal { get; set; }
        public int job_kind { get; set; }
        public int job_source { get; set; }
        public bool new_y { get; set; }
        public int job_raw_grp { get; set; }
        public Nullable<System.DateTime> mrp_date { get; set; }
        public decimal mrp_qty { get; set; }
        public bool mps_flag { get; set; }
        public int job_type { get; set; }
        public string sysremark { get; set; }
        public string source { get; set; }
        public decimal t_qty_per { get; set; }
        public bool SonBom_flag { get; set; }
        public bool part_type { get; set; }
        public string ord_id { get; set; }
        public bool pp_plan { get; set; }
        public string pp_plan_user { get; set; }
        public Nullable<System.DateTime> pp_plan_date { get; set; }
        public bool route_flag { get; set; }
        public bool toprod_flag { get; set; }
        public string toprod_user { get; set; }
        public Nullable<System.DateTime> toprod_date { get; set; }
        public string loc_code { get; set; }
        public bool Bol_Grp_Flag { get; set; }
        public int Bol_Grp { get; set; }
        public string Work_GrpB { get; set; }
        public int R_MaxTimes { get; set; }
        public string NewItem_No { get; set; }
        public int lead_time { get; set; }
        public string Line_Code { get; set; }
        public string Line_Class { get; set; }
        public int LotMaxNo { get; set; }
        public int MaxTimes1 { get; set; }
        public bool MNLine_Flag { get; set; }
        public string nLine_Code { get; set; }
        public decimal TNLead_Time { get; set; }
        public decimal NLead_Time { get; set; }
        public string Supper_Code { get; set; }
        public string M81 { get; set; }
        public string M81_User { get; set; }
        public Nullable<System.DateTime> M81_Date { get; set; }
        public Nullable<bool> ToPo_Flag { get; set; }
        public Nullable<bool> ToSo_Flag { get; set; }
        public decimal Qty_Hold { get; set; }
        public Nullable<System.DateTime> CalIssueDate { get; set; }
        public string SoCn_No { get; set; }
        public string Ecn_No { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool M811 { get; set; }
        public bool T_Flag { get; set; }
        public Nullable<decimal> qty_sample { get; set; }
        public Nullable<decimal> good_sample { get; set; }
        public Nullable<decimal> bad_sample { get; set; }
        public decimal qty_act { get; set; }
        public decimal qty_must_bal { get; set; }
        public decimal qty_reused { get; set; }
        public string mps_user { get; set; }
        public Nullable<System.DateTime> mps_date { get; set; }
        public Nullable<int> bol_ver { get; set; }
        public decimal Qty_Raw_AutoWF { get; set; }
        public decimal Qty_Max { get; set; }
        public decimal Qty_Distr_MySelf { get; set; }
        public decimal Qty_Add { get; set; }
        public string F_Order_No { get; set; }
    }
}
