//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1071A
    {
        public string item_type { get; set; }
        public int L_No { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
        public string spec11 { get; set; }
        public string spec12 { get; set; }
        public string spec13 { get; set; }
        public string spec14 { get; set; }
        public string spec15 { get; set; }
        public string spec16 { get; set; }
        public string spec17 { get; set; }
        public string spec18 { get; set; }
        public string spec19 { get; set; }
        public string spec20 { get; set; }
        public string spec21 { get; set; }
        public string spec22 { get; set; }
        public string spec23 { get; set; }
        public string spec24 { get; set; }
        public string spec25 { get; set; }
        public string spec50 { get; set; }
    }
}
