//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1071
    {
        public string Item_Type { get; set; }
        public string Item_Grp { get; set; }
        public string Type_Descc { get; set; }
        public string Type_Desce { get; set; }
        public string ReportFd { get; set; }
        public string Head_Default { get; set; }
        public string Type_Alias { get; set; }
        public string Type_Aliasc { get; set; }
        public decimal M_Cost { get; set; }
        public decimal Crap_Rate { get; set; }
        public bool IsRing { get; set; }
        public string ItemFrm { get; set; }
        public string ItemTo { get; set; }
        public string Issue_Grp { get; set; }
        public string Spec1 { get; set; }
        public string Spec2 { get; set; }
        public string Spec3 { get; set; }
        public string Spec4 { get; set; }
        public string Spec5 { get; set; }
        public string Spec6 { get; set; }
        public string Spec7 { get; set; }
        public string Spec8 { get; set; }
        public string Spec9 { get; set; }
        public string Spec10 { get; set; }
        public string Spec11 { get; set; }
        public string Spec12 { get; set; }
        public string Spec13 { get; set; }
        public string Spec14 { get; set; }
        public string Spec15 { get; set; }
        public string Spec16 { get; set; }
        public string Spec17 { get; set; }
        public string Spec18 { get; set; }
        public string Spec19 { get; set; }
        public string Spec20 { get; set; }
        public string Spec21 { get; set; }
        public string Spec22 { get; set; }
        public string Spec23 { get; set; }
        public string Spec24 { get; set; }
        public string Spec25 { get; set; }
        public string Spec26 { get; set; }
        public string Spec27 { get; set; }
        public string Spec28 { get; set; }
        public string Spec29 { get; set; }
        public string Spec30 { get; set; }
        public string Spec31 { get; set; }
        public string Spec32 { get; set; }
        public string Spec33 { get; set; }
        public string Spec34 { get; set; }
        public string Spec35 { get; set; }
        public string Spec36 { get; set; }
        public string Spec37 { get; set; }
        public string Spec38 { get; set; }
        public string Spec39 { get; set; }
        public string Spec40 { get; set; }
        public string Spec41 { get; set; }
        public string Spec42 { get; set; }
        public string Spec43 { get; set; }
        public string Spec44 { get; set; }
        public string Spec45 { get; set; }
        public string Spec46 { get; set; }
        public string Spec47 { get; set; }
        public string Spec48 { get; set; }
        public string Spec49 { get; set; }
        public string Spec50 { get; set; }
        public string Spec51 { get; set; }
        public string Spec52 { get; set; }
        public string Spec53 { get; set; }
        public string Spec54 { get; set; }
        public string Spec55 { get; set; }
        public string Spec56 { get; set; }
        public string Spec57 { get; set; }
        public string Spec58 { get; set; }
        public string Spec59 { get; set; }
        public string Spec60 { get; set; }
        public string Spec90 { get; set; }
        public string Spec91 { get; set; }
        public string Spec92 { get; set; }
        public string Spec93 { get; set; }
        public string Spec94 { get; set; }
        public string Spec95 { get; set; }
        public string Spec101 { get; set; }
        public string Spec102 { get; set; }
        public string Spec103 { get; set; }
        public string Spec104 { get; set; }
        public string Spec105 { get; set; }
        public string Spec106 { get; set; }
        public string Spec107 { get; set; }
        public string Spec108 { get; set; }
        public string Spec109 { get; set; }
        public string Spec110 { get; set; }
        public string Spec111 { get; set; }
        public string Spec112 { get; set; }
        public string Spec113 { get; set; }
        public string Spec114 { get; set; }
        public string Spec115 { get; set; }
        public string Spec116 { get; set; }
        public string Spec117 { get; set; }
        public string Spec118 { get; set; }
        public string Spec119 { get; set; }
        public string Spec120 { get; set; }
        public string Spec121 { get; set; }
        public string Spec122 { get; set; }
        public string Spec123 { get; set; }
        public string Spec124 { get; set; }
        public string Spec125 { get; set; }
        public string Spec297 { get; set; }
        public string Spec298 { get; set; }
        public string Spec299 { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Buyer { get; set; }
        public string Loc_UserGrp { get; set; }
        public string Pic_FileName { get; set; }
        public string Pic_Key { get; set; }
        public string Spec900 { get; set; }
        public string Spec901 { get; set; }
        public string Spec902 { get; set; }
        public string Spec903 { get; set; }
        public string Spec904 { get; set; }
        public string Spec905 { get; set; }
        public string Spec906 { get; set; }
        public string Spec907 { get; set; }
        public string Spec908 { get; set; }
        public string Spec909 { get; set; }
        public string Spec910 { get; set; }
        public string Mrp_User { get; set; }
        public string Margin_Code { get; set; }
        public string Mps_User { get; set; }
        public bool export_flag { get; set; }
        public bool export_flag1 { get; set; }
    }
}
