//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1074
    {
        public string Item_No { get; set; }
        public string Vdr_Code { get; set; }
        public int Grade { get; set; }
        public int Status_Code { get; set; }
        public string V_Item_No { get; set; }
        public string V_Item_Desc { get; set; }
        public string V_Uom { get; set; }
        public decimal UomRate { get; set; }
        public decimal Unit_Price { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public Nullable<decimal> Unit_Price2 { get; set; }
        public Nullable<decimal> Unit_Price3 { get; set; }
        public string Con_User { get; set; }
        public decimal unit_price_bef { get; set; }
        public decimal unit_price_delay { get; set; }
        public string Last_User { get; set; }
        public System.DateTime Last_Date { get; set; }
        public bool appr_flag { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public Nullable<decimal> Unit_Price4 { get; set; }
        public decimal unit_price5 { get; set; }
        public bool pured_flag { get; set; }
        public string ref_no { get; set; }
    }
}
