//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1086
    {
        public int plan_source { get; set; }
        public string job_no { get; set; }
        public int seq_no { get; set; }
        public string pitem_no { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public Nullable<decimal> qty_f { get; set; }
        public Nullable<decimal> qty_planed { get; set; }
        public Nullable<System.DateTime> qty_planed_date { get; set; }
        public Nullable<decimal> qty_pr { get; set; }
        public int ma_type { get; set; }
        public Nullable<int> mb_type { get; set; }
        public Nullable<System.DateTime> issuetime { get; set; }
        public decimal leadtime { get; set; }
        public System.DateTime purctime { get; set; }
        public string source { get; set; }
        public string item_bgrp { get; set; }
        public string item_grp { get; set; }
        public int status_code { get; set; }
        public string bom_ver { get; set; }
        public string bol_ver { get; set; }
        public Nullable<decimal> qty_per { get; set; }
        public Nullable<decimal> qty_nochange { get; set; }
        public Nullable<decimal> qty_yield { get; set; }
        public Nullable<decimal> qty_order { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public string ppitem_no { get; set; }
        public Nullable<decimal> pqty_per { get; set; }
        public string pjob_no { get; set; }
        public string hpr_no { get; set; }
        public bool useall_flag { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Line_Code { get; set; }
        public string Line_Class { get; set; }
    }
}
