//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1087
    {
        public string pr_no { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal qty_pass { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public decimal qty_unappr { get; set; }
        public System.DateTime issuetime { get; set; }
        public decimal leadtime { get; set; }
        public System.DateTime ordertime { get; set; }
        public int plan_source { get; set; }
        public string po_no { get; set; }
        public Nullable<int> seq_no { get; set; }
        public bool useall_flag { get; set; }
        public bool moqpr_flag { get; set; }
        public string rela_file_no { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> mrp_qty { get; set; }
        public string source { get; set; }
        public string sysremark { get; set; }
        public string Pr_Type { get; set; }
        public bool Sms_Flag { get; set; }
        public bool Pmc_SMS_Flag { get; set; }
        public bool approve { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public int status_code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Vdr_Code { get; set; }
        public bool TraceOrder_Flag { get; set; }
        public decimal Qty_Per { get; set; }
        public string Job_No { get; set; }
        public string Cust_Code { get; set; }
        public string OurModel { get; set; }
        public string Cust_Po { get; set; }
        public string YourModel { get; set; }
        public string So_No { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
        public bool approve1 { get; set; }
    }
}
