//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1085
    {
        public Nullable<int> Plan_Source { get; set; }
        public string Job_No { get; set; }
        public Nullable<int> Seq_No { get; set; }
        public string PItem_No { get; set; }
        public string Item_No { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Qty_F { get; set; }
        public Nullable<decimal> Qty_Planed { get; set; }
        public Nullable<System.DateTime> Qty_Planed_Date { get; set; }
        public Nullable<decimal> Qty_Pr { get; set; }
        public Nullable<int> Ma_Type { get; set; }
        public Nullable<int> Mb_Type { get; set; }
        public Nullable<System.DateTime> IssueTime { get; set; }
        public Nullable<decimal> LeadTime { get; set; }
        public Nullable<System.DateTime> PurcTime { get; set; }
        public string Source { get; set; }
        public string Item_Bgrp { get; set; }
        public string Item_Grp { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public string Bom_Ver { get; set; }
        public string Bol_Ver { get; set; }
        public Nullable<decimal> Qty_Per { get; set; }
        public Nullable<decimal> Qty_NoChange { get; set; }
        public Nullable<decimal> Qty_Yield { get; set; }
        public Nullable<decimal> Qty_Order { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Qty_Bal { get; set; }
        public string PPItem_No { get; set; }
        public Nullable<decimal> PQty_Per { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
