//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1091
    {
        public string File_No { get; set; }
        public string Ord_Id { get; set; }
        public string Job_No { get; set; }
        public decimal Seq_No { get; set; }
        public string MJob_No { get; set; }
        public string Line_Class { get; set; }
        public string ToLoc_Code { get; set; }
        public string Vh_No { get; set; }
        public bool Issue_Flag { get; set; }
        public string Ref_No { get; set; }
        public int Type_Flag { get; set; }
        public int MaxIssueTime { get; set; }
        public string Trace_Flag { get; set; }
        public string Cust_Code { get; set; }
        public string RefCust_Code { get; set; }
        public string OurModel { get; set; }
        public string Cust_Po { get; set; }
        public int FO_Qty { get; set; }
        public int FO_Use { get; set; }
        public int Fo_Qty_F { get; set; }
        public int Fo_Qty_Org { get; set; }
        public string So_No { get; set; }
        public bool approve { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysRemark { get; set; }
        public string Remark { get; set; }
    }
}
