//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1092
    {
        public int Plan_Source { get; set; }
        public string Job_No { get; set; }
        public Nullable<int> Seq_No { get; set; }
        public string PItem_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_F { get; set; }
        public decimal Qty_Crap { get; set; }
        public decimal Qty_R { get; set; }
        public Nullable<decimal> Qty_Planed { get; set; }
        public Nullable<System.DateTime> Qty_Planed_Date { get; set; }
        public Nullable<decimal> Qty_Pr { get; set; }
        public int Ma_Type { get; set; }
        public int Mb_Type { get; set; }
        public int Mc_Type { get; set; }
        public int Md_Type { get; set; }
        public int Me_Type { get; set; }
        public System.DateTime IssueTime { get; set; }
        public Nullable<System.DateTime> Last_IssueTime { get; set; }
        public Nullable<decimal> LeadTime { get; set; }
        public Nullable<System.DateTime> Purctime { get; set; }
        public string Source { get; set; }
        public string Item_Bgrp { get; set; }
        public string Item_Grp { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public string Status_User { get; set; }
        public string Bom_Ver { get; set; }
        public string Bol_Ver { get; set; }
        public Nullable<decimal> Qty_Per { get; set; }
        public Nullable<decimal> Qty_NoChange { get; set; }
        public Nullable<decimal> Qty_Yield { get; set; }
        public Nullable<decimal> Qty_Order { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Qty_Bal { get; set; }
        public string PPItem_No { get; set; }
        public Nullable<decimal> PQty_Per { get; set; }
        public bool UseAll_Flag { get; set; }
        public string SysRemark { get; set; }
        public int IssueTimes { get; set; }
        public string Line_Code { get; set; }
        public string Line_Class { get; set; }
        public string So_No { get; set; }
        public Nullable<decimal> So_Seq { get; set; }
        public Nullable<bool> Toexcel { get; set; }
        public string Pmc_Remark { get; set; }
        public Nullable<System.DateTime> Mrp_Date { get; set; }
        public string Ord_Id { get; set; }
        public string Trace_Flag { get; set; }
        public string Cust_Code { get; set; }
        public string OurModel { get; set; }
        public bool Mforecast_Flag { get; set; }
        public string Cust_Po { get; set; }
        public string YourModel { get; set; }
        public Nullable<System.DateTime> So_Ftd { get; set; }
        public int FO_Qty { get; set; }
        public bool DircPr_Flag { get; set; }
        public string Precedence { get; set; }
        public Nullable<System.DateTime> LastOut_Date { get; set; }
        public string Pmc_Remark1 { get; set; }
        public decimal Qty_Hold { get; set; }
        public decimal Qty_Hold_UnAppr { get; set; }
        public decimal Qty_HoldA { get; set; }
        public decimal Qty_Hold_UnApprA { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Cn_No { get; set; }
        public decimal Qty_Part { get; set; }
        public bool Yield_Flag { get; set; }
        public bool TraceOrder_Flag { get; set; }
        public bool JobPart_Flag { get; set; }
        public int MF_Flag { get; set; }
        public decimal Qty_Yield1 { get; set; }
        public double Qty_Proof1 { get; set; }
        public string Work_GrpB { get; set; }
        public string M81 { get; set; }
        public string M81_User { get; set; }
        public Nullable<System.DateTime> M81_Date { get; set; }
        public string Plan_Remark { get; set; }
        public Nullable<decimal> Qty_Po { get; set; }
        public int Mps_Seq { get; set; }
        public Nullable<bool> ToIssue_Flag { get; set; }
        public string ToIssue_User { get; set; }
        public Nullable<System.DateTime> ToIssue_Date { get; set; }
        public Nullable<decimal> qty_g_infgs { get; set; }
        public Nullable<decimal> qty_g_outfgs { get; set; }
        public string item_desc { get; set; }
        public string uom { get; set; }
        public string item_type { get; set; }
        public decimal Qty_ToOV { get; set; }
        public string A02 { get; set; }
        public string A02Org_Code { get; set; }
        public decimal Qty_Hand { get; set; }
        public decimal unit_price { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
        public bool Pur_Flag { get; set; }
    }
}
