//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1096
    {
        public string So_No { get; set; }
        public Nullable<decimal> seq_no { get; set; }
        public bool lot_yes { get; set; }
        public bool mat_flag { get; set; }
        public int pos { get; set; }
        public bool ptp { get; set; }
        public decimal rela_seq { get; set; }
        public string tjob_no { get; set; }
        public string Info_Type { get; set; }
        public string job_no { get; set; }
        public string work_type { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal qty_so { get; set; }
        public decimal qty_sd { get; set; }
        public decimal qty_must { get; set; }
        public decimal qty_lot { get; set; }
        public decimal qty_pass { get; set; }
        public decimal qty_loss { get; set; }
        public decimal qty_return { get; set; }
        public decimal qty_bal { get; set; }
        public decimal qty_issue { get; set; }
        public decimal qty_my { get; set; }
        public decimal qty_you { get; set; }
        public decimal qty_raw { get; set; }
        public decimal qty_iqc { get; set; }
        public decimal qty_rej_g { get; set; }
        public Nullable<decimal> qty_prodbal { get; set; }
        public Nullable<System.DateTime> ftd_so { get; set; }
        public Nullable<System.DateTime> pst_date { get; set; }
        public Nullable<System.DateTime> pfh_date { get; set; }
        public Nullable<System.DateTime> rst_date { get; set; }
        public Nullable<System.DateTime> rfh_date { get; set; }
        public Nullable<System.DateTime> ast_date { get; set; }
        public Nullable<System.DateTime> afh_date { get; set; }
        public string remark { get; set; }
        public int status_code { get; set; }
        public string item_bgrp { get; set; }
        public bool mat_plan { get; set; }
        public int maxisstimes { get; set; }
        public string Route_Code { get; set; }
        public string Route_Ver { get; set; }
        public string Bom_Ver { get; set; }
        public bool Job_Raw { get; set; }
        public decimal toqty_bal { get; set; }
        public int job_source { get; set; }
        public bool iqc { get; set; }
        public bool useall_flag { get; set; }
        public string ourmodel { get; set; }
        public string cust_code { get; set; }
        public string issue_no { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public string planer { get; set; }
        public string checker { get; set; }
        public Nullable<System.DateTime> mrp_date { get; set; }
        public string sysremark { get; set; }
        public string Ord_Id { get; set; }
        public Nullable<System.DateTime> ctd { get; set; }
        public Nullable<System.DateTime> ctd2 { get; set; }
        public bool ToProj_Flag { get; set; }
        public Nullable<System.DateTime> PPSt_Date { get; set; }
        public Nullable<System.DateTime> PPFh_Date { get; set; }
        public string PUser { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<System.DateTime> APSt_Date { get; set; }
        public Nullable<System.DateTime> APFh_Date { get; set; }
        public string AUser { get; set; }
        public Nullable<System.DateTime> ADate { get; set; }
        public int R_MaxTimes { get; set; }
        public string Line_Class { get; set; }
        public string Line_Code { get; set; }
        public bool approve { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool New_Flag { get; set; }
        public bool TraceOrder_Flag { get; set; }
        public int MF_Flag { get; set; }
        public string Batch_No { get; set; }
        public string wip_code { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
    }
}
