//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1108
    {
        public string lot_no { get; set; }
        public string job_no { get; set; }
        public string Ord_ID { get; set; }
        public Nullable<System.DateTime> st_date { get; set; }
        public Nullable<System.DateTime> fh_date { get; set; }
        public decimal qty { get; set; }
        public decimal qty_job { get; set; }
        public decimal qty_pass { get; set; }
        public decimal qty_loss { get; set; }
        public int status_code { get; set; }
        public bool divi_yes { get; set; }
        public string plot_no { get; set; }
        public string lot_type { get; set; }
        public string lot_type1 { get; set; }
        public string remark { get; set; }
        public string SysRemark { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
    }
}
