//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1106
    {
        public long autoid { get; set; }
        public string mycompute { get; set; }
        public string mytable { get; set; }
        public string myaction { get; set; }
        public string upt_desc1 { get; set; }
        public string upt_desc2 { get; set; }
        public string log_desc { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
