//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1109
    {
        public string lot_no { get; set; }
        public string Job_No { get; set; }
        public string Line_Code { get; set; }
        public string Nline_code { get; set; }
        public string Xline_code { get; set; }
        public int seq_no { get; set; }
        public decimal Line_Seq_No { get; set; }
        public decimal qty { get; set; }
        public decimal qty_pass { get; set; }
        public decimal qty_loss { get; set; }
        public string bol_grp { get; set; }
        public int status_code { get; set; }
        public Nullable<bool> job_lastseqno { get; set; }
        public bool divi_yes { get; set; }
        public string loc_code { get; set; }
        public string pass_user { get; set; }
        public Nullable<System.DateTime> pass_date { get; set; }
        public int transfer { get; set; }
        public Nullable<System.DateTime> In_date { get; set; }
        public string po_no { get; set; }
        public int pseq_no { get; set; }
        public bool R_Flag { get; set; }
        public string vh_no { get; set; }
        public bool Pack_Flag { get; set; }
        public string Remark { get; set; }
        public bool Bal_Flag { get; set; }
        public decimal Qty_Lot { get; set; }
        public Nullable<decimal> Qty_Bal { get; set; }
        public bool MLLine_Flag { get; set; }
        public bool MNLine_Flag { get; set; }
        public int TLead_Time { get; set; }
        public int Lead_Time { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal Qty_Split { get; set; }
        public Nullable<decimal> Qty_ToLoc { get; set; }
        public string ToLoc_Code { get; set; }
        public string Emp_Code { get; set; }
        public bool ToAcc_Flag { get; set; }
        public string Rec_No { get; set; }
        public string Lot_No_Split { get; set; }
        public decimal Qty_Split2 { get; set; }
        public string Lot_No_Split2 { get; set; }
        public decimal Qty_Split3 { get; set; }
        public string Lot_No_Split3 { get; set; }
        public string Pass_User2 { get; set; }
        public Nullable<System.DateTime> Pass_Date2 { get; set; }
        public string Frm_User2 { get; set; }
        public bool Merge_Flag { get; set; }
    }
}
