//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1107
    {
        public string Lot_No { get; set; }
        public string Ord_Id { get; set; }
        public string Plot_No { get; set; }
        public string Remark { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
        public bool Print_Flag { get; set; }
        public string ReUse_No { get; set; }
        public string A02 { get; set; }
        public string A02Org_Code { get; set; }
        public bool E055Upt_Flag { get; set; }
        public int PLot_Seq_No { get; set; }
        public string frmfile_no { get; set; }
        public Nullable<int> frmfile_seq_no { get; set; }
        public int PRINTTIMES { get; set; }
    }
}
