//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1103
    {
        public string Loc_Code { get; set; }
        public string Loc_Descc { get; set; }
        public string Loc_Desce { get; set; }
        public string Area_Code { get; set; }
        public string Loc_Add1 { get; set; }
        public string Loc_Add2 { get; set; }
        public string Loc_Add3 { get; set; }
        public string Loc_Add4 { get; set; }
        public string Loc_Type01 { get; set; }
        public string Loc_Type02 { get; set; }
        public string Loc_Type03 { get; set; }
        public string Loc_Type04 { get; set; }
        public string Loc_Type05 { get; set; }
        public int Use_Seq_No { get; set; }
        public string PLoc_Code { get; set; }
        public bool AisMrp { get; set; }
        public bool MainMrp { get; set; }
        public string Remark { get; set; }
        public string Rpt_Code { get; set; }
        public string Rpt_Desc { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool export_flag { get; set; }
        public bool export_flag1 { get; set; }
    }
}
