//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1101
    {
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
        public string so_no { get; set; }
        public decimal seq_no { get; set; }
        public string loc_code { get; set; }
        public string rpt_id { get; set; }
        public decimal SSeq_No { get; set; }
        public decimal qty { get; set; }
        public bool mYes { get; set; }
        public bool mNo { get; set; }
        public decimal qty_yes { get; set; }
        public string appr_user { get; set; }
        public string remark { get; set; }
        public bool status_code { get; set; }
        public string sysremark { get; set; }
        public Nullable<System.DateTime> mytime { get; set; }
        public bool plan_flag { get; set; }
        public Nullable<System.DateTime> freeze_date { get; set; }
    }
}
