//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1113
    {
        public string SO_NO { get; set; }
        public Nullable<System.DateTime> Sample_PFH_Date { get; set; }
        public Nullable<System.DateTime> Sample_AFH_Date { get; set; }
        public string Model_ST_Date { get; set; }
        public string Model_FH_Date { get; set; }
        public Nullable<System.DateTime> Cad_PFH_Date { get; set; }
        public Nullable<System.DateTime> Cad_AFH_Date { get; set; }
        public Nullable<System.DateTime> Bom_AFH_Date { get; set; }
        public string Eng_Remark { get; set; }
        public string Item_No1 { get; set; }
        public Nullable<System.DateTime> Item_No1_St_Date { get; set; }
        public Nullable<System.DateTime> Item_No1_PFH_Date { get; set; }
        public Nullable<System.DateTime> Item_No1_AFH_Date { get; set; }
        public string Item_No2 { get; set; }
        public Nullable<System.DateTime> Item_No2_St_Date { get; set; }
        public Nullable<System.DateTime> Item_No2_PFH_Date { get; set; }
        public Nullable<System.DateTime> Item_No2_AFH_Date { get; set; }
        public string Item_No3 { get; set; }
        public Nullable<System.DateTime> Item_No3_St_Date { get; set; }
        public Nullable<System.DateTime> Item_No3_PFH_Date { get; set; }
        public Nullable<System.DateTime> Item_No3_AFH_Date { get; set; }
        public string Item_No4 { get; set; }
        public Nullable<System.DateTime> Item_No4_St_Date { get; set; }
        public Nullable<System.DateTime> Item_No4_PFH_Date { get; set; }
        public Nullable<System.DateTime> Item_No4_AFH_Date { get; set; }
        public string Item_No5 { get; set; }
        public Nullable<System.DateTime> Item_No5_St_Date { get; set; }
        public Nullable<System.DateTime> Item_No5_PFH_Date { get; set; }
        public Nullable<System.DateTime> Item_No5_AFH_Date { get; set; }
        public string Item_No6 { get; set; }
        public Nullable<System.DateTime> Item_No6_St_Date { get; set; }
        public Nullable<System.DateTime> Item_No6_PFH_Date { get; set; }
        public Nullable<System.DateTime> Item_No6_AFH_Date { get; set; }
        public string Item_Remark { get; set; }
        public Nullable<System.DateTime> Pmc_RawSt_Date { get; set; }
        public string Pmc_Remark { get; set; }
    }
}
