//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1111
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string mo_no { get; set; }
        public string Mk_Id { get; set; }
        public string Item_No { get; set; }
        public string SoOurModel { get; set; }
        public string Info_Type { get; set; }
        public decimal Rela_Seq { get; set; }
        public string Rela_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_f { get; set; }
        public decimal Qty_So { get; set; }
        public decimal Qty_Sd { get; set; }
        public Nullable<System.DateTime> Know_Date { get; set; }
        public decimal Know_Qty { get; set; }
        public decimal Know_Qty_Sd { get; set; }
        public Nullable<System.DateTime> Ftd_So { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc_Fst { get; set; }
        public Nullable<System.DateTime> Ftd { get; set; }
        public string pmc_ftd_user { get; set; }
        public Nullable<System.DateTime> pmc_ftd_date { get; set; }
        public int Urgent_Flag { get; set; }
        public string Cust_Po { get; set; }
        public string UCust_Po { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public int Status_Code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> status_Date { get; set; }
        public bool Part_Type { get; set; }
        public bool New_Y { get; set; }
        public System.DateTime Last_Date { get; set; }
        public string Pt_No { get; set; }
        public bool Job_Yes { get; set; }
        public Nullable<System.DateTime> Job_yes_date { get; set; }
        public bool LoT_Flag { get; set; }
        public bool Issue_Flag { get; set; }
        public bool PlanB_Flag { get; set; }
        public string PlanB_User { get; set; }
        public Nullable<System.DateTime> PlanB_Date { get; set; }
        public Nullable<bool> PlanB_MYes { get; set; }
        public Nullable<System.DateTime> PlanB_MDate { get; set; }
        public string PlanB_MUser { get; set; }
        public bool ToProd_flag { get; set; }
        public string Issue_no { get; set; }
        public string ToProd_User { get; set; }
        public Nullable<System.DateTime> ToProd_Date { get; set; }
        public bool ToProd_flag1 { get; set; }
        public string ToProd_User1 { get; set; }
        public Nullable<System.DateTime> ToProd_Date1 { get; set; }
        public bool ToProd_flag2 { get; set; }
        public string ToProd_User2 { get; set; }
        public Nullable<System.DateTime> ToProd_Date2 { get; set; }
        public decimal raw_issue_today { get; set; }
        public decimal raw_issue_set { get; set; }
        public Nullable<System.DateTime> raw_issue_date { get; set; }
        public decimal raw_ready_set { get; set; }
        public bool Mps_Flag { get; set; }
        public string Mps_User { get; set; }
        public Nullable<System.DateTime> Mps_Date { get; set; }
        public bool Mps_Flag1 { get; set; }
        public string Mps_User1 { get; set; }
        public Nullable<System.DateTime> Mps_Date1 { get; set; }
        public bool Mps_Flag2 { get; set; }
        public string Mps_User2 { get; set; }
        public Nullable<System.DateTime> Mps_Date2 { get; set; }
        public string Ord_Id { get; set; }
        public string Cust_Code { get; set; }
        public string CSo_no { get; set; }
        public string OurModel { get; set; }
        public string WoRemark { get; set; }
        public string Pmc_Remark { get; set; }
        public string Trace_Flag { get; set; }
        public decimal Qty_Use { get; set; }
        public Nullable<decimal> Qty_Use_Bal { get; set; }
        public string cust_cll { get; set; }
        public string cust_model { get; set; }
        public string SysRemark { get; set; }
        public string yourcolor { get; set; }
        public string ourcolor { get; set; }
        public string tt_lens { get; set; }
        public string yoursize { get; set; }
        public bool Print_Flag { get; set; }
        public Nullable<System.DateTime> Print_Date { get; set; }
        public string Print_User { get; set; }
        public Nullable<System.DateTime> Mcn_Date { get; set; }
        public Nullable<System.DateTime> Bol_Date { get; set; }
        public bool Prior_Mat_Flag { get; set; }
        public Nullable<System.DateTime> Prior_Mat_Date { get; set; }
        public string Prior_Mat_User { get; set; }
        public bool After_Mat_Flag { get; set; }
        public Nullable<System.DateTime> After_Mat_Date { get; set; }
        public string After_Mat_User { get; set; }
        public bool IsDetail { get; set; }
        public string NewItem_No { get; set; }
        public bool MpsErr_Flag { get; set; }
        public string MpsRemark { get; set; }
        public bool MpsOk_Flag { get; set; }
        public string MpsOk_User { get; set; }
        public Nullable<System.DateTime> MpsOk_Date { get; set; }
        public bool MpsOk_Flag1 { get; set; }
        public string MpsOk_User1 { get; set; }
        public Nullable<System.DateTime> MpsOk_Date1 { get; set; }
        public bool MpsOk_Flag2 { get; set; }
        public string MpsOk_User2 { get; set; }
        public Nullable<System.DateTime> MpsOk_Date2 { get; set; }
        public Nullable<System.DateTime> Pst_Date { get; set; }
        public Nullable<System.DateTime> Pfh_Date { get; set; }
        public string Sp_No { get; set; }
        public string Qc_No { get; set; }
        public decimal Qty_C { get; set; }
        public int MaxCNo { get; set; }
        public Nullable<int> job_raw_grp { get; set; }
        public Nullable<decimal> qty_raw_per { get; set; }
        public bool LotMdl_Flag { get; set; }
        public decimal Qty_Distr { get; set; }
        public decimal Qty_beDistr { get; set; }
        public bool Free_Flag { get; set; }
        public Nullable<decimal> after_issue_set { get; set; }
        public Nullable<System.DateTime> after_issue_time { get; set; }
        public bool Flag3 { get; set; }
        public Nullable<System.DateTime> ftd_pmc2 { get; set; }
        public Nullable<System.DateTime> ftd_pmc3 { get; set; }
        public Nullable<System.DateTime> ftd_pmc4 { get; set; }
        public Nullable<System.DateTime> ftd_pmc5 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SpRemark { get; set; }
        public string Pd_Remark { get; set; }
        public string Pd_Remark_Raw { get; set; }
        public bool Yield_Flag { get; set; }
        public string Issue_Grp { get; set; }
        public bool Pur_Flag { get; set; }
        public string Vdr_Code { get; set; }
        public decimal Qty_Pur { get; set; }
        public string M305 { get; set; }
        public string PackRemark { get; set; }
        public Nullable<int> Color_Num { get; set; }
        public Nullable<int> Lead_Time { get; set; }
        public string M368 { get; set; }
        public string SoMps_User { get; set; }
        public bool Mps_Flag3 { get; set; }
        public string Mps_User3 { get; set; }
        public Nullable<System.DateTime> Mps_Date3 { get; set; }
        public bool MpsOk_Flag3 { get; set; }
        public string MpsOk_User3 { get; set; }
        public Nullable<System.DateTime> MpsOk_Date3 { get; set; }
        public Nullable<System.DateTime> Rst_Date { get; set; }
        public Nullable<System.DateTime> Rfh_Date { get; set; }
        public Nullable<int> MOVE_DAYS { get; set; }
        public string wo_no { get; set; }
        public string M376 { get; set; }
        public string line_rule { get; set; }
        public bool AutoWF_Flag { get; set; }
        public Nullable<decimal> Qty_Wip { get; set; }
        public decimal qty_sample { get; set; }
        public string loc_code { get; set; }
        public Nullable<decimal> qty_f_unappr { get; set; }
        public Nullable<decimal> wo_seq_no { get; set; }
        public string vh_no { get; set; }
        public decimal QTY_PMC { get; set; }
        public bool export_flag { get; set; }
        public string frmso_no { get; set; }
        public Nullable<decimal> frmso_seq_no { get; set; }
    }
}
