//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1110
    {
        public decimal MyId { get; set; }
        public string Loss_Type { get; set; }
        public string Lot_No { get; set; }
        public int Seq_No { get; set; }
        public string Line_Code { get; set; }
        public string Loss_Code { get; set; }
        public decimal Qty_Loss { get; set; }
        public decimal Qty_F { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Loss_Code1 { get; set; }
    }
}
