//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1112
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string mo_no { get; set; }
        public Nullable<System.DateTime> Bom_Date { get; set; }
        public bool C_Flag { get; set; }
        public Nullable<bool> paint_flag { get; set; }
        public Nullable<bool> plate_flag { get; set; }
        public Nullable<System.DateTime> Pmat_InDate { get; set; }
        public string C_Loc_Code { get; set; }
        public Nullable<System.DateTime> Birth_Paper_Date { get; set; }
        public Nullable<System.DateTime> Sample_PFH_Date { get; set; }
        public Nullable<System.DateTime> Sample_AFH_Date { get; set; }
        public string Model_ST_Date { get; set; }
        public string Model_FH_Date { get; set; }
        public Nullable<System.DateTime> PT_St_Date { get; set; }
        public Nullable<System.DateTime> PT_Fh_Date { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc1 { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc2 { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc3 { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc4 { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc5 { get; set; }
        public bool Prior_Flag { get; set; }
        public bool After_Flag { get; set; }
        public bool Mat_Lack_Flag { get; set; }
        public bool Prd_Lack_Flag { get; set; }
        public string Mo_Remark { get; set; }
        public Nullable<System.DateTime> Cycle_Ok_Date { get; set; }
        public Nullable<System.DateTime> Raw_Mat_Date { get; set; }
        public Nullable<System.DateTime> Pst_Date { get; set; }
        public Nullable<System.DateTime> Ast_Date { get; set; }
        public Nullable<System.DateTime> Raw_Fh_Date { get; set; }
        public int Raw_Fh_Qty { get; set; }
        public int Raw_Std_Time { get; set; }
        public string Raw_Remark { get; set; }
        public string Plt_Loc_Code { get; set; }
        public Nullable<System.DateTime> Plt_O_Date1 { get; set; }
        public int Plt_O_Qty1 { get; set; }
        public Nullable<System.DateTime> Plt_O_Date2 { get; set; }
        public int Plt_O_Qty2 { get; set; }
        public int Plt_O_Act_Time { get; set; }
        public int Plt_O_TQty { get; set; }
        public int Plt_O_LQty { get; set; }
        public bool Plt_Ok_Flag { get; set; }
        public string Plt_O_Remark { get; set; }
        public Nullable<System.DateTime> Plt_I_Date1 { get; set; }
        public int Plt_I_Qty1 { get; set; }
        public Nullable<System.DateTime> Plt_I_Date2 { get; set; }
        public int Plt_I_Qty2 { get; set; }
        public Nullable<int> Plt_I_ADays { get; set; }
        public int Plt_I_TQty { get; set; }
        public int Plt_I_LQty { get; set; }
        public bool Plt_I_OkFlag { get; set; }
        public string Plt_I_Remark { get; set; }
        public string Pat_Loc_Code { get; set; }
        public Nullable<System.DateTime> Pat_O_Date1 { get; set; }
        public int Pat_O_Qty1 { get; set; }
        public Nullable<System.DateTime> Pat_O_Date2 { get; set; }
        public int Pat_O_Qty2 { get; set; }
        public int Pat_O_ATime { get; set; }
        public int Pat_O_TQty { get; set; }
        public int Pat_O_LQty { get; set; }
        public int Pat_Bal { get; set; }
        public bool Pat_O_OkFlag { get; set; }
        public string Pat_O_Remark { get; set; }
        public string Pkt_Loc_Code { get; set; }
        public string Pkt_POrd_Date { get; set; }
        public string Pkt_Fc_Date { get; set; }
        public string Pkt_Bc_Date { get; set; }
        public bool Pkt_Cust_Flag { get; set; }
        public string Pkt_Cust_Date { get; set; }
        public Nullable<System.DateTime> Pkt_O_Date1 { get; set; }
        public int Pkt_O_Qty1 { get; set; }
        public Nullable<System.DateTime> Pkt_O_Date2 { get; set; }
        public int Pkt_O_Qty2 { get; set; }
        public int Pkt_O_ATime { get; set; }
        public int Pkt_O_TQty { get; set; }
        public int Pkt_O_LQty { get; set; }
        public int Pkt_Bal { get; set; }
        public bool Pkt_O_OkFlag { get; set; }
        public string Pkt_O_Remark { get; set; }
        public decimal raw_qty_bal { get; set; }
        public int Fgs_Qty_st { get; set; }
        public int Fgs_Qty_hk { get; set; }
        public Nullable<int> Fgs_Qty { get; set; }
        public Nullable<System.DateTime> Tohk_Date { get; set; }
        public Nullable<System.DateTime> ToSt_Date { get; set; }
        public string Late_Code { get; set; }
        public bool status_code { get; set; }
        public string Item_grp { get; set; }
        public bool Whs_Mat_Flag { get; set; }
        public Nullable<System.DateTime> Whs_Mat_Date { get; set; }
        public string Whs_Mat_User { get; set; }
        public bool Prd_Mat_Flag { get; set; }
        public Nullable<System.DateTime> Prd_Mat_Date { get; set; }
        public string Prd_Mat_User { get; set; }
        public string Prd_Mat_Remark { get; set; }
        public bool Cpu_Mat_Flag { get; set; }
        public Nullable<System.DateTime> Cpu_Mat_Date { get; set; }
        public string sysremark { get; set; }
        public Nullable<System.DateTime> Cal_date { get; set; }
        public Nullable<System.DateTime> Act_Issue_Date { get; set; }
        public Nullable<System.DateTime> Act_Issue_Date_AC { get; set; }
        public Nullable<System.DateTime> AfterIssue_FH_Date { get; set; }
        public Nullable<System.DateTime> Fst_Fgs_Date { get; set; }
        public decimal Fst_Fgs_Qty { get; set; }
        public string Line_Code { get; set; }
        public Nullable<bool> GT_Flag { get; set; }
        public string Gt_Code { get; set; }
        public Nullable<System.DateTime> Gt_I_Date1 { get; set; }
        public Nullable<int> Gt_I_Qty1 { get; set; }
        public Nullable<System.DateTime> Gt_I_Date2 { get; set; }
        public Nullable<int> Gt_I_Qty2 { get; set; }
        public Nullable<int> Gt_I_TQty { get; set; }
        public Nullable<System.DateTime> Gt_O_Date1 { get; set; }
        public Nullable<int> Gt_O_Qty1 { get; set; }
        public Nullable<System.DateTime> Gt_O_Date2 { get; set; }
        public Nullable<int> Gt_O_Qty2 { get; set; }
        public Nullable<int> Gt_O_Tqty { get; set; }
        public string DJ_Loc_Code { get; set; }
        public Nullable<System.DateTime> DJ_O_Date1 { get; set; }
        public Nullable<int> DJ_O_Qty1 { get; set; }
        public Nullable<System.DateTime> DJ_O_Date2 { get; set; }
        public Nullable<int> DJ_O_Qty2 { get; set; }
        public Nullable<int> DJ_O_Act_Time { get; set; }
        public Nullable<int> DJ_O_TQty { get; set; }
        public Nullable<int> DJ_O_LQty { get; set; }
        public Nullable<bool> DJ_Ok_Flag { get; set; }
        public string DJ_O_Remark { get; set; }
        public Nullable<System.DateTime> DJ_I_Date1 { get; set; }
        public Nullable<int> DJ_I_Qty1 { get; set; }
        public Nullable<System.DateTime> DJ_I_Date2 { get; set; }
        public Nullable<int> DJ_I_Qty2 { get; set; }
        public Nullable<int> DJ_I_ADays { get; set; }
        public Nullable<int> DJ_I_TQty { get; set; }
        public Nullable<int> DJ_I_LQty { get; set; }
        public Nullable<bool> DJ_I_OkFlag { get; set; }
        public string DJ_I_Remark { get; set; }
        public string NotMat_Desc { get; set; }
        public string NotMat_Desc1 { get; set; }
        public string NotMat_Desc2 { get; set; }
        public string AllMat_Desc { get; set; }
        public string PassMat_Desc { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDATE { get; set; }
        public string Ver_No { get; set; }
        public string Ver_No2 { get; set; }
        public Nullable<bool> GBom_Flag { get; set; }
        public string GBom_PG_No { get; set; }
    }
}
