//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1118
    {
        public int Acc_year { get; set; }
        public int Acc_month { get; set; }
        public bool Mat_Flag { get; set; }
        public bool WIP_Flag { get; set; }
        public bool Fgs_Flag { get; set; }
        public bool Acc_Flag { get; set; }
        public bool Flag1 { get; set; }
        public bool Cal_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool Q001_Flag { get; set; }
    }
}
