//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1121
    {
        public int acc_year { get; set; }
        public int acc_month { get; set; }
        public string emp_code { get; set; }
        public string c_name { get; set; }
        public string org_code { get; set; }
        public Nullable<decimal> D01 { get; set; }
        public Nullable<decimal> D02 { get; set; }
        public Nullable<decimal> D03 { get; set; }
        public Nullable<decimal> D04 { get; set; }
        public Nullable<decimal> D05 { get; set; }
        public Nullable<decimal> D06 { get; set; }
        public Nullable<decimal> D07 { get; set; }
        public Nullable<decimal> D08 { get; set; }
        public Nullable<decimal> D09 { get; set; }
        public Nullable<decimal> D10 { get; set; }
        public Nullable<decimal> D11 { get; set; }
        public Nullable<decimal> D12 { get; set; }
        public Nullable<decimal> D13 { get; set; }
        public Nullable<decimal> D14 { get; set; }
        public Nullable<decimal> D15 { get; set; }
        public Nullable<decimal> D16 { get; set; }
        public Nullable<decimal> D17 { get; set; }
        public Nullable<decimal> D18 { get; set; }
        public Nullable<decimal> D19 { get; set; }
        public Nullable<decimal> D20 { get; set; }
        public Nullable<decimal> D21 { get; set; }
        public Nullable<decimal> D22 { get; set; }
        public Nullable<decimal> D23 { get; set; }
        public Nullable<decimal> D24 { get; set; }
        public Nullable<decimal> D25 { get; set; }
        public Nullable<decimal> D26 { get; set; }
        public Nullable<decimal> D27 { get; set; }
        public Nullable<decimal> D28 { get; set; }
        public Nullable<decimal> D29 { get; set; }
        public Nullable<decimal> D30 { get; set; }
        public Nullable<decimal> D31 { get; set; }
        public Nullable<decimal> avg_eff { get; set; }
        public Nullable<decimal> bonus { get; set; }
        public Nullable<bool> quit_flag { get; set; }
        public Nullable<int> leave_days { get; set; }
        public Nullable<int> eff_days { get; set; }
        public Nullable<int> pass_times { get; set; }
        public Nullable<int> unpass_times { get; set; }
        public Nullable<int> custchk_time { get; set; }
        public Nullable<decimal> Eff_Per { get; set; }
    }
}
