//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1129
    {
        public int period { get; set; }
        public int rpt_id { get; set; }
        public string So_No { get; set; }
        public Nullable<System.DateTime> Ftd { get; set; }
        public string Cust_Code { get; set; }
        public string Ourmodel { get; set; }
        public Nullable<decimal> Qty_So { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_f { get; set; }
        public decimal Qty_Bal { get; set; }
        public decimal Qty_Dstr { get; set; }
        public decimal Qty_Wh { get; set; }
        public decimal Qty_Bal_wh { get; set; }
        public decimal Qty_Issue { get; set; }
        public Nullable<System.DateTime> WoDate { get; set; }
        public string Wiploc { get; set; }
        public string BlnEnough { get; set; }
        public string BlnPlan { get; set; }
        public string Line_Class { get; set; }
    }
}
