//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1122
    {
        public string Job_no { get; set; }
        public decimal Seq_no { get; set; }
        public string line_class { get; set; }
        public int line_class_seq { get; set; }
        public string line_code { get; set; }
        public int Line_Seq_No { get; set; }
        public Nullable<System.DateTime> St_date { get; set; }
        public Nullable<System.DateTime> Fn_date { get; set; }
        public Nullable<System.DateTime> ast_date { get; set; }
        public Nullable<System.DateTime> ash_date { get; set; }
        public decimal qty { get; set; }
        public decimal qty_in { get; set; }
        public decimal qty_out { get; set; }
        public decimal Qty_Scrap { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public string pmc_remark { get; set; }
        public bool issue_flag { get; set; }
        public Nullable<int> status_code { get; set; }
        public decimal Lead_Time { get; set; }
        public bool Ctrl_Point { get; set; }
        public decimal TLead_Time { get; set; }
        public bool mline_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Pass_User { get; set; }
        public Nullable<System.DateTime> Pass_Date { get; set; }
        public string Remark { get; set; }
        public bool OV_Flag { get; set; }
        public int Rela_Seq { get; set; }
        public bool Bol_Flag { get; set; }
        public Nullable<System.DateTime> wFh_Date { get; set; }
        public Nullable<System.DateTime> pst_date { get; set; }
        public Nullable<System.DateTime> pfh_date { get; set; }
        public decimal qty_must { get; set; }
        public bool Pwk_Flag { get; set; }
        public string Pwk_User { get; set; }
        public Nullable<System.DateTime> Pwk_Date { get; set; }
        public bool Appr_Flag { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
    }
}
