//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1139
    {
        public string item_no1 { get; set; }
        public int maxlayer { get; set; }
        public int batchlayer { get; set; }
        public int couplelayer { get; set; }
        public int period { get; set; }
        public int rpt_id { get; set; }
        public string item_no { get; set; }
        public string uom { get; set; }
        public string item_descc { get; set; }
        public string Loc_Namec { get; set; }
        public string so_no { get; set; }
        public decimal seq_no { get; set; }
        public string job_no { get; set; }
        public string Cust_Code { get; set; }
        public string ourmodel { get; set; }
        public Nullable<int> qtyso { get; set; }
        public Nullable<System.DateTime> ftd { get; set; }
        public decimal QtyLack { get; set; }
        public decimal QtyJm { get; set; }
        public Nullable<System.DateTime> Issuetime { get; set; }
        public string source { get; set; }
        public Nullable<System.DateTime> DateApprPr { get; set; }
        public Nullable<System.DateTime> DateProvLast { get; set; }
        public string DistrCLast { get; set; }
        public string File_No { get; set; }
        public string WorkType { get; set; }
        public string pPitem { get; set; }
        public Nullable<decimal> ppQtyPer { get; set; }
        public Nullable<decimal> QtyLackpP { get; set; }
        public Nullable<decimal> QtypP { get; set; }
        public Nullable<bool> BlnHead { get; set; }
        public Nullable<decimal> Qty_Wh { get; set; }
        public Nullable<decimal> QtyDstrSt01 { get; set; }
        public Nullable<decimal> QtyDstrHk01 { get; set; }
        public Nullable<decimal> QtyDstrA95 { get; set; }
        public Nullable<decimal> QtyDstrA98 { get; set; }
        public Nullable<decimal> QtyDstrOv { get; set; }
        public Nullable<decimal> QtyDstrPo { get; set; }
        public Nullable<decimal> QtyDstrPr { get; set; }
        public Nullable<decimal> QtyDstrPd { get; set; }
        public string po_no_unappr { get; set; }
        public Nullable<System.DateTime> Fst_LackDate { get; set; }
        public string SWork_Type { get; set; }
        public bool Acc_Flag { get; set; }
        public bool Acc_Lack { get; set; }
        public Nullable<System.DateTime> JobNo_Date { get; set; }
        public Nullable<decimal> Loc_Qty { get; set; }
        public string U_No { get; set; }
        public string Pmc_Remark { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<bool> diffdate_flag { get; set; }
        public Nullable<int> Mo_Status_Code { get; set; }
        public string SysRemark { get; set; }
        public Nullable<decimal> File_Seq_No { get; set; }
        public string Vdr_Code { get; set; }
    }
}
