//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1137
    {
        public System.DateTime Supply_Date { get; set; }
        public int plan_source { get; set; }
        public string job_no { get; set; }
        public int seq_no { get; set; }
        public System.DateTime tran_date { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal qty_used { get; set; }
        public string remark { get; set; }
        public bool cal_end { get; set; }
        public Nullable<int> LocUseSeq { get; set; }
        public Nullable<long> Mid { get; set; }
        public Nullable<bool> Loc { get; set; }
        public Nullable<decimal> part_per { get; set; }
        public string SysUser { get; set; }
    }
}
