//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1132
    {
        public Nullable<int> period { get; set; }
        public string pr_no { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal qty_pass { get; set; }
        public Nullable<System.DateTime> issuetime { get; set; }
        public decimal leadtime { get; set; }
        public Nullable<System.DateTime> ordertime { get; set; }
        public string remark { get; set; }
        public string pitem_no { get; set; }
        public decimal pqty_per { get; set; }
        public string ppr_no { get; set; }
        public int plan_source { get; set; }
        public Nullable<System.DateTime> pissuetime { get; set; }
        public string job_no { get; set; }
    }
}
