//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1148
    {
        public string Ord_Id { get; set; }
        public string Ord_PID { get; set; }
        public string Ord_Descc { get; set; }
        public string Ord_Desce { get; set; }
        public string tran_in { get; set; }
        public string tran_out { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Ord_Id_Same { get; set; }
        public string Ord_Id_sid { get; set; }
        public string Para_V { get; set; }
    }
}
