//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1149
    {
        public string Order_Head { get; set; }
        public decimal Max_No { get; set; }
        public int No_Len { get; set; }
        public string Ord_Desc { get; set; }
        public string Ord_Desce { get; set; }
        public bool No_Auto { get; set; }
        public int FrmTable { get; set; }
        public int ByType { get; set; }
        public string Ord_ID { get; set; }
        public bool pOrd_Flag { get; set; }
        public bool Hand_Flag { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool Cust_Flag { get; set; }
        public string Cust_Str { get; set; }
        public bool Tran_Flag { get; set; }
        public int YMD_Type { get; set; }
        public bool Cust_FlagA { get; set; }
    }
}
