//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1143
    {
        public string rpt_id { get; set; }
        public string rpt_desc { get; set; }
        public bool enoghrpt { get; set; }
        public bool notenoughrpt { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
