//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1140
    {
        public Nullable<bool> pr_type { get; set; }
        public string so_no { get; set; }
        public Nullable<decimal> seq_no { get; set; }
        public string wo_no { get; set; }
        public string ppr_no { get; set; }
        public string spr_no { get; set; }
        public string pitem_no { get; set; }
        public string item_no { get; set; }
        public Nullable<decimal> qty_requir { get; set; }
        public Nullable<decimal> qty_usewhs { get; set; }
        public Nullable<decimal> qty_usepr { get; set; }
        public Nullable<decimal> qty_pr { get; set; }
        public Nullable<System.DateTime> date_use { get; set; }
        public Nullable<decimal> leadtime { get; set; }
        public Nullable<System.DateTime> date_pr { get; set; }
        public string source { get; set; }
        public string item_bgrp { get; set; }
        public string item_grp { get; set; }
        public Nullable<decimal> qty_pass { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public Nullable<decimal> qty_free_bal { get; set; }
        public Nullable<decimal> qty_prfree_doing { get; set; }
        public string item_grpa { get; set; }
        public string pr_no_ref { get; set; }
        public Nullable<decimal> qty_ref { get; set; }
        public Nullable<int> ma_type { get; set; }
        public Nullable<decimal> qty_usewhs_bal { get; set; }
        public Nullable<decimal> qty_usepr_bal { get; set; }
        public Nullable<decimal> qty_pr_bal { get; set; }
        public Nullable<decimal> qty_usewhs_doing { get; set; }
        public Nullable<decimal> qty_usepr_doing { get; set; }
        public Nullable<decimal> qty_pr_doing { get; set; }
        public Nullable<decimal> qty_issue { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
        public Nullable<int> status_code { get; set; }
    }
}
