//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1141
    {
        public int plan_source { get; set; }
        public string job_no { get; set; }
        public Nullable<int> seq_no { get; set; }
        public string pitem_no { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal qty_supply { get; set; }
        public Nullable<decimal> qty_cur { get; set; }
        public Nullable<decimal> qty_f { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public Nullable<decimal> qty_planed_loc { get; set; }
        public Nullable<decimal> qty_planed { get; set; }
        public Nullable<decimal> qty_pr { get; set; }
        public Nullable<System.DateTime> date_planed_last { get; set; }
        public Nullable<int> ma_type { get; set; }
        public Nullable<System.DateTime> issuetime { get; set; }
        public Nullable<decimal> leadtime { get; set; }
        public Nullable<System.DateTime> purctime { get; set; }
        public string source { get; set; }
        public string item_bgrp { get; set; }
        public string item_grp { get; set; }
        public int status_code { get; set; }
        public string bom_ver { get; set; }
        public string bol_ver { get; set; }
        public Nullable<decimal> qty_nochange { get; set; }
        public Nullable<decimal> qty_yield { get; set; }
        public Nullable<decimal> qty_order { get; set; }
        public string remark { get; set; }
        public Nullable<bool> prnew { get; set; }
        public string H_pn_no { get; set; }
        public string D_pn_no { get; set; }
        public string H_pr_no { get; set; }
        public string D_pr_no { get; set; }
        public Nullable<bool> cal_end { get; set; }
        public bool @lock { get; set; }
        public string precedence { get; set; }
        public Nullable<System.DateTime> pmcPlanDate { get; set; }
        public Nullable<bool> IsSetprecedece { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
