//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1152
    {
        public string PLoc_Code { get; set; }
        public string SLoc_Code { get; set; }
        public string Loc_Descc { get; set; }
        public int Layer { get; set; }
        public decimal Issue_Obj { get; set; }
        public bool BPlan_Flag { get; set; }
    }
}
