//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1153
    {
        public string po_no { get; set; }
        public string buyer { get; set; }
        public decimal Po_Ttl { get; set; }
        public decimal Po_Net { get; set; }
        public decimal Other_Amt { get; set; }
        public string Other_Amt_Desc { get; set; }
        public decimal insurance { get; set; }
        public decimal amt1 { get; set; }
        public decimal hdiscount { get; set; }
        public Nullable<decimal> amt_invoice { get; set; }
        public string tran_type { get; set; }
        public int ov_type { get; set; }
        public string norloc_code { get; set; }
        public string iqcloc_code { get; set; }
        public string vdr_code { get; set; }
        public string vdr_name { get; set; }
        public string vdr_add1 { get; set; }
        public string vdr_add2 { get; set; }
        public string vdr_add3 { get; set; }
        public string vdr_add4 { get; set; }
        public string vdr_contact { get; set; }
        public string vdr_tel { get; set; }
        public string fax { get; set; }
        public string Pay_Code { get; set; }
        public string Ship_Code { get; set; }
        public string Sale_Code { get; set; }
        public string curr_code { get; set; }
        public decimal curr_rate { get; set; }
        public int count_out { get; set; }
        public string Remark { get; set; }
        public bool approve1 { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public Nullable<System.DateTime> ord_date { get; set; }
        public string ord_id { get; set; }
        public string vh_no { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public bool FmHandPr_Flag { get; set; }
        public bool WP_Flag { get; set; }
        public decimal Amt_Deli1 { get; set; }
        public decimal Amt_Deli2 { get; set; }
        public decimal Tax_Rate { get; set; }
        public decimal Amt_Tax { get; set; }
        public int MaxIssTimes { get; set; }
        public int MaxCnTimes { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public Nullable<bool> OverQty_Flag { get; set; }
        public Nullable<bool> Sample_Flag { get; set; }
        public Nullable<bool> Addr_En { get; set; }
        public string Org_Code { get; set; }
        public string Vdr_PurRemark { get; set; }
        public string Contract_No { get; set; }
        public Nullable<decimal> Amt_Discount { get; set; }
        public Nullable<System.DateTime> Fax_Date { get; set; }
        public Nullable<bool> SelfPur_Flag { get; set; }
    }
}
