//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1150
    {
        public int Status_code { get; set; }
        public string Status_desce { get; set; }
        public string Status_descc { get; set; }
        public string type_desc { get; set; }
        public bool status { get; set; }
        public int type_id { get; set; }
        public string sysuser { get; set; }
        public System.DateTime sysdate { get; set; }
    }
}
