//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1154
    {
        public string po_no { get; set; }
        public int pseq_no { get; set; }
        public string item_no { get; set; }
        public string item_desc { get; set; }
        public string uom { get; set; }
        public decimal uomrate { get; set; }
        public bool item_free { get; set; }
        public decimal unit_price { get; set; }
        public decimal discount { get; set; }
        public decimal qty { get; set; }
        public decimal qty_recd { get; set; }
        public decimal qty_pass_free { get; set; }
        public decimal qty_iqc { get; set; }
        public decimal qty_rej_g { get; set; }
        public decimal qty_rej_a { get; set; }
        public decimal Qty_Iqc_Pay { get; set; }
        public decimal Qty_Iqc_Free { get; set; }
        public decimal Qty_UnAppr_Pay { get; set; }
        public decimal Qty_UnAppr_Free { get; set; }
        public decimal qty_unappr { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public Nullable<decimal> qty_bal_out { get; set; }
        public decimal qty_issue { get; set; }
        public decimal qty_issue_rej { get; set; }
        public decimal qty_invoice { get; set; }
        public decimal Qty_Per_Add { get; set; }
        public decimal amt { get; set; }
        public decimal amt_r { get; set; }
        public System.DateTime FTD { get; set; }
        public Nullable<System.DateTime> ctd { get; set; }
        public Nullable<System.DateTime> ctd2 { get; set; }
        public string WO_NO { get; set; }
        public string Remark { get; set; }
        public int status_code { get; set; }
        public string status_user { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public bool mrp { get; set; }
        public bool iqc { get; set; }
        public string PR_NO { get; set; }
        public decimal cost { get; set; }
        public bool useall_flag { get; set; }
        public bool hprice_flag { get; set; }
        public Nullable<System.DateTime> mrp_date { get; set; }
        public Nullable<decimal> mrp_qty { get; set; }
        public bool lot_flag { get; set; }
        public string vh_no { get; set; }
        public string VPRule_Code { get; set; }
        public int MVer { get; set; }
        public int R_MaxTimes { get; set; }
        public string sysremark { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public Nullable<System.DateTime> Tran_Date { get; set; }
        public bool Rej_Flag { get; set; }
        public decimal T_Qty_Rej { get; set; }
        public Nullable<System.DateTime> LIssue_Date { get; set; }
        public Nullable<decimal> Lead_Time { get; set; }
        public string VPgrp_Code { get; set; }
        public decimal Tax_Rate { get; set; }
        public bool TaxRate_flag { get; set; }
        public decimal Amt_Tax { get; set; }
        public decimal qtyh_po { get; set; }
        public decimal qtyl_po { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal Qty_OutMat { get; set; }
        public string In_Remark { get; set; }
        public string Info_Type { get; set; }
        public Nullable<decimal> Know_Qty { get; set; }
        public Nullable<System.DateTime> Know_Date { get; set; }
        public string Know_User { get; set; }
        public Nullable<decimal> Rela_Seq { get; set; }
        public Nullable<decimal> Ref_Seq { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string OutMat_Remark { get; set; }
        public string MK_ID { get; set; }
        public string TaxSt_Code { get; set; }
        public string So_No { get; set; }
        public string OurModel { get; set; }
        public string Pmc_Remark { get; set; }
        public decimal Qty1 { get; set; }
        public string Uom1 { get; set; }
        public decimal qty_recd1 { get; set; }
        public decimal qty_rej1 { get; set; }
        public string H007B { get; set; }
        public decimal Qty_Rej_ReOrder { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
    }
}
