//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1158
    {
        public string pl_no { get; set; }
        public string cn_no { get; set; }
        public string cn_grp { get; set; }
        public string cn_head { get; set; }
        public string ch_foot { get; set; }
        public string Item_No { get; set; }
        public decimal NW { get; set; }
        public decimal GW { get; set; }
        public decimal Measure { get; set; }
        public string WX_Spec53 { get; set; }
    }
}
