//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1155
    {
        public string po_no { get; set; }
        public int seq_no { get; set; }
        public int pseq_no { get; set; }
        public string item_no { get; set; }
        public string item_desc { get; set; }
        public string uom { get; set; }
        public decimal qty_per { get; set; }
        public decimal yield { get; set; }
        public decimal proof { get; set; }
        public bool Yield_Flag { get; set; }
        public decimal qty { get; set; }
        public decimal qty_pick { get; set; }
        public decimal qty_rej { get; set; }
        public decimal qty_r { get; set; }
        public Nullable<decimal> qty_bal { get; set; }
        public decimal unit_price { get; set; }
        public decimal amt { get; set; }
        public string Remark { get; set; }
        public bool useall_flag { get; set; }
        public string po_mno { get; set; }
        public bool lot_flag { get; set; }
        public int frm_flag { get; set; }
        public int status_code { get; set; }
        public string precedence { get; set; }
        public string line_code { get; set; }
        public string line_class { get; set; }
        public string SysRemark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public Nullable<System.DateTime> LastOut_Date { get; set; }
    }
}
