//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1169
    {
        public string pt_no { get; set; }
        public string so_no { get; set; }
        public string mk_id { get; set; }
        public string cust_code { get; set; }
        public string cust_model { get; set; }
        public string cust_cll { get; set; }
        public Nullable<System.DateTime> fin_date { get; set; }
        public string picpath1 { get; set; }
        public string pic_desc1 { get; set; }
        public string pic_descpos1 { get; set; }
        public string picpath2 { get; set; }
        public string pic_desc2 { get; set; }
        public string pic_descpos2 { get; set; }
        public Nullable<int> maxisstimes { get; set; }
        public string line_code { get; set; }
        public bool Approve { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public string Last_User { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
