//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1167
    {
        public string pocn_no { get; set; }
        public string pocn_type { get; set; }
        public string po_no { get; set; }
        public int seq_no { get; set; }
        public string item_no { get; set; }
        public bool item_free { get; set; }
        public string item_desc { get; set; }
        public string uom { get; set; }
        public decimal uomrate { get; set; }
        public decimal qty { get; set; }
        public decimal unit_price { get; set; }
        public decimal discount { get; set; }
        public bool Sample { get; set; }
        public bool iqc { get; set; }
        public string pr_no { get; set; }
        public System.DateTime ftd { get; set; }
        public Nullable<System.DateTime> ctd { get; set; }
        public string remark { get; set; }
        public string In_Remark { get; set; }
        public int status_code { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public string status_user { get; set; }
        public decimal Tax_Rate { get; set; }
        public bool TaxRate_Flag { get; set; }
        public bool Service { get; set; }
        public string uom1 { get; set; }
        public decimal Qty1 { get; set; }
        public Nullable<decimal> Know_Qty { get; set; }
        public Nullable<decimal> Know_Qty1 { get; set; }
        public Nullable<decimal> Rela_Seq { get; set; }
        public Nullable<decimal> Ref_Seq { get; set; }
        public string MK_ID { get; set; }
        public string Info_Type { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string Appr_User { get; set; }
        public bool Approve { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
        public decimal QtyH_Po { get; set; }
        public string VpRule_Code { get; set; }
        public string TaxSt_Code { get; set; }
        public Nullable<System.DateTime> CTD2 { get; set; }
        public string SysRemark { get; set; }
        public string So_No { get; set; }
        public string OurModel { get; set; }
        public string Pmc_Remark { get; set; }
        public string Line_Code { get; set; }
        public decimal unit_price_bef { get; set; }
        public decimal unit_price_delay { get; set; }
        public string rec_grp { get; set; }
        public string ToUom { get; set; }
        public Nullable<decimal> ToUomRate { get; set; }
        public Nullable<decimal> ToUomQty { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
    }
}
