//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1162
    {
        public string Po_No { get; set; }
        public string Ord_Id { get; set; }
        public string Buyer { get; set; }
        public string Vdr_Code { get; set; }
        public string NorLoc_Code { get; set; }
        public string IqcLoc_Code { get; set; }
        public string Pay_Code { get; set; }
        public string Ship_Code { get; set; }
        public string sale_Code { get; set; }
        public string Curr_Code { get; set; }
        public Nullable<decimal> Curr_Rate { get; set; }
        public string ConTact { get; set; }
        public bool Addr_En { get; set; }
        public string Vdr_Add1 { get; set; }
        public string Vdr_Add2 { get; set; }
        public string Vdr_Add3 { get; set; }
        public string Vdr_Add4 { get; set; }
        public string Last_CnNo { get; set; }
        public decimal Po_Ttl { get; set; }
        public decimal HDisCount { get; set; }
        public decimal Po_Net { get; set; }
        public decimal Amt_Invoice { get; set; }
        public decimal Other_Amt { get; set; }
        public string Other_Amt_Desc { get; set; }
        public decimal Insurance { get; set; }
        public string Vh_No { get; set; }
        public bool Main_Flag { get; set; }
        public Nullable<System.DateTime> Fax_Date { get; set; }
        public bool FmHandPr_Flag { get; set; }
        public decimal Amt_Deli1 { get; set; }
        public decimal Amt_Deli2 { get; set; }
        public decimal Tax_Rate { get; set; }
        public decimal Amt_Tax { get; set; }
        public string AOod_ID { get; set; }
        public string Org_Code { get; set; }
        public decimal Amt_Discount { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string ReMark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public int Cn_Max { get; set; }
        public string Contract_No { get; set; }
        public string Vdr_PurRemark { get; set; }
        public bool Apply_Flag { get; set; }
        public Nullable<System.DateTime> Tran_Date { get; set; }
        public string Con_Remark { get; set; }
        public string Con_User { get; set; }
        public string Con_Tel { get; set; }
        public string Con_Fax { get; set; }
        public bool ToFax_Flag { get; set; }
        public bool ToEmail_Flag { get; set; }
    }
}
