//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1166
    {
        public string pocn_no { get; set; }
        public string pocn_type { get; set; }
        public string ord_id { get; set; }
        public string buyer { get; set; }
        public string vdr_code { get; set; }
        public string norloc_code { get; set; }
        public string iqcloc_code { get; set; }
        public string Pay_code { get; set; }
        public string ship_code { get; set; }
        public string sale_code { get; set; }
        public string curr_code { get; set; }
        public decimal curr_rate { get; set; }
        public string contact { get; set; }
        public Nullable<bool> addr_en { get; set; }
        public string vdr_add1 { get; set; }
        public string vdr_add2 { get; set; }
        public string vdr_add3 { get; set; }
        public string vdr_add4 { get; set; }
        public decimal po_ttl { get; set; }
        public decimal hdiscount { get; set; }
        public decimal po_net { get; set; }
        public decimal other_amt_del { get; set; }
        public decimal insurance_del { get; set; }
        public string remark { get; set; }
        public int Seq_No { get; set; }
        public decimal Tax_Rate { get; set; }
        public string org_code { get; set; }
        public decimal amt_discount { get; set; }
        public decimal amt_tax { get; set; }
        public string Contract_No { get; set; }
        public string Vdr_PurRemark { get; set; }
        public Nullable<System.DateTime> Fax_Date { get; set; }
        public bool Apply_Flag { get; set; }
        public Nullable<System.DateTime> Tran_Date { get; set; }
        public string Con_Remark { get; set; }
        public string Con_User { get; set; }
        public string Con_Tel { get; set; }
        public string Con_Fax { get; set; }
    }
}
