//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1164
    {
        public string po_no { get; set; }
        public int seq_no { get; set; }
        public string pr_no { get; set; }
        public decimal qty { get; set; }
        public Nullable<System.DateTime> issuetime { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public int status_code { get; set; }
        public string ord_pid { get; set; }
        public int SonPr_Flag { get; set; }
        public bool Lot_Flag { get; set; }
        public string Remark { get; set; }
        public bool ClosePr_Flag { get; set; }
    }
}
