//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1172
    {
        public string pt_no { get; set; }
        public int seq_no { get; set; }
        public int Item_Seq { get; set; }
        public decimal seq_so { get; set; }
        public string item_no { get; set; }
        public decimal qty_so { get; set; }
        public decimal qty_Pt { get; set; }
        public decimal qty_per { get; set; }
        public decimal yield { get; set; }
        public bool Yield_Flag { get; set; }
        public decimal qty { get; set; }
        public decimal qty_f { get; set; }
        public int status_code { get; set; }
        public bool pkmat_type { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public decimal qty_next { get; set; }
        public bool useall_flag { get; set; }
        public string pt_mno { get; set; }
        public string precedence { get; set; }
        public string SysRemark { get; set; }
        public bool approve { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public string appr_user { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public Nullable<System.DateTime> LastOut_Date { get; set; }
        public string Job_No { get; set; }
        public string Line_Code { get; set; }
        public string Remark { get; set; }
        public string Pic_File { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public string spec4 { get; set; }
        public string spec5 { get; set; }
        public string spec6 { get; set; }
        public string spec7 { get; set; }
        public string spec8 { get; set; }
        public string spec9 { get; set; }
        public string spec10 { get; set; }
        public bool Pur_Flag { get; set; }
    }
}
