//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1175
    {
        public string File_no { get; set; }
        public string Ord_id { get; set; }
        public Nullable<System.DateTime> Tran_date { get; set; }
        public string iqcloc_code { get; set; }
        public string toloc_code_pass { get; set; }
        public string toloc_code_rej { get; set; }
        public string toloc_code_loss { get; set; }
        public string iqc_user { get; set; }
        public Nullable<bool> Approve { get; set; }
        public string Appr_user { get; set; }
        public Nullable<System.DateTime> Appr_date { get; set; }
        public string SysUser { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public string receiver_pass { get; set; }
        public string receiver_rej { get; set; }
        public string receiver_loss { get; set; }
        public string receiver_less { get; set; }
        public int Mtimes { get; set; }
        public string AccCode { get; set; }
        public string Rej_Flow_ID { get; set; }
        public string vh_no { get; set; }
        public string vh_no1 { get; set; }
        public string vh_no2 { get; set; }
        public string ReCab_No { get; set; }
        public bool M31405 { get; set; }
    }
}
