//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1171
    {
        public string pt_no { get; set; }
        public int seq_no { get; set; }
        public string ptitem { get; set; }
        public string item_desc1 { get; set; }
        public string item_desc2 { get; set; }
        public string item_desc3 { get; set; }
        public string item_desc4 { get; set; }
        public string item_desc5 { get; set; }
        public string item_desc6 { get; set; }
        public Nullable<int> line_under { get; set; }
        public Nullable<int> line_side { get; set; }
        public Nullable<int> line_underfont { get; set; }
        public Nullable<bool> line_left { get; set; }
        public Nullable<bool> line_right { get; set; }
        public Nullable<bool> line_top { get; set; }
        public Nullable<bool> line_bottom { get; set; }
        public Nullable<bool> line_bottomA { get; set; }
        public Nullable<bool> font_underline { get; set; }
        public Nullable<bool> font_skyline { get; set; }
        public Nullable<bool> font_bold { get; set; }
        public Nullable<bool> font_Italic { get; set; }
        public string font_name { get; set; }
        public Nullable<double> font_size { get; set; }
        public short SpanCell { get; set; }
        public short Print_Type { get; set; }
        public string Pic_File { get; set; }
        public string sysuser { get; set; }
        public Nullable<System.DateTime> sysdate { get; set; }
    }
}
