//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1170
    {
        public string pt_no { get; set; }
        public int seq_no { get; set; }
        public int sseq_no { get; set; }
        public bool part_type { get; set; }
        public string color_code { get; set; }
        public string our_desc { get; set; }
        public string spec1 { get; set; }
        public string spec2 { get; set; }
        public string spec3 { get; set; }
        public Nullable<decimal> seq_no1 { get; set; }
        public string size1 { get; set; }
        public Nullable<decimal> seq_no2 { get; set; }
        public string size2 { get; set; }
        public Nullable<decimal> seq_no3 { get; set; }
        public string size3 { get; set; }
        public Nullable<decimal> seq_no4 { get; set; }
        public string size4 { get; set; }
        public string sp_item_no { get; set; }
    }
}
