//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1176
    {
        public string File_no { get; set; }
        public string pfile_no { get; set; }
        public Nullable<int> pseq_no { get; set; }
        public string so_no { get; set; }
        public Nullable<decimal> so_seq { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal qty_pass { get; set; }
        public decimal qty_pass_pay { get; set; }
        public decimal qty_pass_free { get; set; }
        public decimal qty_unpass { get; set; }
        public decimal qty_unpass2 { get; set; }
        public decimal qty_rej_g { get; set; }
        public decimal qty_rej_a { get; set; }
        public decimal qty_rej_g2 { get; set; }
        public decimal qty_rej_a2 { get; set; }
        public decimal qty_loss { get; set; }
        public decimal qty_loss2 { get; set; }
        public decimal qty_loss_pay { get; set; }
        public decimal qty_loss_free { get; set; }
        public decimal Qty_Loss_Pay2 { get; set; }
        public decimal qty_less { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> org_cost { get; set; }
        public string curr_code { get; set; }
        public Nullable<decimal> ex_rate { get; set; }
        public string remark { get; set; }
        public string org_file_no { get; set; }
        public Nullable<int> org_seq_no { get; set; }
        public long MID { get; set; }
        public decimal check_hours { get; set; }
        public decimal OrgUnit_Price { get; set; }
        public decimal Tax_Rate { get; set; }
        public bool TaxRate_Flag { get; set; }
        public decimal Tax_Amt { get; set; }
        public decimal Amt { get; set; }
        public decimal Qty_Pay { get; set; }
        public decimal OrgUnit_Price2 { get; set; }
        public decimal Tax_Rate2 { get; set; }
        public bool TaxRate_Flag2 { get; set; }
        public decimal Tax_Amt2 { get; set; }
        public decimal Amt2 { get; set; }
        public decimal Qty_Pay2 { get; set; }
        public bool Check_Flag { get; set; }
        public string UptUser { get; set; }
        public Nullable<System.DateTime> UptDate { get; set; }
        public Nullable<bool> UptAppr_Flag { get; set; }
        public string UptAppr_User { get; set; }
        public Nullable<System.DateTime> UptAppr_Date { get; set; }
        public string File_No1 { get; set; }
        public Nullable<decimal> Qty_G { get; set; }
        public Nullable<decimal> Ex_Rate2 { get; set; }
        public Nullable<decimal> qty_sample { get; set; }
        public Nullable<decimal> good_sample { get; set; }
        public Nullable<decimal> bad_sample { get; set; }
        public decimal qty_less2 { get; set; }
        public string check_no { get; set; }
        public string remark2 { get; set; }
        public string FrmLot_No { get; set; }
        public Nullable<int> FrmLot_Seq_No { get; set; }
        public Nullable<decimal> Qty_UnPassFree { get; set; }
        public Nullable<decimal> Qty_UnPassFree2 { get; set; }
        public string Pass_User2 { get; set; }
        public Nullable<System.DateTime> Pass_Date2 { get; set; }
        public string Frm_User2 { get; set; }
        public string Bat_No { get; set; }
    }
}
