//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1183
    {
        public string refab_no { get; set; }
        public int seq_no { get; set; }
        public string Tran_type { get; set; }
        public string item_no { get; set; }
        public string item_desc { get; set; }
        public string uom { get; set; }
        public decimal qty { get; set; }
        public decimal cost { get; set; }
        public decimal costrate { get; set; }
        public Nullable<decimal> qty_per { get; set; }
    }
}
