//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1187
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string Line_Code { get; set; }
        public string So_No { get; set; }
        public decimal So_Seq_No { get; set; }
        public string Pl_No { get; set; }
        public int Pl_Seq_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty_Org { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_F { get; set; }
        public Nullable<decimal> Qty_Bal { get; set; }
        public string File_No1 { get; set; }
        public decimal Qty1 { get; set; }
        public string File_No2 { get; set; }
        public decimal Qty2 { get; set; }
        public string File_No3 { get; set; }
        public decimal Qty3 { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public Nullable<bool> G_Flag { get; set; }
    }
}
