//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1186
    {
        public string File_No { get; set; }
        public string Cust_Code { get; set; }
        public bool SoNo_FLag { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public int Qty_Box { get; set; }
        public string Loc_Code1 { get; set; }
        public string Loc_Code2 { get; set; }
        public string Loc_Code3 { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Ord_ID { get; set; }
    }
}
