//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1180
    {
        public string File_No { get; set; }
        public string Ord_ID { get; set; }
        public string Line_Code { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string Job_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public decimal T_Qty_Pass { get; set; }
        public decimal T_Qty_Scrap { get; set; }
        public decimal T_Qty_Repair { get; set; }
        public string QcSuggest { get; set; }
        public string Checker { get; set; }
        public bool Appr_Flag { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
