//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1181
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string QItem_Code { get; set; }
        public string QC_Desc { get; set; }
        public decimal QItem_Good { get; set; }
        public decimal QItem_Bad { get; set; }
        public string QItemSuggest { get; set; }
        public string Frm_Dept { get; set; }
        public string Frm_User { get; set; }
        public string Frm_Desc { get; set; }
        public string Remark { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
