//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1196
    {
        public string User_name { get; set; }
        public string User_Desc { get; set; }
        public string PassWord { get; set; }
        public string department { get; set; }
        public string work_type { get; set; }
        public Nullable<System.DateTime> input_date { get; set; }
        public string input_name { get; set; }
        public bool Effect { get; set; }
        public string DisEff_User { get; set; }
        public Nullable<System.DateTime> DisEff_Date { get; set; }
        public bool Online_Flag { get; set; }
        public Nullable<System.DateTime> In_Date { get; set; }
        public string OnLine_Host { get; set; }
        public string ColourSet { get; set; }
        public string Loc_Code { get; set; }
        public string Work_Desc { get; set; }
        public string l_id { get; set; }
        public string Emp_Code { get; set; }
        public System.DateTime FrmDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<System.DateTime> FileModify_Date { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public bool Remot_Flag { get; set; }
        public bool ShowShort_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string MyPic { get; set; }
        public Nullable<bool> QQ_OnLine { get; set; }
        public string Email { get; set; }
        public string mobil { get; set; }
        public string addr { get; set; }
    }
}
