//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1207
    {
        public string cn_no { get; set; }
        public string socn_type { get; set; }
        public string so_no { get; set; }
        public string sales { get; set; }
        public string cust_code { get; set; }
        public string cust_add1 { get; set; }
        public string cust_add2 { get; set; }
        public string cust_add3 { get; set; }
        public string cust_add4 { get; set; }
        public string Ship_Add1 { get; set; }
        public string Ship_Add2 { get; set; }
        public string Ship_Add3 { get; set; }
        public string Ship_Add4 { get; set; }
        public string title { get; set; }
        public string contact { get; set; }
        public string Pay_code { get; set; }
        public string ship_code { get; set; }
        public string sale_code { get; set; }
        public string item_sotype { get; set; }
        public string woremark { get; set; }
        public string Remark { get; set; }
        public string SpRemark { get; set; }
        public string curr_code { get; set; }
        public decimal curr_rate { get; set; }
        public decimal t_discount { get; set; }
        public decimal t_damt { get; set; }
        public bool export { get; set; }
        public bool Tax_Add { get; set; }
        public decimal Qty_Perh { get; set; }
        public decimal Qty_PerL { get; set; }
        public decimal net_amt { get; set; }
        public decimal ttl_amt { get; set; }
        public string tax_order { get; set; }
        public decimal cn_max { get; set; }
        public decimal deposit { get; set; }
        public string ord_id { get; set; }
        public decimal insurance { get; set; }
        public string Rela_no { get; set; }
        public int status_code { get; set; }
        public string sohtext { get; set; }
        public string cust_cll { get; set; }
        public string cust_model { get; set; }
        public Nullable<bool> mat_plan { get; set; }
        public int maxytimes { get; set; }
        public string ourmodel { get; set; }
        public int printver { get; set; }
        public string att1_amt_desc { get; set; }
        public string Sp_No { get; set; }
        public string Qc_No { get; set; }
        public bool RData_Flag { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public string M97 { get; set; }
        public string Cn_Desc { get; set; }
        public string Addr_Code_acc { get; set; }
        public string Addr_Code_ship { get; set; }
        public string CD_Code { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
        public string OrgType_Code { get; set; }
        public bool Flag3 { get; set; }
        public bool Issue_Flag { get; set; }
        public bool NotFin_Flag { get; set; }
        public string PackRemark { get; set; }
        public Nullable<System.DateTime> Tran_Date { get; set; }
        public string ForWarder { get; set; }
        public string PIRemark { get; set; }
        public string C001A { get; set; }
        public string D004A { get; set; }
        public string Mps_User { get; set; }
        public string Acc_Add1 { get; set; }
        public string Acc_Add2 { get; set; }
        public string Acc_Add3 { get; set; }
        public string Acc_Add4 { get; set; }
        public string Sales2 { get; set; }
        public string wo_no { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string www { get; set; }
    }
}
