//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1208
    {
        public string cn_no { get; set; }
        public string socn_type { get; set; }
        public string so_no { get; set; }
        public decimal seq_no { get; set; }
        public string mk_id { get; set; }
        public string item_no { get; set; }
        public string info_type { get; set; }
        public bool pack_status { get; set; }
        public decimal Rela_seq { get; set; }
        public decimal qty { get; set; }
        public decimal qty_sd { get; set; }
        public Nullable<System.DateTime> know_date { get; set; }
        public decimal know_qty { get; set; }
        public decimal know_qty_sd { get; set; }
        public decimal unit_price { get; set; }
        public decimal unit_price_pk { get; set; }
        public decimal discount { get; set; }
        public string sodtext { get; set; }
        public System.DateTime rtd { get; set; }
        public System.DateTime ftd { get; set; }
        public string cust_po { get; set; }
        public string Cpo_Seq_No { get; set; }
        public string UCust_Po { get; set; }
        public Nullable<System.DateTime> Fax_date { get; set; }
        public Nullable<System.DateTime> custpo_date { get; set; }
        public decimal Dn_qty { get; set; }
        public decimal Dn_qty_sd { get; set; }
        public string uom { get; set; }
        public string item_desc { get; set; }
        public bool part_type { get; set; }
        public bool new_y { get; set; }
        public string dn_no { get; set; }
        public string dn_remark { get; set; }
        public Nullable<decimal> dn_amt { get; set; }
        public string wo_no { get; set; }
        public Nullable<System.DateTime> pmc_date { get; set; }
        public string pmc_remark { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Col_Flg { get; set; }
        public string pt_no { get; set; }
        public bool job_yes { get; set; }
        public string yourcolor { get; set; }
        public string ourcolor { get; set; }
        public string tt_lens { get; set; }
        public string yoursize { get; set; }
        public Nullable<int> mrp { get; set; }
        public bool lot_yes { get; set; }
        public bool issue_yes { get; set; }
        public string dcust_code { get; set; }
        public string inv_org_country { get; set; }
        public decimal inv_unit_price { get; set; }
        public bool mps_flag { get; set; }
        public string pcs_pmcmk { get; set; }
        public string pcs_mktmk { get; set; }
        public string SysRemark { get; set; }
        public Nullable<bool> mps_plan { get; set; }
        public Nullable<System.DateTime> Tocust_Date { get; set; }
        public Nullable<System.DateTime> Tocust_Date1 { get; set; }
        public decimal Qty_Pt { get; set; }
        public string M45 { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc { get; set; }
        public Nullable<System.DateTime> Cal_Date { get; set; }
        public decimal Qty_Rej { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public bool Approve { get; set; }
        public string Appr_user { get; set; }
        public Nullable<System.DateTime> Appr_date { get; set; }
        public int status_code { get; set; }
        public string status_user { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public bool scn_flag { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
        public string SoPrice_No { get; set; }
        public decimal Tax_Rate { get; set; }
        public bool TaxRate_Flag { get; set; }
        public bool Issue_Flag { get; set; }
        public bool Yield_Flag { get; set; }
        public bool Proof_Flag { get; set; }
        public string PI_No { get; set; }
        public string M281 { get; set; }
        public string M305 { get; set; }
        public bool Flag1 { get; set; }
        public string TaxSt_Code { get; set; }
        public Nullable<int> Color_Num { get; set; }
        public string yourmodel { get; set; }
        public string yourcolor_desc { get; set; }
        public string Degree { get; set; }
        public Nullable<decimal> Array_Qty { get; set; }
        public Nullable<int> Array_Grp { get; set; }
        public Nullable<bool> NotMove_Flag { get; set; }
        public Nullable<decimal> Sales2_Per { get; set; }
        public Nullable<bool> Sales2Per_Type { get; set; }
        public string item_type { get; set; }
        public string ourmodel { get; set; }
        public decimal qty_sample { get; set; }
        public string Shop_Code { get; set; }
        public int KnowProd_Times { get; set; }
        public string KnowProdTimes_User { get; set; }
        public Nullable<System.DateTime> KnowProdTimes_Date { get; set; }
        public string DSPlan_No { get; set; }
        public Nullable<int> DSPlan_Seq_No { get; set; }
        public string ref_file_no { get; set; }
        public Nullable<int> ref_seq_no { get; set; }
    }
}
