//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1215
    {
        public long AutoID { get; set; }
        public int Seq_No { get; set; }
        public int Pseq_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty_Per { get; set; }
        public decimal Qty_NoChange { get; set; }
        public decimal Yield { get; set; }
        public string Uom { get; set; }
        public string Item_Descc { get; set; }
        public decimal Unit_Price { get; set; }
        public string Source { get; set; }
        public string Item_Type { get; set; }
        public int Type_Flag { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public Nullable<decimal> OrgUnit_Price { get; set; }
        public string vdr_code { get; set; }
        public string UnitPrice_Remark { get; set; }
        public Nullable<System.DateTime> UnitPrice_Date { get; set; }
    }
}
