//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1216
    {
        public string File_no { get; set; }
        public string Ord_id { get; set; }
        public Nullable<int> tran_id { get; set; }
        public string tran_type { get; set; }
        public System.DateTime Tran_date { get; set; }
        public string Fromloc { get; set; }
        public string Toloc { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public string Vh_No { get; set; }
        public bool Flag { get; set; }
        public bool Approve { get; set; }
        public string Appr_user { get; set; }
        public Nullable<System.DateTime> Appr_date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Remark { get; set; }
    }
}
