//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1217
    {
        public string File_no { get; set; }
        public int Seq_no { get; set; }
        public string ITEM_NO { get; set; }
        public decimal QTY { get; set; }
        public decimal Qty1 { get; set; }
        public decimal QTY_F { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public string REMARK { get; set; }
        public string Iqc_No { get; set; }
        public long MID { get; set; }
        public string Flag_Desc { get; set; }
        public string Job_No { get; set; }
        public string PFile_No { get; set; }
        public Nullable<int> PSeq_No { get; set; }
        public string Org_File_No { get; set; }
        public Nullable<int> Org_Seq_No { get; set; }
        public string Po_No { get; set; }
        public Nullable<int> Po_Seq_No { get; set; }
        public decimal OrgUnit_Price { get; set; }
        public decimal Tax_Rate { get; set; }
        public bool TaxRate_Flag { get; set; }
        public decimal Tax_Amt { get; set; }
        public decimal Amt { get; set; }
        public decimal Qty_Pay { get; set; }
        public decimal OrgUnit_Price2 { get; set; }
        public decimal Tax_Rate2 { get; set; }
        public bool TaxRate_Flag2 { get; set; }
        public decimal Tax_Amt2 { get; set; }
        public decimal Amt2 { get; set; }
        public decimal Qty_Pay2 { get; set; }
        public bool Check_Flag { get; set; }
        public string UptUser { get; set; }
        public Nullable<System.DateTime> UptDate { get; set; }
        public Nullable<bool> UptAppr_Flag { get; set; }
        public string UptAppr_User { get; set; }
        public Nullable<System.DateTime> UptAppr_Date { get; set; }
        public Nullable<decimal> Curr_Rate { get; set; }
        public Nullable<decimal> Qty_G { get; set; }
        public Nullable<decimal> Ex_Rate { get; set; }
        public Nullable<decimal> Ex_Rate2 { get; set; }
        public string check_no { get; set; }
        public string remark2 { get; set; }
    }
}
