//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1213
    {
        public string PARENTITEM { get; set; }
        public string SONITEM { get; set; }
        public decimal QTY_PER { get; set; }
        public decimal Yield { get; set; }
        public decimal qty_nochange { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public string UOM { get; set; }
        public string ITEM_DESC { get; set; }
        public string REMARK { get; set; }
        public string Gsonitem { get; set; }
        public decimal Gqty_per { get; set; }
        public decimal Glast_price { get; set; }
        public decimal Callast_price { get; set; }
        public int Bom_Type { get; set; }
        public string Job_No { get; set; }
        public int Seq_No { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
