//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1229
    {
        public string File_No { get; set; }
        public string Ord_Id { get; set; }
        public string Loc_Code { get; set; }
        public int MaxNo { get; set; }
        public bool Approve { get; set; }
        public string Appr_user { get; set; }
        public Nullable<System.DateTime> Appr_date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
