//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1236
    {
        public string file_no { get; set; }
        public string wip_code { get; set; }
        public string ps_code { get; set; }
        public string loc_code { get; set; }
        public string tran_type { get; set; }
        public System.DateTime tran_date { get; set; }
        public string Sender { get; set; }
        public string receiver { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_code { get; set; }
        public string org_code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
