//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1237
    {
        public string File_no { get; set; }
        public int Seq_no { get; set; }
        public string Fwo_no { get; set; }
        public string FItem_no { get; set; }
        public int FQty { get; set; }
        public string Tso_no { get; set; }
        public Nullable<decimal> Tso_seq { get; set; }
        public string TItem_no { get; set; }
        public Nullable<int> TQty { get; set; }
        public string Remark { get; set; }
    }
}
