//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1240
    {
        public string file_no { get; set; }
        public int seq_no { get; set; }
        public string sfile_no { get; set; }
        public int sseq_no { get; set; }
        public string job_no { get; set; }
        public string item_no { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string remark { get; set; }
        public long MID { get; set; }
        public int Status_Code { get; set; }
        public string M140 { get; set; }
        public string frmOrd_ID { get; set; }
        public string Org_File_No { get; set; }
        public Nullable<int> Org_Seq_No { get; set; }
        public string Tran_Type { get; set; }
    }
}
