//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1243
    {
        public int Seq_No { get; set; }
        public string line_class { get; set; }
        public string Bol_code { get; set; }
        public string Bol_num { get; set; }
        public string Bol_desc { get; set; }
        public string Bol_Alias { get; set; }
        public string M305 { get; set; }
        public decimal P_time { get; set; }
        public decimal R_Time { get; set; }
        public decimal W_time { get; set; }
        public decimal T_time { get; set; }
        public decimal P_cost { get; set; }
        public bool Bacode { get; set; }
        public bool Spec_Flag { get; set; }
        public string SL_Code { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public int Status_code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string Tool_No { get; set; }
        public string Machine_no { get; set; }
        public Nullable<int> bol_type { get; set; }
        public bool Wip_Flag { get; set; }
        public bool Pwk_Flag { get; set; }
        public bool NotQty_Flag { get; set; }
        public Nullable<decimal> SID_PTime_More { get; set; }
        public Nullable<bool> SID_NotQty_Flag { get; set; }
        public bool SID_DebutM_Flag { get; set; }
    }
}
