//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1244
    {
        public string Line_Code { get; set; }
        public string Line_Class { get; set; }
        public string Type_Descc { get; set; }
        public int Seq_No { get; set; }
        public decimal Cap_Theor { get; set; }
        public decimal Cap_Rated { get; set; }
        public decimal Cap_Max { get; set; }
        public string IP { get; set; }
        public string Emp_Code { get; set; }
        public bool Ov_Flag { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<bool> MyPur_Flag { get; set; }
        public Nullable<decimal> QtyMust_Yield_Per { get; set; }
        public decimal qty_bol_split { get; set; }
        public Nullable<decimal> SID_qtybol_split_MorePer { get; set; }
    }
}
