//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1254
    {
        public string Work_type { get; set; }
        public string Wtype_desc { get; set; }
        public string Line_Class { get; set; }
        public string work_grp { get; set; }
        public string work_typea { get; set; }
        public string work_grpa { get; set; }
        public string wc_grp { get; set; }
        public Nullable<bool> job_yes { get; set; }
        public Nullable<bool> lot_yes { get; set; }
        public Nullable<bool> ptp { get; set; }
        public Nullable<int> status_code { get; set; }
        public Nullable<decimal> lead_time { get; set; }
        public string short_desc { get; set; }
        public Nullable<int> seq_no { get; set; }
        public Nullable<bool> sum_yes { get; set; }
        public Nullable<bool> job_raw { get; set; }
        public string st_flag { get; set; }
        public string fh_flag { get; set; }
        public string Work_GrpB { get; set; }
        public string pic_key { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
