//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1250
    {
        public string Route_Code { get; set; }
        public string Route_Ver { get; set; }
        public int Line_Class_Seq { get; set; }
        public string Bol_Code { get; set; }
        public int Bol_Code_Seq { get; set; }
        public string Remark { get; set; }
        public bool Ctrl_Point { get; set; }
        public string MyRecord { get; set; }
        public string M305 { get; set; }
        public decimal P_time { get; set; }
        public decimal R_Time { get; set; }
        public decimal W_time { get; set; }
        public decimal T_time { get; set; }
        public decimal P_cost { get; set; }
        public bool Bacode { get; set; }
        public bool Spec_Flag { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public int Bol_Times { get; set; }
        public bool NotQty_Flag { get; set; }
        public string Spec_Desc { get; set; }
        public int Seq_No { get; set; }
        public bool Proof_Flag { get; set; }
        public decimal Proof_Time { get; set; }
        public decimal ReOrderProof_Time { get; set; }
    }
}
