//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1252
    {
        public string Line_Code { get; set; }
        public string SL_Code { get; set; }
        public int Seq_No { get; set; }
        public bool Cap_Type { get; set; }
        public decimal Cap_Machine { get; set; }
        public decimal Cap_Worker { get; set; }
        public decimal Cap_WkHours { get; set; }
        public decimal Cap_Prepare { get; set; }
        public decimal Cap_Repair { get; set; }
        public decimal Cap_Eff { get; set; }
        public decimal Cap_UseEff { get; set; }
        public decimal Cap_Theor { get; set; }
        public decimal Cap_Rated { get; set; }
        public decimal Cap_Max { get; set; }
        public bool Ov_Flag { get; set; }
        public bool Key_Flag { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
