//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1260
    {
        public string File_No { get; set; }
        public string Job_No { get; set; }
        public string Ord_Id { get; set; }
        public string toloc_code { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public decimal Qty_Issue { get; set; }
        public string Out_User { get; set; }
        public string In_user { get; set; }
        public bool Approve { get; set; }
        public string Appr_user { get; set; }
        public Nullable<System.DateTime> Appr_date { get; set; }
        public string remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string VhOrd_ID { get; set; }
        public Nullable<int> Cust_Flag { get; set; }
        public string Curr_Code { get; set; }
        public string Vh_No { get; set; }
    }
}
