//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1264
    {
        public string loc_code { get; set; }
        public string file_no { get; set; }
        public int seq_no { get; set; }
        public string tran_type { get; set; }
        public string Ord_Id { get; set; }
        public string wo_no { get; set; }
        public string item_no { get; set; }
        public string job_no { get; set; }
        public decimal qty { get; set; }
        public decimal bal_qty { get; set; }
        public decimal qty_use { get; set; }
        public decimal unit_price { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public string org_file_no { get; set; }
        public int org_seq_no { get; set; }
        public string MID { get; set; }
        public string lot_no { get; set; }
        public int lot_seq_no { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
