//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1271
    {
        public string fa_code { get; set; }
        public int seq_no { get; set; }
        public string att_desc { get; set; }
        public string att_spec { get; set; }
        public string unit { get; set; }
        public decimal qty { get; set; }
        public decimal unit_price { get; set; }
        public decimal amt { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public Nullable<decimal> amt_f { get; set; }
        public Nullable<decimal> amt_net { get; set; }
    }
}
