//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1270
    {
        public string Fa_Code { get; set; }
        public string Item_No { get; set; }
        public string Fa_Descc { get; set; }
        public string Fa_Desce { get; set; }
        public string St_Code1 { get; set; }
        public string St_Code2 { get; set; }
        public string Fa_Model { get; set; }
        public string Fa_Spec { get; set; }
        public string Po_No { get; set; }
        public int Po_Seq_No { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string Loc_Code { get; set; }
        public string Loc_Desc { get; set; }
        public string Fa_User { get; set; }
        public string Loc_Made { get; set; }
        public string Fain_Type { get; set; }
        public string Fa_Type { get; set; }
        public string Fause_Status { get; set; }
        public bool Attch_Device { get; set; }
        public string Org_Curr_Code { get; set; }
        public decimal Curr_Rate { get; set; }
        public decimal Org_Price { get; set; }
        public decimal Org_Amt { get; set; }
        public decimal Attch_Amt { get; set; }
        public decimal Fa_Amt { get; set; }
        public decimal Dep_Amt { get; set; }
        public decimal Net_Amt { get; set; }
        public System.DateTime StUsed_Date { get; set; }
        public int Dep_Period { get; set; }
        public decimal Dep_AllPeriod { get; set; }
        public string Dep_Type { get; set; }
        public bool Dep_All { get; set; }
        public decimal Dep_Rest { get; set; }
        public string Dep_Rest_Type { get; set; }
        public Nullable<System.DateTime> Dep_Rest_Date { get; set; }
        public string Vdr_Code { get; set; }
        public Nullable<System.DateTime> EnlongToDate { get; set; }
        public Nullable<System.DateTime> Repair_Date { get; set; }
        public string Rec_No { get; set; }
        public int Rec_Seq_No { get; set; }
        public string Serialno { get; set; }
        public string Buyer { get; set; }
        public string ReMark { get; set; }
        public string CFNO { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string ZJ_St_Code1 { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string St_Code_Clear { get; set; }
    }
}
