//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1285
    {
        public string Chance_Code { get; set; }
        public string Cust_Namee { get; set; }
        public string Cust_Namec { get; set; }
        public string Off_Add1 { get; set; }
        public string Off_Add2 { get; set; }
        public string Off_Add3 { get; set; }
        public string Off_Add4 { get; set; }
        public string Off_Add1C { get; set; }
        public string Off_Add2C { get; set; }
        public string Off_Add3C { get; set; }
        public string Off_Add4C { get; set; }
        public string Directors { get; set; }
        public string Off_User { get; set; }
        public string Off_Title { get; set; }
        public string Off_Tel { get; set; }
        public string Off_Fax { get; set; }
        public string Off_Email { get; set; }
        public string Off_Http { get; set; }
        public string Sales { get; set; }
        public int Grade { get; set; }
        public string ToCust_Code { get; set; }
        public string Area_Code1 { get; set; }
        public string Area_Code2 { get; set; }
        public string Area_Code3 { get; set; }
        public string Area_Code4 { get; set; }
        public int Status_Code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
