//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1291
    {
        public decimal bat_id { get; set; }
        public string pfile_no { get; set; }
        public int pseq_no { get; set; }
        public string sfile_no { get; set; }
        public int sseq_no { get; set; }
        public string tran_type { get; set; }
        public string ord_id { get; set; }
        public int sseq_no_org { get; set; }
        public string po_no { get; set; }
        public decimal po_seq { get; set; }
        public string vdr_code { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal ttl_qty { get; set; }
        public decimal price { get; set; }
        public string curr_code { get; set; }
        public decimal ex_cost { get; set; }
        public string loc_code { get; set; }
        public bool approve { get; set; }
        public string sysuser { get; set; }
        public System.DateTime sysdate { get; set; }
        public long mid { get; set; }
        public bool export_flag1 { get; set; }
    }
}
