//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1304
    {
        public long AutoID { get; set; }
        public int Period { get; set; }
        public int MGrp_No { get; set; }
        public string Job_No { get; set; }
        public string FrmJob_No { get; set; }
        public int FrmGrp_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public Nullable<System.DateTime> St_Date { get; set; }
        public Nullable<System.DateTime> Fh_Date { get; set; }
    }
}
