//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1303
    {
        public string File_No { get; set; }
        public string Job_No { get; set; }
        public string Item_No { get; set; }
        public decimal qty { get; set; }
        public decimal qty_f { get; set; }
        public string ReMark { get; set; }
        public int Status_Code { get; set; }
        public string File_No1 { get; set; }
        public Nullable<int> Seq_No1 { get; set; }
        public string File_No2 { get; set; }
    }
}
