//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1314
    {
        public string File_No { get; set; }
        public string Ord_Id { get; set; }
        public string Loc_Code { get; set; }
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string Item_No { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_Act { get; set; }
        public decimal Qty_Chk { get; set; }
        public decimal Qty_Just { get; set; }
        public string Remark { get; set; }
        public string Just_User { get; set; }
        public string Chk_User { get; set; }
        public Nullable<System.DateTime> Chk_Date { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string File_No1 { get; set; }
        public decimal Seq_No1 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
