//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1326
    {
        public System.DateTime Tran_Date { get; set; }
        public string Item_No { get; set; }
        public decimal Mat_Cost { get; set; }
        public decimal Prd_Cost { get; set; }
        public decimal Mat_Cost_wh { get; set; }
        public decimal Prd_Cost_wh { get; set; }
        public decimal Mat_Cost_Po { get; set; }
        public decimal Prd_Cost_Po { get; set; }
        public decimal Last_Cost_Po { get; set; }
        public decimal Last_Cost_wh { get; set; }
        public string Po_No { get; set; }
        public Nullable<int> Po_Seq_No { get; set; }
        public Nullable<System.DateTime> Po_Appr_Date { get; set; }
        public decimal Last_Cost_Po_Ex { get; set; }
        public string Last_Cost_Po_Curr { get; set; }
        public string Rec_No { get; set; }
        public Nullable<int> Rec_Seq_No { get; set; }
        public Nullable<System.DateTime> Rec_Appr_Date { get; set; }
        public decimal Last_Cost_wh_Ex { get; set; }
        public string Last_Cost_wh_Curr { get; set; }
        public decimal Std_Cost { get; set; }
        public decimal Avg_Cost { get; set; }
        public decimal Yield { get; set; }
        public decimal S_Cost { get; set; }
        public decimal B_Cost { get; set; }
        public decimal last_cost_po_a { get; set; }
        public decimal last_cost_wh_a { get; set; }
        public string Sysuser { get; set; }
        public System.DateTime Sysdate { get; set; }
        public string Remark { get; set; }
    }
}
