//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1323
    {
        public string Ecn_No { get; set; }
        public int Seq_No { get; set; }
        public string M99 { get; set; }
        public string Act_Flag { get; set; }
        public string Ecn_Flag { get; set; }
        public string Item_No { get; set; }
        public string Item_Field { get; set; }
        public string Field_Desc { get; set; }
        public string FrmValue { get; set; }
        public string ToValue { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
