//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1336
    {
        public string Amt_Code { get; set; }
        public string Amt_Descc { get; set; }
        public string Amt_Desce { get; set; }
        public string M154 { get; set; }
        public bool Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool sale_flag { get; set; }
        public bool pur_flag { get; set; }
        public bool Export_Flag { get; set; }
    }
}
