//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1347
    {
        public int AutoID { get; set; }
        public string ToTable { get; set; }
        public string ToField { get; set; }
        public string ToWField { get; set; }
        public string FmTable { get; set; }
        public string FmField { get; set; }
        public string ToTable_desc { get; set; }
        public string ToField_Desc { get; set; }
        public string ToWField_Desc { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
