//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1346
    {
        public string ParentItem { get; set; }
        public string SonItem { get; set; }
        public string ItemModel { get; set; }
        public string ItemSize { get; set; }
        public string ItemColor { get; set; }
        public bool Not_Flag { get; set; }
        public string ItemV { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
