//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1358
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public int Acc_Year { get; set; }
        public int Acc_Mon { get; set; }
        public string Cc_Code { get; set; }
        public string Line_Code { get; set; }
        public string Active_Code { get; set; }
        public decimal Qty_Base { get; set; }
        public decimal U_Cost { get; set; }
        public decimal T_Cost { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
