//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1351
    {
        public string Rule_Code { get; set; }
        public string Vdr_Code { get; set; }
        public string Plate_TypeD { get; set; }
        public string PPartCode { get; set; }
        public decimal Unit_Price { get; set; }
        public string Curr_Code { get; set; }
        public int MaxCnNo { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public int Status_Code { get; set; }
        public Nullable<System.DateTime> Eff_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
