//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1356
    {
        public string Line_Code { get; set; }
        public string Active_Type { get; set; }
        public string Cal_Code { get; set; }
        public decimal Unit_Price { get; set; }
        public string M220 { get; set; }
        public string M216 { get; set; }
        public string M224 { get; set; }
        public int Flag1 { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
