//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1366
    {
        public long AutoId { get; set; }
        public string so_no { get; set; }
        public decimal seq_no { get; set; }
        public string job_no { get; set; }
        public string lot_no { get; set; }
        public int Lot_Seq_No { get; set; }
        public int Ord_Type { get; set; }
        public int IO_Flag { get; set; }
        public int IO_Code { get; set; }
        public string Line_Code { get; set; }
        public int Line_Seq_No { get; set; }
        public decimal Qty_JO { get; set; }
        public decimal Qty_Mo { get; set; }
        public decimal T_Qty_Per { get; set; }
        public int TTL_Flag { get; set; }
        public int status_code { get; set; }
        public Nullable<System.DateTime> pass_date { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public int Ord_Flag1 { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
