//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1364
    {
        public int Period { get; set; }
        public string Line_Code1 { get; set; }
        public string Item_Class1 { get; set; }
        public string Line_Class { get; set; }
        public int Line_Seq_No { get; set; }
        public int IO_Flag { get; set; }
        public int IO_Code { get; set; }
        public string FLine_Code { get; set; }
        public int FLine_Seq_No { get; set; }
        public string TLine_Code { get; set; }
        public int TLine_Seq_No { get; set; }
        public decimal Qty_JO { get; set; }
        public decimal Qty_Mo { get; set; }
        public int MLLine_Flag { get; set; }
        public int MNLine_Flag { get; set; }
        public int Ord_Flag1 { get; set; }
    }
}
