//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1365
    {
        public long AutoID { get; set; }
        public int Period { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public int Ord_Type { get; set; }
        public string job_no { get; set; }
        public string lot_no { get; set; }
        public int Lot_Seq_No { get; set; }
        public int IO_Flag { get; set; }
        public int IO_Code { get; set; }
        public string FLine_Code { get; set; }
        public int FLine_Seq_No { get; set; }
        public string TLine_Code { get; set; }
        public int TLine_Seq_No { get; set; }
        public decimal Qty_JO { get; set; }
        public decimal Qty_Mo { get; set; }
        public decimal T_Qty_Per { get; set; }
        public int Cal_Flag { get; set; }
        public Nullable<bool> MLLine_Flag { get; set; }
        public Nullable<bool> MNLine_Flag { get; set; }
        public Nullable<decimal> TLead_Time { get; set; }
        public Nullable<decimal> Lead_Time { get; set; }
        public Nullable<System.DateTime> In_Date { get; set; }
        public Nullable<System.DateTime> Pass_Date { get; set; }
        public Nullable<int> Ord_Flag1 { get; set; }
    }
}
