//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1369
    {
        public int Period { get; set; }
        public int I_Seq_No { get; set; }
        public string I_Desc { get; set; }
        public int P_Seq_No { get; set; }
        public string P_Desc { get; set; }
        public string Loc_Code { get; set; }
        public string Item_Class1 { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty1 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
