//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1388
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public int SSeq_No { get; set; }
        public decimal qty { get; set; }
        public decimal qty_sd { get; set; }
        public decimal Dn_qty { get; set; }
        public decimal Dn_qty_sd { get; set; }
        public Nullable<System.DateTime> rtd { get; set; }
        public Nullable<System.DateTime> ftd { get; set; }
        public string cust_po { get; set; }
        public string CPo_Seq_No { get; set; }
        public Nullable<System.DateTime> CustPo_date { get; set; }
        public Nullable<System.DateTime> Fax_date { get; set; }
        public int status_code { get; set; }
        public string status_user { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string pt_no { get; set; }
        public decimal Qty_Pt { get; set; }
        public string cust_code { get; set; }
        public string SysRemark { get; set; }
        public Nullable<System.DateTime> Tocust_Date { get; set; }
        public Nullable<System.DateTime> Tocust_Date1 { get; set; }
        public string M45 { get; set; }
        public Nullable<System.DateTime> Ftd_Pmc { get; set; }
        public Nullable<System.DateTime> Cal_Date { get; set; }
        public decimal Qty_Rej { get; set; }
        public string M77 { get; set; }
        public string Addr_Code_Acc { get; set; }
        public string Addr_Code_Ship { get; set; }
        public string add_acc1 { get; set; }
        public string add_acc2 { get; set; }
        public string add_acc3 { get; set; }
        public string add_acc4 { get; set; }
        public string add_ship1 { get; set; }
        public string add_ship2 { get; set; }
        public string add_ship3 { get; set; }
        public string add_ship4 { get; set; }
    }
}
