//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1390
    {
        public string parentitem { get; set; }
        public string item_no { get; set; }
        public string item_type { get; set; }
        public string uom { get; set; }
        public Nullable<decimal> qty_per { get; set; }
        public Nullable<decimal> yield { get; set; }
        public Nullable<decimal> yield_total { get; set; }
        public Nullable<decimal> use_total { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> cost_total { get; set; }
        public Nullable<decimal> cost_unit { get; set; }
        public decimal sort { get; set; }
    }
}
