//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1407
    {
        public string Sln_No { get; set; }
        public string Rpt_Field { get; set; }
        public int Seq_No { get; set; }
        public bool Out_Flag { get; set; }
        public bool Cond_Flag { get; set; }
        public bool Sum_Flag { get; set; }
        public string Sum_Str { get; set; }
        public bool CondRef_Flag { get; set; }
        public int Sort_Flag { get; set; }
        public string Sort_Desc { get; set; }
        public bool Span_Flag { get; set; }
        public string Alias_Desc { get; set; }
        public string Cond_Def { get; set; }
        public bool Split_Sheet { get; set; }
        public Nullable<bool> Line_Flag { get; set; }
        public Nullable<bool> Color_Flag { get; set; }
        public Nullable<int> Color_R { get; set; }
        public Nullable<int> Color_G { get; set; }
        public Nullable<int> Color_B { get; set; }
        public string Cond_Add { get; set; }
        public Nullable<bool> SubTotal_Flag { get; set; }
        public Nullable<bool> SubTotal_Sum { get; set; }
        public Nullable<bool> SelectOut_Flag { get; set; }
        public Nullable<bool> RptCond_Flag { get; set; }
        public Nullable<bool> UserWrite_Flag { get; set; }
        public string frm_Field { get; set; }
        public string frmField_Desc { get; set; }
        public bool removeEmpty_Flag { get; set; }
        public string ToDetail_Where { get; set; }
        public string ToDetail_RptNo { get; set; }
    }
}
