//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1405
    {
        public string Rpt_Code { get; set; }
        public string Rpt_Field { get; set; }
        public string Frm_Table { get; set; }
        public string Frm_Field { get; set; }
        public string FrmField_Desc { get; set; }
        public string Field_Type { get; set; }
        public int Seq_No { get; set; }
        public int SSeq_No { get; set; }
        public bool Price_Flag { get; set; }
        public bool Esp_Flag { get; set; }
        public string Esp_Code { get; set; }
        public string Ref_Table { get; set; }
        public string Ref_TableDesc { get; set; }
        public string Ref_Field { get; set; }
        public string Ref_FieldDesc { get; set; }
        public string Ref_FieldName { get; set; }
        public string Ref_FieldNameDesc { get; set; }
        public string RefCond_Field { get; set; }
        public string RefCond_Value { get; set; }
        public string RefCond_Oper { get; set; }
        public bool Field_AfterCal { get; set; }
        public bool Total_Flag { get; set; }
        public bool CondPara_Flag { get; set; }
        public Nullable<int> DecimalPlaces { get; set; }
    }
}
