//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1406
    {
        public string Sln_No { get; set; }
        public string Rpt_Code { get; set; }
        public string Sln_Desc { get; set; }
        public string M_Key1 { get; set; }
        public string M_Key2 { get; set; }
        public bool Distinct_Flag { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Sln_Head { get; set; }
        public string Sln_Foot { get; set; }
        public string T_Code { get; set; }
        public bool Field_Flag { get; set; }
        public int Left_M { get; set; }
        public int Right_M { get; set; }
        public int Top_M { get; set; }
        public int Bottom_M { get; set; }
        public int Page_Align { get; set; }
        public int Page_Orientation { get; set; }
    }
}
