//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1402
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public int SSeq_No { get; set; }
        public string Job_no { get; set; }
        public decimal Mps_Seq_no { get; set; }
        public int line_class_seq { get; set; }
        public string Line_Code { get; set; }
        public int IO_Flag { get; set; }
        public decimal Qty_Pass { get; set; }
        public decimal Qty_Scrap { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public decimal Qty_F { get; set; }
        public int Flag1 { get; set; }
        public int status_code { get; set; }
        public string status_User { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public string Remark { get; set; }
        public string SysRemark { get; set; }
        public string FrmLine_Code { get; set; }
        public string ToLine_Code { get; set; }
        public decimal Qty_Repair { get; set; }
        public decimal Qty_ToLoc { get; set; }
        public string ToLoc_Code { get; set; }
        public string sysuser { get; set; }
        public System.DateTime sysdate { get; set; }
    }
}
