//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1403
    {
        public string PFile_No { get; set; }
        public int PSeq_No { get; set; }
        public string SFile_No { get; set; }
        public int SPSeq_No { get; set; }
        public int SSeq_No { get; set; }
        public decimal Qty { get; set; }
    }
}
