//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1411
    {
        public string Vh_No { get; set; }
        public int Seq_No { get; set; }
        public string Remark { get; set; }
        public string st_code { get; set; }
        public decimal Amt_Debit { get; set; }
        public decimal Amt_Credit { get; set; }
        public decimal Amt_Debit1 { get; set; }
        public decimal Amt_Credit1 { get; set; }
        public string Org_Vh_No { get; set; }
        public int Org_Seq_No { get; set; }
        public decimal Org_Amt { get; set; }
        public decimal Amt_UnPay { get; set; }
        public decimal Amt_F { get; set; }
        public decimal Qty { get; set; }
        public decimal Unit_Price { get; set; }
        public string Inv_No { get; set; }
        public int F_Seq_No { get; set; }
        public string Po_No { get; set; }
        public int Po_Seq_No { get; set; }
        public string Ex_Curr_Code { get; set; }
        public decimal Ex_Rate { get; set; }
        public string Dn_No { get; set; }
        public bool Cod_Flag { get; set; }
        public int Status_Code { get; set; }
        public string File_No1 { get; set; }
        public string Line_Code { get; set; }
        public string Item_No { get; set; }
        public string Job_No { get; set; }
        public string Item_Type { get; set; }
        public string M216 { get; set; }
        public string St_Code2 { get; set; }
        public string Active_Code { get; set; }
    }
}
