//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1410
    {
        public int Acc_Year { get; set; }
        public int Acc_Month { get; set; }
        public string Vh_No { get; set; }
        public Nullable<System.DateTime> Tran_Date { get; set; }
        public string File_Type { get; set; }
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string Cust_Code { get; set; }
        public string Curr_Code { get; set; }
        public int Ord_Cnt { get; set; }
        public string Ord_Id { get; set; }
        public decimal T_Amt_Debit { get; set; }
        public decimal T_Amt_Credit { get; set; }
        public decimal T_Amt_Debit1 { get; set; }
        public decimal T_Amt_Credit1 { get; set; }
        public bool Approve { get; set; }
        public string Appr_user { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string Checker { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
        public bool Pay_Flag { get; set; }
        public string Cashier { get; set; }
        public Nullable<System.DateTime> Cashier_Date { get; set; }
        public bool Pasted { get; set; }
        public string Past_User { get; set; }
        public Nullable<System.DateTime> Past_Date { get; set; }
        public string Ref_No { get; set; }
        public bool Hand_Flag { get; set; }
        public bool Curr_Flag { get; set; }
        public string M220 { get; set; }
        public int status_code { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
    }
}
