//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1422
    {
        public string Rpt_Code { get; set; }
        public int Seq_No { get; set; }
        public int SSeq_No { get; set; }
        public int Item_Seq { get; set; }
        public string St_Code { get; set; }
        public string Oper_Char { get; set; }
    }
}
