//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1424
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string Item_Code1 { get; set; }
        public string Item_Code2 { get; set; }
        public string Item_Desc1 { get; set; }
        public string Item_Desc2 { get; set; }
        public string Item_Code3 { get; set; }
        public string Item_Code4 { get; set; }
        public string Item_Code5 { get; set; }
        public string Item_Code6 { get; set; }
        public string Item_Code7 { get; set; }
        public string Remark { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
