//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1421
    {
        public string Rpt_Code { get; set; }
        public int Seq_No { get; set; }
        public string Item1 { get; set; }
        public string Item2 { get; set; }
        public string Item3 { get; set; }
        public string Item3_ID { get; set; }
        public string Item4_ID { get; set; }
        public string Item4 { get; set; }
        public bool Flag1 { get; set; }
        public bool Flag2 { get; set; }
        public string Item { get; set; }
        public string Item5 { get; set; }
        public string Item5_Id { get; set; }
        public string Item6 { get; set; }
        public string Item6_Id { get; set; }
        public bool VhData_Flag { get; set; }
    }
}
