//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1467
    {
        public string So_No { get; set; }
        public string M273 { get; set; }
        public decimal Qty { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Remark { get; set; }
    }
}
