//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1462
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string StrPara1 { get; set; }
        public string StrPara2 { get; set; }
        public string StrPara3 { get; set; }
        public string StrPara4 { get; set; }
        public string StrPara5 { get; set; }
        public string StrPara6 { get; set; }
        public string StrPara7 { get; set; }
        public string StrPara8 { get; set; }
        public string StrPara9 { get; set; }
        public string StrPara10 { get; set; }
        public string StrPara11 { get; set; }
        public string StrPara12 { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_DN { get; set; }
        public decimal Unit_Price { get; set; }
        public int Status_Code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
    }
}
