//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1468
    {
        public string Pd_No { get; set; }
        public string Cust_Code { get; set; }
        public Nullable<System.DateTime> VC_Date { get; set; }
        public string CSerial { get; set; }
        public string SerialCode { get; set; }
        public string User1 { get; set; }
        public Nullable<System.DateTime> MIssue_Date { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Qty1 { get; set; }
        public Nullable<decimal> Qty2 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string M276 { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> CtFlag { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<bool> LdFlag { get; set; }
        public string SysUser { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public string OkPaper { get; set; }
    }
}
