//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1463
    {
        public string So_No { get; set; }
        public string strPara1 { get; set; }
        public string strPara2 { get; set; }
        public string strPara3 { get; set; }
        public string strPara4 { get; set; }
        public string strPara5 { get; set; }
        public string strPara6 { get; set; }
        public string strPara7 { get; set; }
        public string strPara8 { get; set; }
        public string strPara9 { get; set; }
        public string strPara10 { get; set; }
        public string strPara11 { get; set; }
        public string strPara12 { get; set; }
        public string strPara13 { get; set; }
        public string strPara14 { get; set; }
        public string strPara15 { get; set; }
        public string strPara16 { get; set; }
        public string strPara17 { get; set; }
        public string strPara18 { get; set; }
        public string strPara19 { get; set; }
        public string strPara20 { get; set; }
        public string strPara21 { get; set; }
        public string strPara22 { get; set; }
        public string strPara23 { get; set; }
        public string strPara24 { get; set; }
        public string strPara25 { get; set; }
        public string strPara26 { get; set; }
        public string strPara27 { get; set; }
        public string strPara28 { get; set; }
        public string strPara29 { get; set; }
        public string strPara30 { get; set; }
    }
}
