//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1460
    {
        public string So_No { get; set; }
        public string Ord_Type { get; set; }
        public string Ord_Id { get; set; }
        public string Sales { get; set; }
        public string Cust_Code { get; set; }
        public string Cust_Add1 { get; set; }
        public string Cust_Add2 { get; set; }
        public string Cust_Add3 { get; set; }
        public string Cust_Add4 { get; set; }
        public string Contact { get; set; }
        public string Title { get; set; }
        public string Item_SoType { get; set; }
        public string Pay_Code { get; set; }
        public string Ship_Code { get; set; }
        public string Sale_Code { get; set; }
        public bool Export { get; set; }
        public string Addr_code { get; set; }
        public string Curr_Code { get; set; }
        public decimal Curr_Rate { get; set; }
        public bool Tax_Add { get; set; }
        public string Tax_Order { get; set; }
        public decimal Qty_Perh { get; set; }
        public decimal Qty_PerL { get; set; }
        public decimal Deposit { get; set; }
        public decimal Insurance { get; set; }
        public decimal Att_Amt { get; set; }
        public string Att_Amt_Desc { get; set; }
        public decimal T_Discount { get; set; }
        public decimal T_Damt { get; set; }
        public decimal Net_amt { get; set; }
        public decimal Ttl_amt { get; set; }
        public string Ourmodel { get; set; }
        public string Spec6 { get; set; }
        public string Spec1 { get; set; }
        public bool Mat_Plan { get; set; }
        public int Printver { get; set; }
        public string Att1_Amt_Desc { get; set; }
        public string sp_no { get; set; }
        public string Ship_Add1 { get; set; }
        public string Ship_Add2 { get; set; }
        public string Ship_Add3 { get; set; }
        public string Ship_Add4 { get; set; }
        public string Rela_No { get; set; }
        public int MaxYTimes { get; set; }
        public string Woremark { get; set; }
        public string Remark { get; set; }
        public decimal Cn_Max { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Last_User { get; set; }
        public System.DateTime Last_Date { get; set; }
        public string StrPara1 { get; set; }
        public bool Ml_Flag { get; set; }
        public bool Bol_Flag { get; set; }
        public string Item_Class { get; set; }
        public string StrPara2 { get; set; }
        public string StrPara3 { get; set; }
        public string StrPara4 { get; set; }
        public bool Size_Flag { get; set; }
        public string StrPara5 { get; set; }
        public decimal Qty1 { get; set; }
        public string StrPara6 { get; set; }
        public string StrPara7 { get; set; }
        public string StrPara8 { get; set; }
        public string StrPara9 { get; set; }
        public string StrPara10 { get; set; }
        public string StrPara11 { get; set; }
        public string StrPara12 { get; set; }
        public string StrPara13 { get; set; }
        public string StrPara14 { get; set; }
        public string StrPara15 { get; set; }
        public Nullable<System.DateTime> St_Date { get; set; }
        public Nullable<System.DateTime> FH_Date { get; set; }
        public string User1 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string User2 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string User3 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public string User4 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public string User5 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public string User6 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public string User7 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public string User8 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public string User9 { get; set; }
        public Nullable<System.DateTime> Date9 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> Date10 { get; set; }
        public string Path1 { get; set; }
        public bool Flag1 { get; set; }
        public int Status_Code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public Nullable<decimal> FbQty { get; set; }
        public string M202 { get; set; }
        public Nullable<System.DateTime> Raw_Date { get; set; }
        public Nullable<System.DateTime> Color_Date { get; set; }
        public string so_no1 { get; set; }
        public string CustRemark { get; set; }
        public Nullable<System.DateTime> Color_WDate { get; set; }
        public Nullable<System.DateTime> Cust_Date { get; set; }
        public Nullable<decimal> Cust_Qty { get; set; }
        public Nullable<System.DateTime> Cust_SBDate { get; set; }
        public Nullable<decimal> Cust_SBQty { get; set; }
        public Nullable<System.DateTime> Cust_JGBDate { get; set; }
        public Nullable<decimal> Cust_JGBQty { get; set; }
        public Nullable<System.DateTime> Cust_CBDate { get; set; }
        public Nullable<decimal> Cust_CBQty { get; set; }
        public Nullable<System.DateTime> Cust_TZDate { get; set; }
        public Nullable<decimal> Cust_TZQty { get; set; }
        public Nullable<System.DateTime> Cust_YJCDate { get; set; }
        public Nullable<decimal> Cust_YJCQty { get; set; }
        public string PJ_Remark { get; set; }
        public Nullable<int> flag2 { get; set; }
        public Nullable<int> flag3 { get; set; }
        public string GZ_Remark { get; set; }
        public Nullable<System.DateTime> FB_Date { get; set; }
    }
}
