//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1476
    {
        public string So_No { get; set; }
        public string Sp_Ver { get; set; }
        public string Sp_Type { get; set; }
        public Nullable<bool> New_Flag { get; set; }
        public Nullable<bool> Tooling_Flag { get; set; }
        public Nullable<System.DateTime> KnowOrder_Date { get; set; }
        public Nullable<System.DateTime> StOrder_Date { get; set; }
        public Nullable<bool> ComeSample_Flag { get; set; }
        public string Design_User { get; set; }
        public Nullable<System.DateTime> Issue_FinDate { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool PicConfirm_Flag { get; set; }
    }
}
