//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1471
    {
        public string Item_No { get; set; }
        public string Cust_Code { get; set; }
        public decimal Unit_Price { get; set; }
        public string Spec101 { get; set; }
        public string Spec102 { get; set; }
        public string Spec103 { get; set; }
        public string Spec104 { get; set; }
        public string Spec105 { get; set; }
        public string Spec106 { get; set; }
        public string Spec107 { get; set; }
        public string Spec108 { get; set; }
        public string Spec109 { get; set; }
        public string Spec110 { get; set; }
        public string Spec111 { get; set; }
        public string Spec112 { get; set; }
        public string Spec113 { get; set; }
        public string Spec114 { get; set; }
        public string Spec115 { get; set; }
        public string Spec116 { get; set; }
        public string Spec117 { get; set; }
        public string Spec118 { get; set; }
        public string Spec119 { get; set; }
        public string Spec120 { get; set; }
        public string Spec121 { get; set; }
        public string Spec122 { get; set; }
        public string Spec123 { get; set; }
        public string Spec124 { get; set; }
        public string Spec125 { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string last_user { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
        public bool appr_flag { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
    }
}
