//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1487
    {
        public string PL_No { get; set; }
        public Nullable<int> Cn_No { get; set; }
        public int Seq_No { get; set; }
        public string So_No { get; set; }
        public Nullable<decimal> So_Seq_No { get; set; }
        public int So_SSeq_No { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> Qty_Sd { get; set; }
        public string Qty_Remark1 { get; set; }
        public string Qty_Remark2 { get; set; }
        public string Item_No { get; set; }
        public string Item_Type { get; set; }
        public string Your_Size { get; set; }
        public string Last_Size { get; set; }
        public string Your_Model { get; set; }
        public string Last_Model { get; set; }
        public string Your_Color { get; set; }
        public string Your_PoNo { get; set; }
        public string Last_PoNo { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Qty_Per { get; set; }
        public string FrmCust_Code { get; set; }
        public string Item_No1 { get; set; }
        public string Item_Desc1 { get; set; }
        public Nullable<decimal> Qty1 { get; set; }
        public string Item_No2 { get; set; }
        public string Item_Desc2 { get; set; }
        public Nullable<decimal> Qty2 { get; set; }
        public string M281 { get; set; }
        public Nullable<decimal> Qty1_Per { get; set; }
        public Nullable<decimal> Qty2_Per { get; set; }
    }
}
