//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1491
    {
        public string PI_No { get; set; }
        public string Version { get; set; }
        public System.DateTime Ver_Date { get; set; }
        public string Addr_Code { get; set; }
        public string Addr_Desc1 { get; set; }
        public string Addr_Desc2 { get; set; }
        public string Addr_Desc3 { get; set; }
        public string Addr_Desc4 { get; set; }
        public string Ref { get; set; }
        public string Remark { get; set; }
        public string Spec1 { get; set; }
        public string Spec2 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<int> Dec1 { get; set; }
        public Nullable<int> Dec2 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
