//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1502
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string Job_No { get; set; }
        public string ParentItem { get; set; }
        public string SonItem { get; set; }
        public decimal Qty_Per { get; set; }
        public int M_Ver { get; set; }
        public int P_Ver { get; set; }
        public string Remark { get; set; }
        public bool Approve { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public Nullable<System.DateTime> M_STEffdate { get; set; }
        public Nullable<System.DateTime> M_EDEffdate { get; set; }
        public string Appr_User { get; set; }
        public string SysUser { get; set; }
        public bool Part_Type { get; set; }
        public string MyRecord { get; set; }
        public decimal Per_Cost { get; set; }
        public int Bom_Type { get; set; }
        public int Status_Code { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Ecn_No { get; set; }
        public string PpItem_No { get; set; }
        public bool LotCard_Point { get; set; }
        public bool Y_Flag { get; set; }
        public bool Y1_Flag { get; set; }
        public bool Y2_Flag { get; set; }
        public bool Y3_Flag { get; set; }
        public bool Y4_Flag { get; set; }
        public bool Y5_Flag { get; set; }
        public bool Y6_Flag { get; set; }
        public int YCT_Flag { get; set; }
        public string Line_Code { get; set; }
    }
}
