//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1511
    {
        public string ORD_ID { get; set; }
        public int SEQ_NO { get; set; }
        public string Seq_Desc { get; set; }
        public bool Key_Flag { get; set; }
        public bool UnAppr_Flag { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string M_SKey { get; set; }
    }
}
