//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1523
    {
        public string SLN_No { get; set; }
        public string Pitem_No { get; set; }
        public string Sitem_No { get; set; }
        public string Sitem_Desc { get; set; }
        public bool V_Flag { get; set; }
        public int Seq_No { get; set; }
        public string formula { get; set; }
        public bool Material_Flag { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Spec1 { get; set; }
        public string Spec2 { get; set; }
        public string Spec3 { get; set; }
        public string Spec4 { get; set; }
        public string Spec5 { get; set; }
        public string Spec6 { get; set; }
        public string Spec7 { get; set; }
        public string Spec8 { get; set; }
        public string Spec9 { get; set; }
        public string Spec10 { get; set; }
        public bool formula_Flag { get; set; }
    }
}
