//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1520
    {
        public string Cust_Code { get; set; }
        public string CItem_No { get; set; }
        public string Curr_Code { get; set; }
        public decimal Unit_Price { get; set; }
        public string pItem_Code { get; set; }
        public string SPEC1 { get; set; }
        public string SPEC2 { get; set; }
        public string SPEC3 { get; set; }
        public string SPEC4 { get; set; }
        public string SPEC5 { get; set; }
        public string SPEC6 { get; set; }
        public string SPEC7 { get; set; }
        public string SPEC8 { get; set; }
        public string SPEC9 { get; set; }
        public string SPEC10 { get; set; }
        public Nullable<decimal> SPEC11 { get; set; }
        public Nullable<decimal> SPEC12 { get; set; }
        public Nullable<decimal> SPEC13 { get; set; }
        public Nullable<decimal> SPEC14 { get; set; }
        public Nullable<decimal> SPEC15 { get; set; }
        public Nullable<System.DateTime> SPEC16 { get; set; }
        public Nullable<System.DateTime> SPEC17 { get; set; }
        public Nullable<System.DateTime> SPEC18 { get; set; }
        public Nullable<System.DateTime> SPEC19 { get; set; }
        public Nullable<System.DateTime> SPEC20 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool Appr_Flag { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string sysremark { get; set; }
    }
}
