//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1529
    {
        public int AutoID { get; set; }
        public string CItem_No { get; set; }
        public string Cust_Code { get; set; }
        public string Item_No { get; set; }
        public string SPEC100 { get; set; }
        public string Pitem_Code { get; set; }
        public string Sitem_Code { get; set; }
        public int SSeq_No { get; set; }
        public string Item_No1 { get; set; }
        public string Item_V_Code { get; set; }
        public string ITEM_V_Descc { get; set; }
        public string ITEM_V_Desce { get; set; }
        public decimal Price_Diff { get; set; }
        public bool RELA_FLAG { get; set; }
        public int RELA_SEQ_NO { get; set; }
        public int SEQ_NO { get; set; }
        public string SITEM_GRP { get; set; }
        public string Sitem_desc { get; set; }
        public string Sitem_desce { get; set; }
        public bool Item_Flag { get; set; }
        public int Pseq_no { get; set; }
        public string SPEC1 { get; set; }
        public string SPEC2 { get; set; }
        public string SPEC3 { get; set; }
        public string SPEC4 { get; set; }
        public string SPEC5 { get; set; }
        public string Remark { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal Unit_Cost { get; set; }
        public string ColorGrp_Code { get; set; }
    }
}
