//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1525
    {
        public string OurModel { get; set; }
        public string Sitem_No { get; set; }
        public int Seq_No { get; set; }
        public decimal AMT { get; set; }
        public string Item_No { get; set; }
        public string Item_Desc { get; set; }
        public bool Material_Flag { get; set; }
        public string Remark { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool Appr_Flag { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string SPEC1 { get; set; }
        public string SPEC2 { get; set; }
        public string SPEC3 { get; set; }
        public string SPEC4 { get; set; }
        public string SPEC5 { get; set; }
        public Nullable<decimal> SPEC6 { get; set; }
        public Nullable<decimal> SPEC7 { get; set; }
        public Nullable<decimal> SPEC8 { get; set; }
        public Nullable<decimal> SPEC9 { get; set; }
        public Nullable<decimal> SPEC10 { get; set; }
    }
}
