//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1526
    {
        public string rec_no { get; set; }
        public int rec_seq { get; set; }
        public string PoCn_No { get; set; }
        public string Po_No { get; set; }
        public int Po_Seq { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
