//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1532
    {
        public string Color_Code { get; set; }
        public string Color_Descc { get; set; }
        public string Color_Desce { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string LastUser { get; set; }
        public System.DateTime LastDate { get; set; }
        public string B019A { get; set; }
        public string short_desc { get; set; }
        public bool export_flag { get; set; }
        public bool export_flag1 { get; set; }
    }
}
