//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1531
    {
        public int Acc_Year { get; set; }
        public int Acc_Month { get; set; }
        public string Rpt_Code { get; set; }
        public int Seq_No { get; set; }
        public int Flag1 { get; set; }
        public string Item1 { get; set; }
        public string Item2 { get; set; }
        public string Item3 { get; set; }
        public string Item4 { get; set; }
        public bool Flag2 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Page_Head { get; set; }
        public string Page_Foot { get; set; }
    }
}
