//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1530
    {
        public string File_No { get; set; }
        public string Item_Code { get; set; }
        public string Mkey { get; set; }
        public string Mkey_Desc { get; set; }
        public string Frm_Name { get; set; }
        public string Active_Name { get; set; }
        public bool Visible_Flag { get; set; }
        public bool Upt_Flag { get; set; }
        public string DF_V { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string L3 { get; set; }
        public string L4 { get; set; }
        public string L5 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
