//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1535
    {
        public int Period { get; set; }
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string St_Code { get; set; }
        public decimal Amt_Total_In { get; set; }
        public decimal Amt_In { get; set; }
        public decimal Amt_In_Other { get; set; }
        public decimal Amt_Bal { get; set; }
        public decimal Amt_Per { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal amt_out { get; set; }
        public string M220 { get; set; }
    }
}
