//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1545
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string Tran_Type { get; set; }
        public string Acc_Grp { get; set; }
        public string F_Desc { get; set; }
        public decimal AMT { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Org_File_No { get; set; }
        public decimal Tax_Rate { get; set; }
        public bool TaxRate_Flag { get; set; }
        public string TaxSt_Code { get; set; }
        public string Org_Code { get; set; }
        public string So_No { get; set; }
        public Nullable<int> So_Seq_No { get; set; }
        public string Item_Model { get; set; }
        public string Item_Size { get; set; }
        public string item_Color { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public string check_no { get; set; }
        public string remark2 { get; set; }
    }
}
