//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1541_20120711
    {
        public long AutoID { get; set; }
        public int MRow { get; set; }
        public int MCol { get; set; }
        public int L_No { get; set; }
        public int L_Seq_No { get; set; }
        public bool MH_Flag { get; set; }
        public int MSheet { get; set; }
        public string L_Desc { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Ctrls_No { get; set; }
    }
}
