//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1546
    {
        public string Rec_No { get; set; }
        public int Rec_Seq { get; set; }
        public string Amt_Code { get; set; }
        public decimal Amt { get; set; }
        public decimal Amt2 { get; set; }
    }
}
