//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1544
    {
        public string File_No { get; set; }
        public string Ord_ID { get; set; }
        public string Ptr_Code { get; set; }
        public int Flag1 { get; set; }
        public string Curr_Code { get; set; }
        public decimal Curr_Rate { get; set; }
        public decimal TTL_AMT { get; set; }
        public string Ptr_Add1 { get; set; }
        public string Ptr_Add2 { get; set; }
        public string Ptr_Add3 { get; set; }
        public string Ptr_Add4 { get; set; }
        public string Ptr_Fax { get; set; }
        public string Ptr_Tel { get; set; }
        public string ptr_ConTact { get; set; }
        public string Confirm_User { get; set; }
        public string Remark { get; set; }
        public bool Approve { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string Vh_No { get; set; }
        public string VhOrd_ID { get; set; }
    }
}
