//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1552
    {
        public string Sln_No { get; set; }
        public string Sln_Descc { get; set; }
        public string Page_Head { get; set; }
        public string Page_Foot { get; set; }
        public string Filter_Code { get; set; }
        public string T_Code { get; set; }
        public string Menu_Key { get; set; }
        public string Proc_Name { get; set; }
        public Nullable<int> D_Table_Seq1 { get; set; }
        public Nullable<int> D_Table_Seq2 { get; set; }
        public Nullable<int> D_Table_Seq3 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
