//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1565
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string Line_Class { get; set; }
        public string Item_Type { get; set; }
        public string Line_Desc { get; set; }
        public int mPart_Flag { get; set; }
        public System.DateTime In_Date { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Pmc_Remark { get; set; }
        public int delay_type { get; set; }
    }
}
