//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1568
    {
        public string rec_no { get; set; }
        public int seq_no { get; set; }
        public string so_no { get; set; }
        public Nullable<decimal> so_seq_no { get; set; }
        public string pl_no { get; set; }
        public Nullable<int> pl_seq_no { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal qty_fgs { get; set; }
        public decimal qty_unfgs { get; set; }
        public bool iqc { get; set; }
        public string iqc_no { get; set; }
        public int MaxIqcTimes { get; set; }
        public string File_No1 { get; set; }
        public string File_No2 { get; set; }
        public string Tran_Type { get; set; }
        public string Remark { get; set; }
        public string SysRemark { get; set; }
        public string D048B { get; set; }
        public Nullable<decimal> Amt { get; set; }
    }
}
