//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1569
    {
        public string File_no { get; set; }
        public string Ord_id { get; set; }
        public System.DateTime Tran_date { get; set; }
        public string iqcloc_code { get; set; }
        public string toloc_code_fgs { get; set; }
        public string toloc_code_unfgs { get; set; }
        public string toloc_code_unfgs1 { get; set; }
        public string toloc_code_loss { get; set; }
        public string iqc_user { get; set; }
        public Nullable<bool> Approve { get; set; }
        public string Appr_user { get; set; }
        public Nullable<System.DateTime> Appr_date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Fgs_User { get; set; }
        public string UnFgs_User { get; set; }
        public string UnFgs1_User { get; set; }
        public string Loss_User { get; set; }
        public string vh_no { get; set; }
        public string vh_no1 { get; set; }
        public string vh_no2 { get; set; }
        public bool Check_Flag { get; set; }
        public string Check_User { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
    }
}
