//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1570
    {
        public string File_no { get; set; }
        public string pfile_no { get; set; }
        public Nullable<int> pseq_no { get; set; }
        public string so_no { get; set; }
        public Nullable<decimal> so_seq { get; set; }
        public string item_no { get; set; }
        public decimal qty { get; set; }
        public decimal qty_fgs { get; set; }
        public decimal qty_unfgs { get; set; }
        public decimal qty_unfgs1 { get; set; }
        public decimal qty_loss { get; set; }
        public string remark { get; set; }
        public string org_file_no { get; set; }
        public Nullable<int> org_seq_no { get; set; }
        public string File_No1 { get; set; }
    }
}
