//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1577
    {
        public int Acc_Year { get; set; }
        public int Acc_Month { get; set; }
        public string st_code { get; set; }
        public string curr_code { get; set; }
        public string cust_code { get; set; }
        public int Flag1 { get; set; }
        public decimal Amt_Debit1 { get; set; }
        public decimal Amt_Credit1 { get; set; }
        public decimal Amt_Bal1 { get; set; }
        public bool Bal_Direct { get; set; }
        public decimal Ex_Rate { get; set; }
        public string Remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string chk_code { get; set; }
        public decimal Amt_Debit { get; set; }
        public decimal Amt_Credit { get; set; }
        public decimal Amt_Bal { get; set; }
    }
}
