//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1579
    {
        public int Acc_Year { get; set; }
        public int Acc_Month { get; set; }
        public string PCC_Code { get; set; }
        public string CC_Code { get; set; }
        public string Active_Type { get; set; }
        public string Item_Type { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> Amt_Per { get; set; }
    }
}
