//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1572
    {
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty_Per { get; set; }
        public decimal Qty_Yield { get; set; }
        public decimal Qty_F { get; set; }
        public string G_No { get; set; }
    }
}
