//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1571
    {
        public string File_no { get; set; }
        public int Seq_No { get; set; }
        public string qc_code { get; set; }
        public decimal qty { get; set; }
        public string Org_Code { get; set; }
    }
}
