//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1588
    {
        public int Acc_Year { get; set; }
        public int Acc_Month { get; set; }
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string Line_Code { get; set; }
        public string Lot_No { get; set; }
        public string Job_No { get; set; }
        public string Item_No { get; set; }
        public decimal qty_in { get; set; }
        public decimal qty_out { get; set; }
        public decimal qty_bal { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Item_Desc { get; set; }
        public string Uom { get; set; }
        public Nullable<int> Lot_Flag { get; set; }
        public string SysUser { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public Nullable<bool> Check_Flag { get; set; }
    }
}
