//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1589
    {
        public long AutoID { get; set; }
        public string ToUser { get; set; }
        public string FrmUser { get; set; }
        public Nullable<bool> Read_Flag { get; set; }
        public string Message { get; set; }
    }
}
