//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1586
    {
        public string CItem_No { get; set; }
        public int Seq_No { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string Item_No { get; set; }
        public string Color { get; set; }
        public string Cust_code { get; set; }
    }
}
