//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1597
    {
        public string Po_No { get; set; }
        public int Seq_No { get; set; }
        public string Amt_Desc { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Tran_Type { get; set; }
    }
}
