//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1603
    {
        public int Acc_Year { get; set; }
        public int Acc_Month { get; set; }
        public string Vh_No { get; set; }
        public int Vh_Seq { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string File_No { get; set; }
        public Nullable<int> File_Seq { get; set; }
        public string Job_No { get; set; }
        public string So_No { get; set; }
        public Nullable<decimal> Seq_No { get; set; }
    }
}
