//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1602
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public int File_SSeq { get; set; }
        public System.DateTime St_Date { get; set; }
        public System.DateTime Fn_Date { get; set; }
        public string Lot_No { get; set; }
        public decimal Mps_Seq_No { get; set; }
        public int SSeq_No { get; set; }
        public string Emp_Code { get; set; }
        public string Line_Code { get; set; }
        public string Bol_Code { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal qty_f { get; set; }
        public string remark { get; set; }
        public string sysremark { get; set; }
    }
}
