//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1612
    {
        public string File_No { get; set; }
        public decimal DiscountH { get; set; }
        public string RemarkH { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public int Status_Code { get; set; }
        public bool Appr_Flag { get; set; }
        public string Appr_User { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public string ord_id { get; set; }
        public bool export_flag { get; set; }
        public decimal Amt_Rec { get; set; }
        public Nullable<bool> NotPay_Flag { get; set; }
        public Nullable<bool> Bank_Flag { get; set; }
        public Nullable<decimal> Amt_Rec_Bank { get; set; }
        public Nullable<bool> AmtEdit_Flag { get; set; }
        public bool AmtClose_Flag { get; set; }
    }
}
