//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1617
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public int IO_Flag { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal Discount { get; set; }
        public decimal Amt { get; set; }
        public string Loc_Code { get; set; }
        public string Sale_Org_Code { get; set; }
        public string Cust_Code { get; set; }
        public string So_No { get; set; }
        public decimal So_Seq { get; set; }
        public string Remark { get; set; }
        public string Sales { get; set; }
        public bool Free_Flag { get; set; }
        public int Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal qty_rej { get; set; }
        public string org_file_no { get; set; }
        public string org_seq_no { get; set; }
        public Nullable<int> repair_times { get; set; }
        public Nullable<System.DateTime> repair_todate { get; set; }
        public bool export_flag1 { get; set; }
    }
}
