//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1610
    {
        public string pl_no { get; set; }
        public string Ord_Id { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string loc_code { get; set; }
        public string cust_code { get; set; }
        public string fm_add1 { get; set; }
        public string fm_add2 { get; set; }
        public string fm_add3 { get; set; }
        public string fm_add4 { get; set; }
        public int ttl_cnt { get; set; }
        public bool approve { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public string remark { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public bool export_flag { get; set; }
    }
}
