//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1628
    {
        public string Cust_code { get; set; }
        public string SHOP_CODE { get; set; }
        public string SHOP_DESCC { get; set; }
        public string SHOP_DESCE { get; set; }
        public string CONTACT { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public Nullable<int> STATUS_CODE { get; set; }
        public string SYSUSER { get; set; }
        public System.DateTime SYSDATE { get; set; }
    }
}
