//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1629
    {
        public string ITEM_NO { get; set; }
        public string LOC_CODE { get; set; }
        public string CURR_CODE { get; set; }
        public decimal UNIT_PRICE1 { get; set; }
        public decimal UNIT_PRICE2 { get; set; }
        public decimal UNIT_PRICE3 { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Last_User { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public bool export_flag { get; set; }
        public bool export_flag1 { get; set; }
    }
}
