//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1620A
    {
        public string Org_Code { get; set; }
        public string para_code { get; set; }
        public string item_code { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
    }
}
