//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1622
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty_Stk1 { get; set; }
        public decimal Qty_Stk2 { get; set; }
        public decimal Qty_Stk3 { get; set; }
        public int Day_Sale { get; set; }
        public decimal Qty_Sale { get; set; }
        public decimal Qty_Sale_Per { get; set; }
        public decimal Qty_Layer { get; set; }
        public decimal Qty_Layer_Per { get; set; }
        public decimal Qty_Array_Per { get; set; }
        public decimal Qty_Stk_Min { get; set; }
        public decimal Qty_Stk_Max { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_F { get; set; }
        public Nullable<decimal> Qty_Bal { get; set; }
        public int Status_Code { get; set; }
        public decimal Obj_Stk_Days { get; set; }
        public Nullable<System.DateTime> IssueTime { get; set; }
        public string remark { get; set; }
        public bool Repair_Flag { get; set; }
        public decimal qty_case { get; set; }
        public decimal qty_per_case { get; set; }
        public decimal Qty_Loc_Frm { get; set; }
        public Nullable<decimal> Qty_Loc_FrmSon { get; set; }
        public Nullable<int> He_FlowID { get; set; }
    }
}
