//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1626
    {
        public string FILE_NO { get; set; }
        public string ORD_ID { get; set; }
        public string FILE_DESCC { get; set; }
        public string FILE_DESCE { get; set; }
        public int STATUS_CODE { get; set; }
        public string SYSUSER { get; set; }
        public System.DateTime SYSDATE { get; set; }
        public string Last_User { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
    }
}
