//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1632
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string F_Table_Name { get; set; }
        public string F_Table_Field { get; set; }
        public string T_Table_Name { get; set; }
        public string T_Table_Field { get; set; }
        public int Status_Code { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
    }
}
