//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1647
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public int SSeq_No { get; set; }
        public string Job_No { get; set; }
        public string item_no { get; set; }
        public Nullable<decimal> Mps_Seq_No { get; set; }
        public Nullable<decimal> Bol_Seq_No { get; set; }
        public string Bol_Code { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_Pass { get; set; }
        public decimal Qty_Scrap { get; set; }
        public decimal Qty_Repair { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
