//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1645
    {
        public int Acc_Year { get; set; }
        public int Acc_Month { get; set; }
        public string So_No { get; set; }
        public decimal Seq_No { get; set; }
        public string CC_Code { get; set; }
        public string Active_Type { get; set; }
        public string Item_Type { get; set; }
        public string St_Code { get; set; }
        public decimal Amt_In { get; set; }
        public decimal Amt_Out { get; set; }
        public decimal Amt_Bal { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public decimal Amt_OutOther { get; set; }
        public decimal amt_InOther { get; set; }
    }
}
