//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1655
    {
        public string mKey { get; set; }
        public string mType { get; set; }
        public string find_user { get; set; }
        public string use_user { get; set; }
        public Nullable<System.DateTime> use_time { get; set; }
        public Nullable<int> t_seq_no { get; set; }
        public Nullable<int> s_seq_no { get; set; }
        public string sun_type { get; set; }
        public string gen_type { get; set; }
        public string material_type { get; set; }
        public string shape_type { get; set; }
        public string key_word { get; set; }
        public string pages { get; set; }
        public Nullable<System.DateTime> sortname_date { get; set; }
        public Nullable<int> sortname_desc { get; set; }
        public string first_page { get; set; }
        public Nullable<int> fixed_sortname { get; set; }
        public Nullable<decimal> t_qty { get; set; }
        public Nullable<decimal> qty_of_firstpage { get; set; }
        public bool Status_Code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
