//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1675
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public int SSeq_No { get; set; }
        public string Pos_Code { get; set; }
        public int Pos_Row { get; set; }
        public int Pos_Col { get; set; }
        public int Layer_Num { get; set; }
        public int List_Layer { get; set; }
        public int He_Num { get; set; }
        public int Item_Seq { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Item_No { get; set; }
        public string Loc_Code { get; set; }
    }
}
