//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1672
    {
        public string Loc_Code { get; set; }
        public string Pos_Code { get; set; }
        public int Pos_Row { get; set; }
        public int Pos_Col { get; set; }
        public Nullable<int> Layer_Num { get; set; }
        public Nullable<bool> Layer_Mode { get; set; }
        public Nullable<int> List_Layer { get; set; }
        public string Loc_Type06 { get; set; }
        public Nullable<int> RowHeight { get; set; }
        public Nullable<int> ColWidth { get; set; }
        public Nullable<int> RowSeq_No { get; set; }
        public Nullable<int> ColSeq_No { get; set; }
        public Nullable<bool> FirstRow_Col_Flag { get; set; }
        public string Pos_Descc { get; set; }
        public string Pos_Desce { get; set; }
        public Nullable<bool> NotCal_Flag { get; set; }
        public string Pos_Grp { get; set; }
        public Nullable<bool> Export_Flag { get; set; }
    }
}
