//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1680
    {
        public int Period { get; set; }
        public string Loc_Code { get; set; }
        public string Pos_Code { get; set; }
        public string OurModel { get; set; }
        public Nullable<System.DateTime> S_Date { get; set; }
        public bool Status_Code { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
