//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1903
    {
        public string Item_Type { get; set; }
        public string Para_Code { get; set; }
        public string item_code { get; set; }
        public string e_name { get; set; }
        public string c_name { get; set; }
        public decimal para_val { get; set; }
        public Nullable<System.DateTime> para_date { get; set; }
        public string para_str { get; set; }
        public string para_desc { get; set; }
        public short status_code { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
    }
}
