//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1959
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string Item_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Qty_F { get; set; }
        public decimal unit_price { get; set; }
        public decimal Discount { get; set; }
        public decimal Amt { get; set; }
        public string Spec1 { get; set; }
        public string Remark { get; set; }
        public int Status_Code { get; set; }
        public Nullable<bool> ctrl_Date_Flag { get; set; }
        public Nullable<System.DateTime> frm_Date { get; set; }
        public Nullable<System.DateTime> to_Date { get; set; }
        public Nullable<decimal> Tax_Rate { get; set; }
        public Nullable<bool> TaxRate_Flag { get; set; }
        public string TaxSt_Code { get; set; }
        public Nullable<bool> edit_Flag { get; set; }
        public Nullable<System.DateTime> Ftd { get; set; }
        public string item_desc { get; set; }
        public string spec101 { get; set; }
        public string spec102 { get; set; }
        public string spec107 { get; set; }
        public string itempath { get; set; }
        public decimal V_Unit_Price { get; set; }
        public decimal V_Amt { get; set; }
        public decimal Amt_Other { get; set; }
        public decimal Amt_Profit { get; set; }
        public Nullable<int> TIMES { get; set; }
        public string D059B { get; set; }
    }
}
