//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1956
    {
        public string File_No { get; set; }
        public string Form_No { get; set; }
        public string Ctr_No { get; set; }
        public string ToCtr_No { get; set; }
        public string ToCtr_prop { get; set; }
        public string Table_Name { get; set; }
        public string Field_Name { get; set; }
        public string Table_Name1 { get; set; }
        public string Field_Name1 { get; set; }
        public bool Mul_flag { get; set; }
        public int Status_Code { get; set; }
    }
}
