//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1953
    {
        public string Rpt_Code { get; set; }
        public int MRow { get; set; }
        public int MCol { get; set; }
        public string Field_Name { get; set; }
        public int Seq_No { get; set; }
        public int Sseq_No { get; set; }
        public int Data_Type { get; set; }
        public string Font { get; set; }
        public Nullable<decimal> Fontsize { get; set; }
        public Nullable<bool> L_LINE { get; set; }
        public Nullable<bool> R_LINE { get; set; }
        public Nullable<bool> T_LINE { get; set; }
        public Nullable<bool> B_LINE { get; set; }
    }
}
