//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1958
    {
        public string File_No { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public string ord_id { get; set; }
        public string sales { get; set; }
        public string SaleOrg_Code { get; set; }
        public string cust_code { get; set; }
        public string cust_add1 { get; set; }
        public string cust_add2 { get; set; }
        public string cust_add3 { get; set; }
        public string cust_add4 { get; set; }
        public string title { get; set; }
        public string contact { get; set; }
        public string Pay_code { get; set; }
        public string ship_code { get; set; }
        public string sale_code { get; set; }
        public string Remark { get; set; }
        public string curr_code { get; set; }
        public Nullable<decimal> curr_rate { get; set; }
        public Nullable<decimal> t_discount { get; set; }
        public Nullable<decimal> t_damt { get; set; }
        public Nullable<decimal> net_amt { get; set; }
        public Nullable<decimal> ttl_amt { get; set; }
        public Nullable<int> status_code { get; set; }
        public Nullable<bool> ApplyAppr_Flag { get; set; }
        public string Last_User { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public string SysUser { get; set; }
        public bool appr_flag { get; set; }
        public string appr_user { get; set; }
        public Nullable<System.DateTime> appr_date { get; set; }
        public string sysremark { get; set; }
        public string D059A { get; set; }
    }
}
