//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1964
    {
        public string File_No { get; set; }
        public int Seq_No { get; set; }
        public string SQL_Desc { get; set; }
        public string Sql_Type { get; set; }
        public string SQL_NAME { get; set; }
        public int Act_Type { get; set; }
        public string File_Desc { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDate { get; set; }
        public string FilterParas { get; set; }
        public string Proc_Para { get; set; }
        public string m_skey { get; set; }
    }
}
