//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class H1966
    {
        public long ID { get; set; }
        public string KzqName { get; set; }
        public string KzqIP { get; set; }
        public string KzqServerIP { get; set; }
        public int Port { get; set; }
        public string KzqYima { get; set; }
        public string KzqLyip { get; set; }
        public string KzqWlh { get; set; }
        public string KzqPin { get; set; }
        public string Kzq_Desc { get; set; }
        public string Remark { get; set; }
        public System.DateTime SysDate { get; set; }
        public string SysUser { get; set; }
    }
}
