//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_baseset
    {
        public string baseid { get; set; }
        public string basedesc { get; set; }
        public Nullable<decimal> timepcs { get; set; }
        public Nullable<byte> timeto { get; set; }
        public Nullable<int> laterfan { get; set; }
        public Nullable<int> earlyleavefan { get; set; }
        public Nullable<bool> laterto { get; set; }
        public Nullable<int> latertime { get; set; }
        public Nullable<int> goodtime1 { get; set; }
        public Nullable<bool> earlyto { get; set; }
        public Nullable<int> earlytime { get; set; }
        public Nullable<int> goodtime2 { get; set; }
        public Nullable<bool> beforeto { get; set; }
        public Nullable<int> beforetime { get; set; }
        public Nullable<int> goodtime3 { get; set; }
        public Nullable<bool> afterto { get; set; }
        public Nullable<int> aftertime { get; set; }
        public Nullable<int> goodtime4 { get; set; }
        public Nullable<bool> defaultbase { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
