//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_checked_data
    {
        public long autoid { get; set; }
        public Nullable<long> myid { get; set; }
        public Nullable<System.DateTime> rdate { get; set; }
        public Nullable<bool> weekend { get; set; }
        public Nullable<bool> weeksun { get; set; }
        public string hols { get; set; }
        public Nullable<System.DateTime> in1 { get; set; }
        public Nullable<System.DateTime> out1 { get; set; }
        public Nullable<System.DateTime> in2 { get; set; }
        public Nullable<System.DateTime> out2 { get; set; }
        public Nullable<System.DateTime> in3 { get; set; }
        public Nullable<System.DateTime> out3 { get; set; }
        public Nullable<System.DateTime> in4 { get; set; }
        public Nullable<System.DateTime> out4 { get; set; }
        public Nullable<System.DateTime> in5 { get; set; }
        public Nullable<System.DateTime> out5 { get; set; }
        public Nullable<System.DateTime> in6 { get; set; }
        public Nullable<System.DateTime> out6 { get; set; }
        public Nullable<System.DateTime> out7 { get; set; }
        public Nullable<System.DateTime> in7 { get; set; }
        public string templvid1 { get; set; }
        public Nullable<System.DateTime> out8 { get; set; }
        public Nullable<System.DateTime> in8 { get; set; }
        public string templvid2 { get; set; }
        public Nullable<System.DateTime> out9 { get; set; }
        public Nullable<System.DateTime> in9 { get; set; }
        public string templvid3 { get; set; }
        public Nullable<System.DateTime> out10 { get; set; }
        public Nullable<System.DateTime> in10 { get; set; }
        public string templvid4 { get; set; }
        public Nullable<System.DateTime> out11 { get; set; }
        public Nullable<System.DateTime> in11 { get; set; }
        public string templvid5 { get; set; }
        public Nullable<System.DateTime> out12 { get; set; }
        public Nullable<System.DateTime> in12 { get; set; }
        public string templvid6 { get; set; }
        public Nullable<decimal> ot1 { get; set; }
        public string otid1 { get; set; }
        public Nullable<decimal> ot2 { get; set; }
        public string otid2 { get; set; }
        public Nullable<decimal> ot3 { get; set; }
        public string otid3 { get; set; }
        public Nullable<decimal> ot4 { get; set; }
        public string otid4 { get; set; }
        public Nullable<bool> lvday { get; set; }
        public Nullable<decimal> lv1 { get; set; }
        public string lvid1 { get; set; }
        public Nullable<decimal> lv2 { get; set; }
        public string lvid2 { get; set; }
        public Nullable<decimal> lv3 { get; set; }
        public string lvid3 { get; set; }
        public Nullable<decimal> later { get; set; }
        public Nullable<decimal> earlyleave { get; set; }
        public Nullable<decimal> notworktime { get; set; }
        public string notworkid { get; set; }
        public Nullable<decimal> worktime { get; set; }
        public Nullable<decimal> temptime1 { get; set; }
        public Nullable<decimal> temptime2 { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
