//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_check_item
    {
        public int itemnum { get; set; }
        public string itemdesc { get; set; }
        public string itemproc { get; set; }
        public Nullable<bool> itemstatus { get; set; }
        public Nullable<bool> User_Flag { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
        public bool Hand_Flag { get; set; }
    }
}
