//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_classset
    {
        public string classid { get; set; }
        public string classdesc { get; set; }
        public Nullable<System.DateTime> stime { get; set; }
        public Nullable<bool> s_second { get; set; }
        public Nullable<int> s_before { get; set; }
        public Nullable<int> s_after { get; set; }
        public Nullable<bool> later { get; set; }
        public Nullable<System.DateTime> etime { get; set; }
        public Nullable<bool> e_second { get; set; }
        public Nullable<int> e_before { get; set; }
        public Nullable<int> e_after { get; set; }
        public Nullable<bool> earlyleave { get; set; }
        public Nullable<decimal> resttime { get; set; }
        public Nullable<bool> restcard { get; set; }
        public Nullable<decimal> ottime { get; set; }
        public string ottype { get; set; }
        public Nullable<bool> notwork { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
