//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_company
    {
        public string co_code { get; set; }
        public string co_namec { get; set; }
        public string co_namee { get; set; }
        public string co_addc { get; set; }
        public string co_adde { get; set; }
        public string zipcode { get; set; }
        public string providence { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string logofile { get; set; }
        public string tax_code { get; set; }
        public string bank_acc { get; set; }
        public string bank_descc { get; set; }
        public string bank_desce { get; set; }
        public string dataformat { get; set; }
        public string servername { get; set; }
        public string databasename { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
