//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_document
    {
        public long myid { get; set; }
        public string status_code { get; set; }
        public string code { get; set; }
        public string card_id { get; set; }
        public string namec { get; set; }
        public string namee { get; set; }
        public string country { get; set; }
        public string providence { get; set; }
        public string city { get; set; }
        public string id { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string marital { get; set; }
        public string gender { get; set; }
        public string picture { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<System.DateTime> leave_date { get; set; }
        public string origin { get; set; }
        public string address { get; set; }
        public string police_desc { get; set; }
        public string zipcode { get; set; }
        public string ethnic { get; set; }
        public string hometel { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string http { get; set; }
        public string org_code { get; set; }
        public string place_huji { get; set; }
        public string pos_code { get; set; }
        public Nullable<System.DateTime> stdate_position { get; set; }
        public string work_desc { get; set; }
        public string dri_admin { get; set; }
        public string sal_grade { get; set; }
        public string hr_grade { get; set; }
        public Nullable<System.DateTime> id_lastdate { get; set; }
        public Nullable<bool> contract_y { get; set; }
        public Nullable<System.DateTime> contract_stdate { get; set; }
        public Nullable<System.DateTime> contract_enddate { get; set; }
        public Nullable<decimal> sal_ttl { get; set; }
        public Nullable<decimal> work_age { get; set; }
        public string party_code { get; set; }
        public string hk_type { get; set; }
        public string lab_book { get; set; }
        public string intr_name { get; set; }
        public string intr_rela { get; set; }
        public string intr_comp { get; set; }
        public string intr_con { get; set; }
        public string ex_language { get; set; }
        public Nullable<System.DateTime> bgwork_date { get; set; }
        public string poswork_type { get; set; }
        public string tech_code { get; set; }
        public Nullable<System.DateTime> inparty_date { get; set; }
        public string work_source { get; set; }
        public string lv_work { get; set; }
        public Nullable<decimal> amt_lv_work { get; set; }
        public string amt_rela { get; set; }
        public Nullable<decimal> emp_high { get; set; }
        public Nullable<decimal> emp_weight { get; set; }
        public Nullable<decimal> emp_leye { get; set; }
        public Nullable<decimal> emp_reye { get; set; }
        public string emp_size01 { get; set; }
        public string emp_size02 { get; set; }
        public string emp_size03 { get; set; }
        public Nullable<bool> bl_yes { get; set; }
        public string bl_type { get; set; }
        public Nullable<bool> sm_yes { get; set; }
        public Nullable<bool> cj_yes { get; set; }
        public string cj_desc { get; set; }
        public Nullable<bool> yc_yes { get; set; }
        public string yc_desc { get; set; }
        public Nullable<bool> cr_yes { get; set; }
        public string cr_desc { get; set; }
        public string leave_type { get; set; }
        public string leave_beca { get; set; }
        public string emp_kind { get; set; }
        public string bank_account { get; set; }
        public string bank_name { get; set; }
        public string OT_GRP { get; set; }
        public string LV_GRP { get; set; }
        public Nullable<bool> atsfree { get; set; }
        public Nullable<bool> Is_Test { get; set; }
        public Nullable<System.DateTime> TestFn_Date { get; set; }
        public bool JiJian_Flag { get; set; }
        public decimal Amt_Hour_Per { get; set; }
        public bool PassUser_Flag { get; set; }
    }
}
