//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Empfields
    {
        public string mytable { get; set; }
        public string fld_name { get; set; }
        public string fld_desc { get; set; }
        public string fld_type { get; set; }
        public Nullable<int> fld_size { get; set; }
        public Nullable<int> fld_d { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> mattch { get; set; }
        public string para_grp { get; set; }
        public Nullable<bool> Input_Flag { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
        public int fld_seq { get; set; }
    }
}
