//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_emphisinfo
    {
        public long myid { get; set; }
        public Nullable<bool> status { get; set; }
        public System.DateTime st_date { get; set; }
        public Nullable<System.DateTime> fh_date { get; set; }
        public string company { get; set; }
        public string department { get; set; }
        public string emp_pos { get; set; }
        public Nullable<decimal> emp_sal { get; set; }
        public string tel { get; set; }
        public string emp_per { get; set; }
        public string work_desc { get; set; }
        public string lv_bec { get; set; }
    }
}
