//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_EMPINFOH
    {
        public long MYID { get; set; }
        public Nullable<bool> Cal_Flag { get; set; }
        public Nullable<bool> Bef_Flag { get; set; }
        public string H001 { get; set; }
        public string H002 { get; set; }
    }
}
