//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_empskill
    {
        public int autoid { get; set; }
        public string serialnumber { get; set; }
        public string skillcode { get; set; }
        public string degreecode { get; set; }
        public float skillscore { get; set; }
        public Nullable<System.DateTime> qualifydate { get; set; }
        public float validityperiod { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public byte certificate { get; set; }
        public string certificatenumber { get; set; }
        public string comment { get; set; }
    }
}
