//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_hrchange
    {
        public decimal AUTOID { get; set; }
        public string myid { get; set; }
        public Nullable<decimal> A001_FRM { get; set; }
        public Nullable<decimal> A002_FRM { get; set; }
        public Nullable<decimal> A003_FRM { get; set; }
        public Nullable<decimal> A004_FRM { get; set; }
        public Nullable<decimal> A001_TO { get; set; }
        public Nullable<decimal> A002_TO { get; set; }
        public Nullable<decimal> A003_TO { get; set; }
        public Nullable<decimal> A004_TO { get; set; }
        public string poscode_frm { get; set; }
        public string poscode_to { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
