//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_importset
    {
        public int setname { get; set; }
        public string importfile { get; set; }
        public Nullable<int> importtype { get; set; }
        public Nullable<System.DateTime> stime { get; set; }
        public Nullable<System.DateTime> etime { get; set; }
        public Nullable<System.DateTime> lasttime { get; set; }
        public Nullable<int> timenum { get; set; }
        public Nullable<bool> status { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
