//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_lvrule
    {
        public string lv_grp { get; set; }
        public string lv_type { get; set; }
        public Nullable<bool> type_id { get; set; }
        public Nullable<decimal> lv_amt_h { get; set; }
        public string lv_amt_cal { get; set; }
        public string lvid { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
