//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_lvlist_set
    {
        public decimal autoid { get; set; }
        public string lvid { get; set; }
        public Nullable<bool> ynlist { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<bool> onlylist { get; set; }
        public Nullable<bool> toweekend { get; set; }
        public Nullable<bool> status { get; set; }
        public string allone { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
