//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_olddata
    {
        public long autoid { get; set; }
        public string card_id { get; set; }
        public Nullable<System.DateTime> indate { get; set; }
        public string intime { get; set; }
        public string address { get; set; }
        public Nullable<decimal> myid { get; set; }
        public Nullable<bool> status { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
