//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_otset
    {
        public string otid { get; set; }
        public string otdesc { get; set; }
        public Nullable<decimal> timepcs { get; set; }
        public Nullable<byte> timeto { get; set; }
        public Nullable<int> laterfan { get; set; }
        public Nullable<int> earlyleavefan { get; set; }
        public Nullable<bool> autoin { get; set; }
        public Nullable<int> in1 { get; set; }
        public Nullable<bool> autoout { get; set; }
        public Nullable<int> out1 { get; set; }
        public Nullable<bool> laterto { get; set; }
        public Nullable<int> latertime { get; set; }
        public Nullable<int> goodtime1 { get; set; }
        public Nullable<bool> earlyto { get; set; }
        public Nullable<int> earlytime { get; set; }
        public Nullable<int> goodtime2 { get; set; }
        public Nullable<bool> defaultot { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
