//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_planclass_temp
    {
        public long myid { get; set; }
        public string mydesc { get; set; }
        public System.DateTime pdate { get; set; }
        public string ptype { get; set; }
        public Nullable<bool> weekend { get; set; }
        public Nullable<bool> weeksun { get; set; }
        public string hols { get; set; }
        public string time1_classid { get; set; }
        public string intime1 { get; set; }
        public Nullable<bool> intime1_second { get; set; }
        public Nullable<int> intime1_before { get; set; }
        public Nullable<int> intime1_after { get; set; }
        public Nullable<bool> intime1_later { get; set; }
        public string outtime1 { get; set; }
        public Nullable<bool> outtime1_second { get; set; }
        public Nullable<int> outtime1_before { get; set; }
        public Nullable<int> outtime1_after { get; set; }
        public Nullable<bool> outtime1_earlyleave { get; set; }
        public Nullable<decimal> time1_resttime { get; set; }
        public Nullable<bool> time1_restcard { get; set; }
        public Nullable<decimal> time1_ottime { get; set; }
        public Nullable<bool> time1_notwork { get; set; }
        public string time1_baseid { get; set; }
        public string time1_memo { get; set; }
        public string time2_classid { get; set; }
        public string intime2 { get; set; }
        public Nullable<bool> intime2_second { get; set; }
        public Nullable<int> intime2_before { get; set; }
        public Nullable<int> intime2_after { get; set; }
        public Nullable<bool> intime2_later { get; set; }
        public string outtime2 { get; set; }
        public Nullable<bool> outtime2_second { get; set; }
        public Nullable<int> outtime2_before { get; set; }
        public Nullable<int> outtime2_after { get; set; }
        public Nullable<bool> outtime2_earlyleave { get; set; }
        public Nullable<decimal> time2_resttime { get; set; }
        public Nullable<bool> time2_restcard { get; set; }
        public Nullable<decimal> time2_ottime { get; set; }
        public Nullable<bool> time2_notwork { get; set; }
        public string time2_baseid { get; set; }
        public string time2_memo { get; set; }
        public string time3_classid { get; set; }
        public string intime3 { get; set; }
        public Nullable<bool> intime3_second { get; set; }
        public Nullable<int> intime3_before { get; set; }
        public Nullable<int> intime3_after { get; set; }
        public Nullable<bool> intime3_later { get; set; }
        public string outtime3 { get; set; }
        public Nullable<bool> outtime3_second { get; set; }
        public Nullable<int> outtime3_before { get; set; }
        public Nullable<int> outtime3_after { get; set; }
        public Nullable<bool> outtime3_earlyleave { get; set; }
        public Nullable<decimal> time3_resttime { get; set; }
        public Nullable<bool> time3_restcard { get; set; }
        public Nullable<decimal> time3_ottime { get; set; }
        public Nullable<bool> time3_notwork { get; set; }
        public string time3_baseid { get; set; }
        public string time3_memo { get; set; }
        public string ot1_classid { get; set; }
        public string otintime1 { get; set; }
        public Nullable<bool> otintime1_second { get; set; }
        public Nullable<int> otintime1_before { get; set; }
        public Nullable<int> otintime1_after { get; set; }
        public Nullable<bool> otintime1_later { get; set; }
        public string otouttime1 { get; set; }
        public Nullable<bool> otouttime1_second { get; set; }
        public Nullable<int> otouttime1_before { get; set; }
        public Nullable<int> otouttime1_after { get; set; }
        public Nullable<bool> otouttime1_earlyleave { get; set; }
        public Nullable<decimal> ottime1_resttime { get; set; }
        public Nullable<bool> ottime1_restcard { get; set; }
        public Nullable<bool> ottime1_notwork { get; set; }
        public string ottime1_ottype { get; set; }
        public string ottime1_policy { get; set; }
        public string ottime1_memo { get; set; }
        public string ot2_classid { get; set; }
        public string otintime2 { get; set; }
        public Nullable<bool> otintime2_second { get; set; }
        public Nullable<int> otintime2_before { get; set; }
        public Nullable<int> otintime2_after { get; set; }
        public Nullable<bool> otintime2_later { get; set; }
        public string otouttime2 { get; set; }
        public Nullable<bool> otouttime2_second { get; set; }
        public Nullable<int> otouttime2_before { get; set; }
        public Nullable<int> otouttime2_after { get; set; }
        public Nullable<bool> otouttime2_earlyleave { get; set; }
        public Nullable<decimal> ottime2_resttime { get; set; }
        public Nullable<bool> ottime2_restcard { get; set; }
        public Nullable<bool> ottime2_notwork { get; set; }
        public string ottime2_ottype { get; set; }
        public string ottime2_policy { get; set; }
        public string ottime2_memo { get; set; }
        public string ot3_classid { get; set; }
        public string otintime3 { get; set; }
        public Nullable<bool> otintime3_second { get; set; }
        public Nullable<int> otintime3_before { get; set; }
        public Nullable<int> otintime3_after { get; set; }
        public Nullable<bool> otintime3_later { get; set; }
        public string otouttime3 { get; set; }
        public Nullable<bool> otouttime3_second { get; set; }
        public Nullable<int> otouttime3_before { get; set; }
        public Nullable<int> otouttime3_after { get; set; }
        public Nullable<bool> otouttime3_earlyleave { get; set; }
        public Nullable<decimal> ottime3_resttime { get; set; }
        public Nullable<bool> ottime3_restcard { get; set; }
        public Nullable<bool> ottime3_notwork { get; set; }
        public string ottime3_ottype { get; set; }
        public string ottime3_policy { get; set; }
        public string ottime3_memo { get; set; }
        public Nullable<bool> lvday { get; set; }
        public string lvstime1 { get; set; }
        public Nullable<bool> lvstime1_second { get; set; }
        public string lvetime1 { get; set; }
        public Nullable<bool> lvetime1_second { get; set; }
        public string lvid1 { get; set; }
        public string lvtime1_memo { get; set; }
        public string lvstime2 { get; set; }
        public Nullable<bool> lvstime2_second { get; set; }
        public string lvetime2 { get; set; }
        public Nullable<bool> lvetime2_second { get; set; }
        public string lvid2 { get; set; }
        public string lvtime2_memo { get; set; }
        public string lvstime3 { get; set; }
        public Nullable<bool> lvstime3_second { get; set; }
        public string lvetime3 { get; set; }
        public Nullable<bool> lvetime3_second { get; set; }
        public string lvid3 { get; set; }
        public string lvtime3_memo { get; set; }
        public Nullable<bool> lvlong { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
