//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_print_set
    {
        public int autoid { get; set; }
        public string procitem { get; set; }
        public int num { get; set; }
        public string pagehead { get; set; }
        public string pageheadfont { get; set; }
        public Nullable<int> pageheadsize { get; set; }
        public Nullable<int> pageheadlmr { get; set; }
        public string pagefoot { get; set; }
        public string pagefootfont { get; set; }
        public Nullable<int> pagefootsize { get; set; }
        public Nullable<int> pagefootlmr { get; set; }
        public Nullable<bool> hormid { get; set; }
        public Nullable<bool> vermid { get; set; }
        public Nullable<int> mtop { get; set; }
        public Nullable<int> mbottom { get; set; }
        public Nullable<int> mleft { get; set; }
        public Nullable<int> mright { get; set; }
        public Nullable<int> org { get; set; }
        public Nullable<int> startpagenum { get; set; }
        public Nullable<bool> rownumyn { get; set; }
        public Nullable<bool> colnumyn { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
