//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_salarydatA
    {
        public int acc_year { get; set; }
        public int acc_month { get; set; }
        public long myid { get; set; }
        public string namec { get; set; }
        public string namee { get; set; }
        public string pos_code { get; set; }
        public Nullable<decimal> amt_sal { get; set; }
        public Nullable<decimal> amt_detail { get; set; }
        public Nullable<decimal> amt_detail_out { get; set; }
        public Nullable<decimal> amt_detail_bal { get; set; }
        public Nullable<decimal> amt_net { get; set; }
        public Nullable<decimal> amt_real { get; set; }
        public Nullable<decimal> amt_bank { get; set; }
        public string bank_account { get; set; }
        public string bank_name { get; set; }
        public Nullable<decimal> A001 { get; set; }
        public Nullable<decimal> A002 { get; set; }
        public Nullable<decimal> A003 { get; set; }
        public Nullable<decimal> A004 { get; set; }
        public Nullable<decimal> A006 { get; set; }
        public Nullable<decimal> A005 { get; set; }
        public Nullable<decimal> C001 { get; set; }
        public Nullable<decimal> C002 { get; set; }
        public Nullable<decimal> B001 { get; set; }
        public Nullable<decimal> B002 { get; set; }
        public Nullable<decimal> B003 { get; set; }
        public Nullable<decimal> C003 { get; set; }
    }
}
