//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_salarydatC
    {
        public int acc_year { get; set; }
        public int acc_month { get; set; }
        public long myid { get; set; }
        public string LV_GRP { get; set; }
        public string LV1_Type { get; set; }
        public Nullable<decimal> LV1_HOURS { get; set; }
        public string LV1_CAL { get; set; }
        public Nullable<decimal> LV1_Amt_H { get; set; }
        public Nullable<decimal> LV1_AMT { get; set; }
        public string LV2_Type { get; set; }
        public Nullable<decimal> LV2_HOURS { get; set; }
        public string LV2_CAL { get; set; }
        public Nullable<decimal> LV2_Amt_H { get; set; }
        public Nullable<decimal> LV2_AMT { get; set; }
        public string LV3_Type { get; set; }
        public Nullable<decimal> LV3_HOURs { get; set; }
        public string LV3_CAL { get; set; }
        public Nullable<decimal> LV3_Amt_H { get; set; }
        public Nullable<decimal> LV3_AMT { get; set; }
        public string LV4_Type { get; set; }
        public Nullable<decimal> LV4_HOURS { get; set; }
        public string LV4_CAL { get; set; }
        public Nullable<decimal> LV4_Amt_H { get; set; }
        public Nullable<decimal> LV4_AMT { get; set; }
    }
}
