//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_salchange
    {
        public long myid { get; set; }
        public System.DateTime tran_date { get; set; }
        public string para_code { get; set; }
        public string result { get; set; }
        public string remark { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
        public Nullable<decimal> A001 { get; set; }
        public Nullable<decimal> A001_Bef { get; set; }
        public Nullable<decimal> A002 { get; set; }
        public Nullable<decimal> A002_Bef { get; set; }
        public Nullable<decimal> A003 { get; set; }
        public Nullable<decimal> A003_Bef { get; set; }
        public Nullable<decimal> A004 { get; set; }
        public Nullable<decimal> A004_Bef { get; set; }
        public Nullable<decimal> A006 { get; set; }
        public Nullable<decimal> A006_Bef { get; set; }
        public Nullable<decimal> A005 { get; set; }
        public Nullable<decimal> A005_Bef { get; set; }
        public Nullable<decimal> C001 { get; set; }
        public Nullable<decimal> C001_Bef { get; set; }
        public Nullable<decimal> C002 { get; set; }
        public Nullable<decimal> C002_Bef { get; set; }
        public Nullable<decimal> B001 { get; set; }
        public Nullable<decimal> B001_Bef { get; set; }
        public Nullable<decimal> B002 { get; set; }
        public Nullable<decimal> B002_Bef { get; set; }
        public Nullable<decimal> B003 { get; set; }
        public Nullable<decimal> B003_Bef { get; set; }
        public Nullable<decimal> C003 { get; set; }
        public Nullable<decimal> C003_Bef { get; set; }
    }
}
