//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SALARYDATHEAD
    {
        public int acc_year { get; set; }
        public int acc_month { get; set; }
        public Nullable<int> month_hrs { get; set; }
        public Nullable<int> month_sathrs { get; set; }
        public Nullable<int> month_sunhrs { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
