//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_sendhrp
    {
        public decimal autoid { get; set; }
        public Nullable<decimal> myid { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<decimal> later { get; set; }
        public Nullable<decimal> earlyleave { get; set; }
        public Nullable<decimal> notworktime { get; set; }
        public string ot_type { get; set; }
        public Nullable<decimal> ot { get; set; }
        public string lv_type { get; set; }
        public Nullable<decimal> lv { get; set; }
        public string myuser { get; set; }
        public Nullable<System.DateTime> mydate { get; set; }
    }
}
