//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SYSMENU
    {
        public string Pmenu_key { get; set; }
        public string Smenu_key { get; set; }
        public string menu_descc { get; set; }
        public string menu_desce { get; set; }
        public int grade { get; set; }
        public Nullable<int> menu_type { get; set; }
        public string exefile_name { get; set; }
        public string myuser { get; set; }
        public System.DateTime mydate { get; set; }
    }
}
