//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop001
    {
        public int L_No { get; set; }
        public string Price_Grp { get; set; }
        public int mID { get; set; }
        public string Price_Desc { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public string Unit_Price_Desc { get; set; }
        public string Logo { get; set; }
        public string ZeSe { get; set; }
        public string GNeng { get; set; }
        public string mType { get; set; }
    }
}
