//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eyeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1961
    {
        public string Ref_No { get; set; }
        public string File_No { get; set; }
        public Nullable<int> Seq_No { get; set; }
        public string Item_No { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Qty_F { get; set; }
        public decimal unit_price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Spec1 { get; set; }
        public string Remark { get; set; }
        public int Status_Code { get; set; }
        public Nullable<bool> ctrl_Date_Flag { get; set; }
        public Nullable<System.DateTime> frm_Date { get; set; }
        public Nullable<System.DateTime> to_Date { get; set; }
        public Nullable<bool> edit_Flag { get; set; }
        public string TaxSt_Code { get; set; }
        public Nullable<decimal> Tax_Rate { get; set; }
        public Nullable<bool> TaxRate_Flag { get; set; }
        public string Vdr_Code { get; set; }
        public string Sysuser { get; set; }
        public Nullable<System.DateTime> sysdate { get; set; }
    }
}
